using System.Collections;
using System.Globalization;
using ns284;
using ns301;

namespace ns290;

internal class Class6923 : Interface343
{
	private const string string_0 = "{0}.";

	private readonly Interface344 interface344_0;

	private readonly Interface352 interface352_0;

	private readonly Interface350 interface350_0;

	private readonly Interface351 interface351_0;

	private Class6849 class6849_0;

	private Class6944 class6944_0;

	public Class6923(Interface344 boxFactory, Interface350 whitespaceProcessor)
	{
		Class6892.smethod_0(boxFactory, "boxFactory");
		Class6892.smethod_0(whitespaceProcessor, "whitespaceProcessor");
		interface344_0 = boxFactory;
		interface350_0 = whitespaceProcessor;
		interface351_0 = new Class6942();
		interface352_0 = new Class6943(interface351_0, interface344_0);
	}

	public void imethod_0(Interface329 style, string name)
	{
		Class6892.smethod_0(style, "style");
		class6849_0 = interface344_0.imethod_0(style, name);
		class6849_0.Style.Display = Enum952.const_1;
		class6944_0 = new Class6944(class6849_0, interface351_0);
	}

	public Class6844 imethod_1()
	{
		return class6849_0;
	}

	public void imethod_4(Interface329 style, string name, Interface356 hyperlink)
	{
		Class6892.smethod_0(style, "style");
		Class6845 container = interface344_0.imethod_2(style, name);
		Class6845 container2 = smethod_2(container);
		smethod_3(hyperlink, container);
		Class6845 parentContainer = class6944_0.method_0(container);
		smethod_0(container, parentContainer);
		method_0(ref container, ref parentContainer);
		interface352_0.imethod_2(container, parentContainer, out var wasContainerBoxSplitted, out var newContainer);
		if (wasContainerBoxSplitted)
		{
			class6944_0.method_4(newContainer);
		}
		class6944_0.method_2(container2);
	}

	private static void smethod_0(Class6845 box, Class6845 parent)
	{
		if (box is Class6851 @class && parent != null)
		{
			if (!@class.Style.CounterValue.IsAuto)
			{
				parent.Style.CounterValue = new Class6959(@class.Style.CounterValue.Value - 1f);
			}
			smethod_1(@class.Marker, (int)parent.Style.CounterValue.Value, @class.Style.ListStyle);
			parent.Style.CounterValue = new Class6959((int)parent.Style.CounterValue.Value + @class.Style.CounterIncrementValue);
		}
	}

	private static void smethod_1(Class6855 marker, int counterValue, int style)
	{
		switch (style)
		{
		case 0:
			marker.WordDecoded = "●";
			marker.IsUnicode = true;
			break;
		case 1:
			marker.WordDecoded = "○";
			marker.IsUnicode = true;
			break;
		case 2:
			marker.WordDecoded = "▪";
			marker.IsUnicode = true;
			break;
		case 3:
		case 4:
			marker.WordDecoded = string.Format(CultureInfo.InvariantCulture, "{0}.", new object[1] { counterValue + 1 });
			break;
		case 5:
		{
			string text = Class6966.smethod_1(counterValue + 1);
			marker.WordDecoded = string.Format(CultureInfo.InvariantCulture, "{0}.", new object[1] { text });
			break;
		}
		case 6:
		{
			string text = Class6966.smethod_1(counterValue + 1).ToUpper(CultureInfo.InvariantCulture);
			marker.WordDecoded = string.Format(CultureInfo.InvariantCulture, "{0}.", new object[1] { text });
			break;
		}
		default:
			marker.WordDecoded = "●";
			marker.IsUnicode = true;
			break;
		case 8:
		case 12:
		{
			string text = Class6966.smethod_0(counterValue);
			marker.WordDecoded = string.Format(CultureInfo.InvariantCulture, "{0}.", new object[1] { text });
			break;
		}
		case 9:
		case 13:
		{
			string text = Class6966.smethod_0(counterValue).ToUpper(CultureInfo.InvariantCulture);
			marker.WordDecoded = string.Format(CultureInfo.InvariantCulture, "{0}.", new object[1] { text });
			break;
		}
		case 14:
			break;
		}
	}

	private static Class6845 smethod_2(Class6845 container)
	{
		if (container is Class6851 @class)
		{
			return @class.ContentBox;
		}
		return container;
	}

	private void method_0(ref Class6845 container, ref Class6845 parentContainer)
	{
		if (method_3(ref container, ref parentContainer))
		{
			method_0(ref container, ref parentContainer);
		}
	}

	private void method_1(ref Class6845 container)
	{
		if (method_2(ref container))
		{
			method_1(ref container);
		}
	}

	private bool method_2(ref Class6845 container)
	{
		if (!(container is Class6852) && !(container is Class6854))
		{
			return false;
		}
		Class6845 container2 = interface344_0.imethod_10();
		(container2 as Class6853).IsAutoGenerated = true;
		Class6845 @class = container2;
		method_0(ref container2, ref container);
		container.InnerBoxes.Add(container2);
		container2.Parent = container;
		container = @class;
		return true;
	}

	private bool method_3(ref Class6845 container, ref Class6845 parentContainer)
	{
		if (container is Class6852)
		{
			Class6848 @class = interface344_0.imethod_3();
			@class.InnerBoxes.Add(container);
			@class.Style.TextAlign = container.Style.TextAlign;
			@class.Style.Align = container.Style.Align;
			container.Parent = @class;
			container = @class;
			return true;
		}
		if (container is Class6854 && !(parentContainer is Class6852))
		{
			Class6852 class2 = interface344_0.imethod_8();
			container.Parent = class2;
			class2.InnerBoxes.Add(container);
			container = class2;
			return true;
		}
		if (container is Class6853 && !(parentContainer is Class6854))
		{
			Class6854 class3 = interface344_0.imethod_9();
			class3.IsAutoGenerated = true;
			container.Parent = class3;
			class3.InnerBoxes.Add(container);
			container = class3;
			return true;
		}
		if (!(container is Class6852) && !(container is Class6853) && !(container is Class6854) && (parentContainer is Class6852 || parentContainer is Class6854))
		{
			if (parentContainer.InnerBoxes.Count > 0)
			{
				Class6854 class4 = (Class6854)parentContainer.InnerBoxes[parentContainer.InnerBoxes.Count - 1];
				if (class4.IsAutoGenerated)
				{
					parentContainer = class4;
					if (parentContainer.InnerBoxes.Count > 0)
					{
						Class6853 class5 = parentContainer.InnerBoxes[parentContainer.InnerBoxes.Count - 1] as Class6853;
						if (class5.IsAutoGenerated)
						{
							parentContainer = class5;
						}
					}
				}
			}
			if (!(container is Class6852) && !(container is Class6853) && !(container is Class6854) && (parentContainer is Class6852 || parentContainer is Class6854))
			{
				method_1(ref parentContainer);
			}
		}
		return false;
	}

	public void imethod_2(Interface329 style, string name)
	{
		imethod_4(style, name, null);
	}

	public void imethod_3(Interface329 style, string name)
	{
		class6944_0.method_3(style);
	}

	public void imethod_5(IList words)
	{
		Class6892.smethod_0(words, "words");
		Class6845 container = null;
		for (int i = 0; i < words.Count; i++)
		{
			string word = (string)words[i];
			Class6855 @class = interface344_0.imethod_1(word);
			if (container == null)
			{
				container = class6944_0.method_0(@class);
			}
			if (!interface350_0.imethod_0(@class, container))
			{
				Class6960.smethod_0(@class.Style, container.Style);
				Class6940.smethod_0(@class, @class.Style.TextTransform);
				method_1(ref container);
				interface352_0.imethod_2(@class, container, out var wasContainerBoxSplitted, out var newContainer);
				if (wasContainerBoxSplitted)
				{
					class6944_0.method_4(newContainer);
					container = newContainer;
				}
			}
		}
	}

	public void imethod_6(string name)
	{
		Class6844 box = interface344_0.imethod_4();
		class6944_0.method_0(box);
	}

	public void imethod_7(Interface356 link)
	{
		Class6892.smethod_0(link, "link");
	}

	public void imethod_8()
	{
	}

	private static void smethod_3(Interface356 hyperlink, Class6844 box)
	{
		box.Link = hyperlink;
	}
}
