using System.Collections;

namespace ns290;

internal class Class6854 : Class6845
{
	private bool bool_0;

	private IList ilist_1;

	private float float_5;

	public bool IsAutoGenerated
	{
		get
		{
			return bool_0;
		}
		set
		{
			bool_0 = value;
		}
	}

	public IList ColumnWidths
	{
		get
		{
			return ilist_1;
		}
		set
		{
			ilist_1 = value;
		}
	}

	public Class6852 Table
	{
		get
		{
			if (!(base.Parent is Class6852 result))
			{
				throw new Exception70();
			}
			return result;
		}
	}

	public float MinHeight
	{
		get
		{
			return float_5;
		}
		set
		{
			float_5 = value;
		}
	}

	public Class6854(Class6844 parent)
		: base(parent)
	{
	}
}
