using System;
using System.Collections;
using System.Drawing;
using System.Drawing.Drawing2D;
using ns22;
using ns47;

namespace ns18;

internal class Class1061
{
	private bool bool_0;

	private readonly Class1057 class1057_0;

	private readonly Class1009 class1009_0;

	private readonly bool bool_1;

	internal Class1061(Class1057 class1057_1, Class1009 class1009_1, bool bool_2)
	{
		class1057_0 = class1057_1;
		class1009_0 = class1009_1;
		bool_1 = bool_2;
	}

	internal void method_0(int int_0, float float_0, float float_1)
	{
		if (bool_1)
		{
			class1009_0.method_1("FixedPage");
		}
		else
		{
			class1009_0.method_3("FixedPage");
		}
		if (bool_1)
		{
			class1009_0.method_9("xmlns", "http://schemas.microsoft.com/xps/2005/06");
			class1009_0.method_9("xmlns:x", "http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key");
		}
		class1009_0.method_9("xml:lang", "en-us");
		class1009_0.method_9("Width", Class1059.smethod_1(float_0));
		class1009_0.method_9("Height", Class1059.smethod_1(float_1));
		class1009_0.method_9("Name", $"Page{int_0}");
		if (Class1015.smethod_11(class1057_0.method_8().method_0()) && bool_1)
		{
			class1009_0.method_0().WriteComment($"Generated by {class1057_0.method_8().method_0()}");
		}
		class1009_0.method_3("Canvas");
		Matrix matrix = new Matrix();
		matrix.Scale(1.3333334f, 1.3333334f, MatrixOrder.Prepend);
		class1009_0.method_9("RenderTransform", Class1059.smethod_3(matrix));
	}

	internal void method_1()
	{
		class1009_0.method_4();
		if (bool_1)
		{
			class1009_0.method_2();
		}
		else
		{
			class1009_0.method_4();
		}
	}

	internal void method_2(Class454 class454_0)
	{
		class1009_0.method_3("Canvas");
		if (class454_0.Hyperlink != null)
		{
			class1009_0.method_9("FixedPage.NavigateUri", method_8(class454_0.Hyperlink));
		}
		if (class454_0.imethod_0() != null)
		{
			class1009_0.method_9("RenderTransform", Class1059.smethod_3(class454_0.imethod_0()));
		}
		if (!Class1405.smethod_3(class454_0))
		{
			return;
		}
		if (class454_0.imethod_1() != null && class454_0.imethod_1().method_1().Count > 0)
		{
			ArrayList arrayList = class454_0.imethod_1().method_1();
			Class459 @class = (Class459)arrayList[0];
			if ((double)Math.Abs(@class.method_2().X) > 10000000.0 || (double)Math.Abs(@class.method_2().Y) > 10000000.0)
			{
				return;
			}
		}
		Class470 class2 = new Class470();
		class1009_0.method_9("Clip", class2.method_2(class454_0.imethod_1(), bool_3: true));
	}

	internal void method_3()
	{
		class1009_0.method_4();
	}

	internal void method_4(Class458 class458_0)
	{
		bool_0 = Class773.smethod_0(class1009_0, class1057_0, class458_0);
	}

	internal void method_5()
	{
		if (bool_0)
		{
			Class773.smethod_1(class1009_0);
		}
	}

	internal void method_6(Class465 class465_0)
	{
		class1009_0.method_3("Path");
		if (class465_0.Hyperlink != null)
		{
			class1009_0.method_9("FixedPage.NavigateUri", method_8(class465_0.Hyperlink));
		}
		Class458 class458_ = Class458.smethod_2(new RectangleF(class465_0.method_2(), class465_0.Size));
		Class470 @class = new Class470();
		class1009_0.method_9("Data", @class.method_2(class458_, bool_3: false));
		class1009_0.method_3("Path.Fill");
		Class1056.smethod_1(class1009_0, class1057_0, class465_0.method_3(), class465_0.method_7(), WrapMode.Clamp, null);
		class1009_0.method_4();
		class1009_0.method_4();
	}

	internal void method_7(Class463 class463_0)
	{
		string string_ = class1009_0.method_10(class463_0.Text);
		Class1460 class1460_ = Class1462.smethod_3(class463_0.method_1().Name, class463_0.method_1().Style, bool_0: false);
		string_ = class1057_0.method_2(class1460_, string_);
		if (Class1015.smethod_11(string_))
		{
			string_ = (string_.StartsWith("{") ? ("{}" + string_) : string_);
			class1009_0.method_3("Glyphs");
			class1009_0.method_9("OriginX", Class1025.smethod_11(class463_0.method_4().X));
			class1009_0.method_9("OriginY", Class1025.smethod_11(class463_0.method_4().Y));
			class1009_0.method_9("UnicodeString", string_);
			Color color_ = ((!class463_0.Color.IsEmpty) ? class463_0.Color : (class463_0.method_3().IsEmpty ? Color.Black : class463_0.method_3()));
			class1009_0.method_9("Fill", Class1059.smethod_2(color_));
			class1009_0.method_9("FontRenderingEmSize", Class1025.smethod_11(class463_0.method_1().Size));
			class1460_ = Class1462.smethod_3(class463_0.method_1().Name, class463_0.method_1().Style, bool_0: false);
			string string_2 = class1057_0.vmethod_0(class1460_);
			class1009_0.method_9("FontUri", string_2);
			string text = smethod_0(class463_0.method_1());
			if (Class1015.smethod_11(text))
			{
				class1009_0.method_9("StyleSimulations", text);
			}
			if (class463_0.imethod_0() != null)
			{
				class1009_0.method_9("RenderTransform", Class1059.smethod_3(class463_0.imethod_0()));
			}
			if (class463_0.imethod_1() != null)
			{
				Class470 @class = new Class470();
				class1009_0.method_9("Clip", @class.method_2(class463_0.imethod_1(), bool_3: true));
			}
			if (class463_0.Hyperlink != null)
			{
				class1009_0.method_9("FixedPage.NavigateUri", method_8(class463_0.Hyperlink));
			}
			class1009_0.method_4();
		}
	}

	private static string smethod_0(Class1396 class1396_0)
	{
		string result = "";
		if (class1396_0.method_4().Style != class1396_0.Style)
		{
			if (class1396_0.IsBold && class1396_0.IsItalic)
			{
				result = "BoldItalicSimulation";
			}
			else if (class1396_0.IsBold)
			{
				result = "BoldSimulation";
			}
			else if (class1396_0.IsItalic)
			{
				result = "ItalicSimulation";
			}
		}
		return result;
	}

	private string method_8(Class464 class464_0)
	{
		if (!class464_0.method_2())
		{
			return class464_0.method_3();
		}
		return string.Format(bool_1 ? "../FixedDocument.fdoc#{0}" : "#{0}", class1057_0.method_0(class464_0.method_3()));
	}
}
