using ns16;
using ns24;

namespace ns32;

internal class Class640
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[34]
		{
			new Class541("d", Enum113.const_0, -27273042329604L, 1L, 20L, autogenerated: false),
			new Class541("rw2", Enum113.const_1, -27273042329643L, 0L, -27273042329612L, autogenerated: false),
			new Class541("rh2", Enum113.const_1, -27273042329644L, 0L, -27273042329612L, autogenerated: false),
			new Class541("t1", Enum113.const_7, -27273042329643L, 480000L, 0L, autogenerated: false),
			new Class541("t2", Enum113.const_13, -27273042329644L, 480000L, 0L, autogenerated: false),
			new Class541("da", Enum113.const_5, -27273042329615L, -27273042329616L, 0L, autogenerated: false),
			new Class541("2da", Enum113.const_0, -27273042329617L, 2L, 1L, autogenerated: false),
			new Class541("stAng1", Enum113.const_1, -27273042329645L, 0L, -27273042329617L, autogenerated: false),
			new Class541("swAng1", Enum113.const_1, -27273042329645L, -27273042329618L, 0L, autogenerated: false),
			new Class541("swAng3", Enum113.const_1, -27273042329645L, 0L, -27273042329618L, autogenerated: false),
			new Class541("rw3", Enum113.const_0, -27273042329643L, 1L, 4L, autogenerated: false),
			new Class541("rh3", Enum113.const_0, -27273042329644L, 1L, 4L, autogenerated: false),
			new Class541("ct1", Enum113.const_7, -27273042329644L, -27273042329619L, 0L, autogenerated: false),
			new Class541("st1", Enum113.const_13, -27273042329643L, -27273042329619L, 0L, autogenerated: false),
			new Class541("m1", Enum113.const_10, -27273042329624L, -27273042329625L, 0L, autogenerated: false),
			new Class541("n1", Enum113.const_0, -27273042329643L, -27273042329644L, -27273042329626L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329627L, -27273042329619L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329627L, -27273042329619L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329628L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329644L, -27273042329629L, 0L, autogenerated: false),
			new Class541("ct3", Enum113.const_7, -27273042329623L, -27273042329617L, 0L, autogenerated: false),
			new Class541("st3", Enum113.const_13, -27273042329622L, -27273042329617L, 0L, autogenerated: false),
			new Class541("m3", Enum113.const_10, -27273042329632L, -27273042329633L, 0L, autogenerated: false),
			new Class541("n3", Enum113.const_0, -27273042329622L, -27273042329623L, -27273042329634L, autogenerated: false),
			new Class541("dx3", Enum113.const_7, -27273042329635L, -27273042329617L, 0L, autogenerated: false),
			new Class541("dy3", Enum113.const_13, -27273042329635L, -27273042329617L, 0L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, -27273042329636L, 0L, autogenerated: false),
			new Class541("vc3", Enum113.const_1, -27273042329611L, 0L, -27273042329623L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329639L, -27273042329637L, 0L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329643L, 0L, -27273042329613L, autogenerated: false),
			new Class541("cd", Enum113.const_0, -27273042329645L, 2L, 1L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd4", Enum113.const_0, -27273042329603L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true)
		}, null, null, new Class516[1]
		{
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[18]
			{
				-27273042329630L, -27273042329631L, -27273042329643L, -27273042329644L, -27273042329619L, -27273042329620L, -27273042329638L, -27273042329640L, -27273042329622L, -27273042329623L,
				-27273042329617L, -27273042329621L, -27273042329641L, -27273042329644L, -27273042329613L, -27273042329614L, -27273042329645L, -21600000L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
