using ns16;
using ns24;

namespace ns32;

internal class Class572
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[8]
		{
			new Class341("adj1", 18750L),
			new Class341("adj2", -8333L),
			new Class341("adj3", 18750L),
			new Class341("adj4", -16667L),
			new Class341("adj5", 100000L),
			new Class341("adj6", -16667L),
			new Class341("adj7", 112963L),
			new Class341("adj8", -8333L)
		}, new Class541[11]
		{
			new Class541("y1", Enum113.const_0, -27273042329603L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329602L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("y2", Enum113.const_0, -27273042329603L, 27273042316903L, 100000L, autogenerated: false),
			new Class541("x2", Enum113.const_0, -27273042329602L, 27273042316904L, 100000L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, 27273042316905L, 100000L, autogenerated: false),
			new Class541("x3", Enum113.const_0, -27273042329602L, 27273042316906L, 100000L, autogenerated: false),
			new Class541("y4", Enum113.const_0, -27273042329603L, 27273042316907L, 100000L, autogenerated: false),
			new Class541("x4", Enum113.const_0, -27273042329602L, 27273042316908L, 100000L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329620L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329621L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329622L)
		}, new Class886[4]
		{
			new Class886(polar: false, 27273042316902L, -2147483647L, 2147483647L, 27273042316901L, -2147483647L, 2147483647L, -27273042329613L, -27273042329612L),
			new Class886(polar: false, 27273042316904L, -2147483647L, 2147483647L, 27273042316903L, -2147483647L, 2147483647L, -27273042329615L, -27273042329614L),
			new Class886(polar: false, 27273042316906L, -2147483647L, 2147483647L, 27273042316905L, -2147483647L, 2147483647L, -27273042329617L, -27273042329616L),
			new Class886(polar: false, 27273042316908L, -2147483647L, 2147483647L, 27273042316907L, -2147483647L, 2147483647L, -27273042329619L, -27273042329618L)
		}, new Class516[2]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: false),
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2
			}, new long[8] { -27273042329613L, -27273042329612L, -27273042329615L, -27273042329614L, -27273042329617L, -27273042329616L, -27273042329619L, -27273042329618L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
