using ns16;
using ns24;

namespace ns32;

internal class Class637
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[7]
		{
			new Class541("il", Enum113.const_0, -27273042329602L, 1018L, 21600L, autogenerated: false),
			new Class541("ir", Enum113.const_0, -27273042329602L, 20582L, 21600L, autogenerated: false),
			new Class541("it", Enum113.const_0, -27273042329603L, 3163L, 21600L, autogenerated: false),
			new Class541("ib", Enum113.const_0, -27273042329603L, 18437L, 21600L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329616L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329617L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329618L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[6]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[14]
			{
				3475L, 0L, 18125L, 0L, 3475L, 10800L, -27273042329616L, -27273042329617L, 3475L, 21600L,
				3475L, 10800L, -27273042329618L, -27273042329617L
			}, 21600L, 21600L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329612L, -27273042329614L), new Class887(-27273042329613L, -27273042329615L));
	}
}
