using ns16;
using ns24;

namespace ns32;

internal class Class644
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[14]
		{
			new Class541("dx1", Enum113.const_0, -27273042329602L, 49L, 48L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329602L, 10L, 48L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329612L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329613L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, -27273042329613L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329609L, 0L, -27273042329622L, autogenerated: false),
			new Class541("il", Enum113.const_0, -27273042329602L, 1L, 6L, autogenerated: false),
			new Class541("ir", Enum113.const_0, -27273042329602L, 5L, 6L, autogenerated: false),
			new Class541("ib", Enum113.const_0, -27273042329603L, 2L, 3L, autogenerated: false),
			new Class541("hd3", Enum113.const_0, -27273042329603L, 1L, 3L, autogenerated: true),
			new Class541("hd4", Enum113.const_0, -27273042329603L, 1L, 4L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[2]
		{
			new Class888(-27273042329606L, -27273042329623L, -27273042329624L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329625L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_5,
				Enum115.const_5,
				Enum115.const_0
			}, new long[14]
			{
				-27273042329606L, -27273042329623L, -27273042329616L, -27273042329618L, -27273042329617L, -27273042329623L, -27273042329606L, -27273042329611L, -27273042329614L, -27273042329623L,
				-27273042329615L, -27273042329618L, -27273042329606L, -27273042329623L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329619L, -27273042329623L), new Class887(-27273042329620L, -27273042329621L));
	}
}
