using ns16;
using ns24;

namespace ns32;

internal class Class613
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[10]
		{
			new Class541("idx", Enum113.const_7, -27273042329617L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329618L, 2700000L, 0L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329613L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329613L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329619L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329620L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329621L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_0
			}, new long[10] { -27273042329608L, -27273042329609L, -27273042329606L, -27273042329609L, -27273042329617L, -27273042329618L, -27273042329619L, -27273042329620L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329615L), new Class887(-27273042329614L, -27273042329616L));
	}
}
