using ns16;
using ns24;

namespace ns32;

internal class Class716
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 25000L),
			new Class341("adj2", 16667L)
		}, new Class541[31]
		{
			new Class541("a1", Enum113.const_11, 1L, 27273042316901L, 75000L, autogenerated: false),
			new Class541("maxAdj2", Enum113.const_0, 70000L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, -27273042329613L, autogenerated: false),
			new Class541("ad1", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("ad2", Enum113.const_0, -27273042329604L, -27273042329614L, 100000L, autogenerated: false),
			new Class541("xB", Enum113.const_1, -27273042329610L, 0L, -27273042329616L, autogenerated: false),
			new Class541("yB", Enum113.const_1, -27273042329609L, -27273042329637L, 0L, autogenerated: false),
			new Class541("alfa", Enum113.const_0, -27273042329638L, 1L, 14L, autogenerated: false),
			new Class541("dx0", Enum113.const_15, -27273042329637L, -27273042329619L, 0L, autogenerated: false),
			new Class541("xC", Enum113.const_1, -27273042329617L, 0L, -27273042329620L, autogenerated: false),
			new Class541("dx1", Enum113.const_15, -27273042329615L, -27273042329619L, 0L, autogenerated: false),
			new Class541("yF", Enum113.const_1, -27273042329618L, -27273042329615L, 0L, autogenerated: false),
			new Class541("xF", Enum113.const_1, -27273042329617L, -27273042329622L, 0L, autogenerated: false),
			new Class541("xE", Enum113.const_1, -27273042329624L, -27273042329620L, 0L, autogenerated: false),
			new Class541("yE", Enum113.const_1, -27273042329623L, -27273042329637L, 0L, autogenerated: false),
			new Class541("dy2", Enum113.const_1, -27273042329626L, 0L, -27273042329609L, autogenerated: false),
			new Class541("dy22", Enum113.const_0, -27273042329627L, 1L, 2L, autogenerated: false),
			new Class541("dy3", Enum113.const_0, -27273042329603L, 1L, 20L, autogenerated: false),
			new Class541("yD", Enum113.const_1, -27273042329609L, -27273042329628L, -27273042329629L, autogenerated: false),
			new Class541("dy4", Enum113.const_0, -27273042329639L, 1L, 1L, autogenerated: false),
			new Class541("yP1", Enum113.const_1, -27273042329639L, -27273042329631L, 0L, autogenerated: false),
			new Class541("xP1", Enum113.const_16, -27273042329640L, 0L, 0L, autogenerated: false),
			new Class541("dy5", Enum113.const_0, -27273042329639L, 1L, 2L, autogenerated: false),
			new Class541("yP2", Enum113.const_1, -27273042329623L, -27273042329634L, 0L, autogenerated: false),
			new Class541("xP2", Enum113.const_16, -27273042329641L, 0L, 0L, autogenerated: false),
			new Class541("ssd8", Enum113.const_0, -27273042329604L, 1L, 8L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("hd6", Enum113.const_0, -27273042329603L, 1L, 6L, autogenerated: true),
			new Class541("wd6", Enum113.const_0, -27273042329602L, 1L, 6L, autogenerated: true),
			new Class541("wd4", Enum113.const_0, -27273042329602L, 1L, 4L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329608L, -27273042329611L, -27273042329638L),
			new Class888(-27273042329621L, -27273042329609L, -27273042329642L),
			new Class888(-27273042329610L, -27273042329630L, 0L),
			new Class888(-27273042329625L, -27273042329626L, -27273042329638L)
		}, new Class886[2]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 1L, 75000L, -27273042329624L, -27273042329623L),
			new Class886(polar: false, 27273042316902L, 0L, -27273042329613L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329617L, -27273042329618L)
		}, new Class516[1]
		{
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_0
			}, new long[18]
			{
				-27273042329608L, -27273042329611L, -27273042329633L, -27273042329632L, -27273042329617L, -27273042329618L, -27273042329621L, -27273042329609L, -27273042329610L, -27273042329630L,
				-27273042329625L, -27273042329626L, -27273042329624L, -27273042329623L, -27273042329636L, -27273042329635L, -27273042329608L, -27273042329611L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
