using ns16;
using ns24;

namespace ns32;

internal class Class619
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[5]
		{
			new Class541("y3", Enum113.const_0, -27273042329603L, 5L, 6L, autogenerated: false),
			new Class541("hd3", Enum113.const_0, -27273042329603L, 1L, 3L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[5]
		{
			new Class888(-27273042329606L, -27273042329613L, -27273042329614L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329614L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329615L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329616L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, null, new Class516[3]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[12]
			{
				0L, 1L, 3L, 1L, -27273042329615L, -27273042329615L, 6L, 5L, 3L, 1L,
				0L, -27273042329615L
			}, 6L, 6L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[2]
			{
				Enum115.const_1,
				Enum115.const_3
			}, new long[6] { 6L, 1L, 3L, 1L, 0L, -27273042329615L }, 6L, 6L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[12]
			{
				0L, 1L, 3L, 1L, -27273042329615L, -27273042329615L, 6L, 5L, 3L, 1L,
				0L, -27273042329615L
			}, 6L, 6L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329613L), new Class887(-27273042329610L, -27273042329612L));
	}
}
