using ns16;
using ns24;

namespace ns32;

internal class Class673
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 18750L)
		}, new Class541[37]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("dr", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("iwd2", Enum113.const_1, -27273042329644L, 0L, -27273042329613L, autogenerated: false),
			new Class541("ihd2", Enum113.const_1, -27273042329645L, 0L, -27273042329613L, autogenerated: false),
			new Class541("ang", Enum113.const_5, -27273042329602L, -27273042329603L, 0L, autogenerated: false),
			new Class541("ct", Enum113.const_7, -27273042329615L, -27273042329616L, 0L, autogenerated: false),
			new Class541("st", Enum113.const_13, -27273042329614L, -27273042329616L, 0L, autogenerated: false),
			new Class541("m", Enum113.const_10, -27273042329617L, -27273042329618L, 0L, autogenerated: false),
			new Class541("n", Enum113.const_0, -27273042329614L, -27273042329615L, -27273042329619L, autogenerated: false),
			new Class541("drd2", Enum113.const_0, -27273042329613L, 1L, 2L, autogenerated: false),
			new Class541("dang", Enum113.const_5, -27273042329620L, -27273042329621L, 0L, autogenerated: false),
			new Class541("2dang", Enum113.const_0, -27273042329622L, 2L, 1L, autogenerated: false),
			new Class541("swAng", Enum113.const_1, -10800000L, -27273042329623L, 0L, autogenerated: false),
			new Class541("t3", Enum113.const_5, -27273042329602L, -27273042329603L, 0L, autogenerated: false),
			new Class541("stAng1", Enum113.const_1, -27273042329625L, 0L, -27273042329622L, autogenerated: false),
			new Class541("stAng2", Enum113.const_1, -27273042329626L, 0L, -27273042329646L, autogenerated: false),
			new Class541("ct1", Enum113.const_7, -27273042329615L, -27273042329626L, 0L, autogenerated: false),
			new Class541("st1", Enum113.const_13, -27273042329614L, -27273042329626L, 0L, autogenerated: false),
			new Class541("m1", Enum113.const_10, -27273042329628L, -27273042329629L, 0L, autogenerated: false),
			new Class541("n1", Enum113.const_0, -27273042329614L, -27273042329615L, -27273042329630L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329631L, -27273042329626L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329631L, -27273042329626L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329632L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, -27273042329633L, 0L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329632L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, 0L, -27273042329633L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329644L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329645L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329638L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329638L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329639L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329639L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[8]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329647L),
			new Class888(-27273042329640L, -27273042329642L, -27273042329647L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329646L),
			new Class888(-27273042329640L, -27273042329643L, -27273042329648L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329648L),
			new Class888(-27273042329641L, -27273042329643L, -27273042329648L),
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329641L, -27273042329642L, -27273042329647L)
		}, new Class886[1]
		{
			new Class886(polar: true, 27273042316901L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329613L, -27273042329607L)
		}, new Class516[1]
		{
			new Class516(new Enum115[12]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[30]
			{
				-27273042329608L, -27273042329607L, -27273042329644L, -27273042329645L, -27273042329646L, -27273042329648L, -27273042329644L, -27273042329645L, -27273042329647L, -27273042329648L,
				-27273042329644L, -27273042329645L, 0L, -27273042329648L, -27273042329644L, -27273042329645L, -27273042329648L, -27273042329648L, -27273042329634L, -27273042329635L,
				-27273042329614L, -27273042329615L, -27273042329626L, -27273042329624L, -27273042329636L, -27273042329637L, -27273042329614L, -27273042329615L, -27273042329627L, -27273042329624L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329640L, -27273042329642L), new Class887(-27273042329641L, -27273042329643L));
	}
}
