using ns16;
using ns24;

namespace ns32;

internal class Class594
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[3]
		{
			new Class341("adj1", 25000L),
			new Class341("adj2", 50000L),
			new Class341("adj3", 25000L)
		}, new Class541[45]
		{
			new Class541("maxAdj2", Enum113.const_0, 50000L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, -27273042329612L, autogenerated: false),
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("th", Enum113.const_0, -27273042329604L, -27273042329614L, 100000L, autogenerated: false),
			new Class541("aw", Enum113.const_0, -27273042329604L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("q1", Enum113.const_2, -27273042329615L, -27273042329616L, 4L, autogenerated: false),
			new Class541("wR", Enum113.const_1, -27273042329653L, 0L, -27273042329617L, autogenerated: false),
			new Class541("q7", Enum113.const_0, -27273042329618L, 2L, 1L, autogenerated: false),
			new Class541("q8", Enum113.const_0, -27273042329619L, -27273042329619L, 1L, autogenerated: false),
			new Class541("q9", Enum113.const_0, -27273042329615L, -27273042329615L, 1L, autogenerated: false),
			new Class541("q10", Enum113.const_1, -27273042329620L, 0L, -27273042329621L, autogenerated: false),
			new Class541("q11", Enum113.const_14, -27273042329622L, 0L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_0, -27273042329623L, -27273042329603L, -27273042329619L, autogenerated: false),
			new Class541("maxAdj3", Enum113.const_0, 100000L, -27273042329624L, -27273042329604L, autogenerated: false),
			new Class541("a3", Enum113.const_11, 0L, 27273042316903L, -27273042329625L, autogenerated: false),
			new Class541("ah", Enum113.const_0, -27273042329604L, 27273042316903L, 100000L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329618L, -27273042329615L, 0L, autogenerated: false),
			new Class541("q2", Enum113.const_0, -27273042329603L, -27273042329603L, 1L, autogenerated: false),
			new Class541("q3", Enum113.const_0, -27273042329627L, -27273042329627L, 1L, autogenerated: false),
			new Class541("q4", Enum113.const_1, -27273042329629L, 0L, -27273042329630L, autogenerated: false),
			new Class541("q5", Enum113.const_14, -27273042329631L, 0L, 0L, autogenerated: false),
			new Class541("dx", Enum113.const_0, -27273042329632L, -27273042329618L, -27273042329603L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329618L, -27273042329633L, 0L, autogenerated: false),
			new Class541("x7", Enum113.const_1, -27273042329628L, -27273042329633L, 0L, autogenerated: false),
			new Class541("q6", Enum113.const_1, -27273042329616L, 0L, -27273042329615L, autogenerated: false),
			new Class541("dh", Enum113.const_0, -27273042329636L, 1L, 2L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329634L, 0L, -27273042329637L, autogenerated: false),
			new Class541("x8", Enum113.const_1, -27273042329635L, -27273042329637L, 0L, autogenerated: false),
			new Class541("aw2", Enum113.const_0, -27273042329616L, 1L, 2L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329610L, 0L, -27273042329640L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329611L, 0L, -27273042329627L, autogenerated: false),
			new Class541("swAng", Enum113.const_5, -27273042329627L, -27273042329633L, 0L, autogenerated: false),
			new Class541("mswAng", Enum113.const_1, 0L, 0L, -27273042329643L, autogenerated: false),
			new Class541("iy", Enum113.const_1, -27273042329611L, 0L, -27273042329624L, autogenerated: false),
			new Class541("ix", Enum113.const_2, -27273042329618L, -27273042329628L, 2L, autogenerated: false),
			new Class541("q12", Enum113.const_0, -27273042329615L, 1L, 2L, autogenerated: false),
			new Class541("dang2", Enum113.const_5, -27273042329624L, -27273042329647L, 0L, autogenerated: false),
			new Class541("stAng", Enum113.const_1, -27273042329654L, -27273042329643L, 0L, autogenerated: false),
			new Class541("stAng2", Enum113.const_1, -27273042329654L, 0L, -27273042329648L, autogenerated: false),
			new Class541("swAng2", Enum113.const_1, -27273042329648L, 0L, -27273042329655L, autogenerated: false),
			new Class541("swAng3", Enum113.const_1, -27273042329655L, -27273042329648L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true)
		}, new Class888[5]
		{
			new Class888(-27273042329646L, -27273042329609L, -27273042329654L),
			new Class888(-27273042329647L, -27273042329611L, -27273042329655L),
			new Class888(-27273042329638L, -27273042329642L, -27273042329655L),
			new Class888(-27273042329641L, -27273042329611L, -27273042329655L),
			new Class888(-27273042329639L, -27273042329642L, 0L)
		}, new Class886[3]
		{
			new Class886(polar: false, 27273042316901L, 0L, 27273042316902L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329635L, -27273042329642L),
			new Class886(polar: false, 27273042316902L, 0L, -27273042329612L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329638L, -27273042329611L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316903L, 0L, -27273042329625L, -27273042329610L, -27273042329642L)
		}, new Class516[3]
		{
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_0
			}, new long[18]
			{
				-27273042329641L, -27273042329611L, -27273042329638L, -27273042329642L, -27273042329634L, -27273042329642L, -27273042329618L, -27273042329603L, -27273042329649L, -27273042329644L,
				-27273042329628L, -27273042329609L, -27273042329618L, -27273042329603L, -27273042329654L, -27273042329643L, -27273042329639L, -27273042329642L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[12]
			{
				-27273042329646L, -27273042329645L, -27273042329618L, -27273042329603L, -27273042329650L, -27273042329651L, -27273042329608L, -27273042329611L, -27273042329618L, -27273042329603L,
				-27273042329656L, -27273042329652L
			}, 0L, 0L, Enum271.const_5, stroke: false, extrusionOk: false),
			new Class516(new Enum115[11]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3
			}, new long[30]
			{
				-27273042329646L, -27273042329645L, -27273042329618L, -27273042329603L, -27273042329650L, -27273042329651L, -27273042329608L, -27273042329611L, -27273042329618L, -27273042329603L,
				-27273042329656L, -27273042329655L, -27273042329628L, -27273042329609L, -27273042329618L, -27273042329603L, -27273042329654L, -27273042329643L, -27273042329639L, -27273042329642L,
				-27273042329641L, -27273042329611L, -27273042329638L, -27273042329642L, -27273042329634L, -27273042329642L, -27273042329618L, -27273042329603L, -27273042329649L, -27273042329644L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
