using ns16;
using ns24;

namespace ns32;

internal class Class715
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 25000L)
		}, new Class541[50]
		{
			new Class541("a", Enum113.const_11, 12500L, 27273042316901L, 46875L, autogenerated: false),
			new Class541("g0", Enum113.const_1, 50000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g1", Enum113.const_0, -27273042329613L, 30274L, 32768L, autogenerated: false),
			new Class541("g2", Enum113.const_0, -27273042329613L, 12540L, 32768L, autogenerated: false),
			new Class541("g3", Enum113.const_1, -27273042329614L, 50000L, 0L, autogenerated: false),
			new Class541("g4", Enum113.const_1, -27273042329615L, 50000L, 0L, autogenerated: false),
			new Class541("g5", Enum113.const_1, 50000L, 0L, -27273042329614L, autogenerated: false),
			new Class541("g6", Enum113.const_1, 50000L, 0L, -27273042329615L, autogenerated: false),
			new Class541("g7", Enum113.const_0, -27273042329613L, 23170L, 32768L, autogenerated: false),
			new Class541("g8", Enum113.const_1, 50000L, -27273042329620L, 0L, autogenerated: false),
			new Class541("g9", Enum113.const_1, 50000L, 0L, -27273042329620L, autogenerated: false),
			new Class541("g10", Enum113.const_0, -27273042329618L, 3L, 4L, autogenerated: false),
			new Class541("g11", Enum113.const_0, -27273042329619L, 3L, 4L, autogenerated: false),
			new Class541("g12", Enum113.const_1, -27273042329623L, 3662L, 0L, autogenerated: false),
			new Class541("g13", Enum113.const_1, -27273042329624L, 3662L, 0L, autogenerated: false),
			new Class541("g14", Enum113.const_1, -27273042329624L, 12500L, 0L, autogenerated: false),
			new Class541("g15", Enum113.const_1, 100000L, 0L, -27273042329623L, autogenerated: false),
			new Class541("g16", Enum113.const_1, 100000L, 0L, -27273042329625L, autogenerated: false),
			new Class541("g17", Enum113.const_1, 100000L, 0L, -27273042329626L, autogenerated: false),
			new Class541("g18", Enum113.const_1, 100000L, 0L, -27273042329627L, autogenerated: false),
			new Class541("ox1", Enum113.const_0, -27273042329602L, 18436L, 21600L, autogenerated: false),
			new Class541("oy1", Enum113.const_0, -27273042329603L, 3163L, 21600L, autogenerated: false),
			new Class541("ox2", Enum113.const_0, -27273042329602L, 3163L, 21600L, autogenerated: false),
			new Class541("oy2", Enum113.const_0, -27273042329603L, 18436L, 21600L, autogenerated: false),
			new Class541("x8", Enum113.const_0, -27273042329602L, -27273042329621L, 100000L, autogenerated: false),
			new Class541("x9", Enum113.const_0, -27273042329602L, -27273042329622L, 100000L, autogenerated: false),
			new Class541("x10", Enum113.const_0, -27273042329602L, -27273042329623L, 100000L, autogenerated: false),
			new Class541("x12", Enum113.const_0, -27273042329602L, -27273042329625L, 100000L, autogenerated: false),
			new Class541("x13", Enum113.const_0, -27273042329602L, -27273042329626L, 100000L, autogenerated: false),
			new Class541("x14", Enum113.const_0, -27273042329602L, -27273042329627L, 100000L, autogenerated: false),
			new Class541("x15", Enum113.const_0, -27273042329602L, -27273042329628L, 100000L, autogenerated: false),
			new Class541("x16", Enum113.const_0, -27273042329602L, -27273042329629L, 100000L, autogenerated: false),
			new Class541("x17", Enum113.const_0, -27273042329602L, -27273042329630L, 100000L, autogenerated: false),
			new Class541("x18", Enum113.const_0, -27273042329602L, -27273042329631L, 100000L, autogenerated: false),
			new Class541("x19", Enum113.const_0, -27273042329602L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("wR", Enum113.const_0, -27273042329602L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("hR", Enum113.const_0, -27273042329603L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("y8", Enum113.const_0, -27273042329603L, -27273042329621L, 100000L, autogenerated: false),
			new Class541("y9", Enum113.const_0, -27273042329603L, -27273042329622L, 100000L, autogenerated: false),
			new Class541("y10", Enum113.const_0, -27273042329603L, -27273042329623L, 100000L, autogenerated: false),
			new Class541("y12", Enum113.const_0, -27273042329603L, -27273042329625L, 100000L, autogenerated: false),
			new Class541("y13", Enum113.const_0, -27273042329603L, -27273042329626L, 100000L, autogenerated: false),
			new Class541("y14", Enum113.const_0, -27273042329603L, -27273042329627L, 100000L, autogenerated: false),
			new Class541("y15", Enum113.const_0, -27273042329603L, -27273042329628L, 100000L, autogenerated: false),
			new Class541("y16", Enum113.const_0, -27273042329603L, -27273042329629L, 100000L, autogenerated: false),
			new Class541("y17", Enum113.const_0, -27273042329603L, -27273042329630L, 100000L, autogenerated: false),
			new Class541("y18", Enum113.const_0, -27273042329603L, -27273042329631L, 100000L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329659L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329660L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329661L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, 12500L, 46875L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329646L, -27273042329607L)
		}, new Class516[1]
		{
			new Class516(new Enum115[35]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[54]
			{
				-27273042329610L, -27273042329607L, -27273042329642L, -27273042329658L, -27273042329642L, -27273042329654L, -27273042329632L, -27273042329633L, -27273042329643L, -27273042329653L,
				-27273042329644L, -27273042329652L, -27273042329606L, -27273042329609L, -27273042329645L, -27273042329651L, -27273042329641L, -27273042329651L, -27273042329634L, -27273042329633L,
				-27273042329640L, -27273042329652L, -27273042329639L, -27273042329653L, -27273042329608L, -27273042329607L, -27273042329638L, -27273042329654L, -27273042329638L, -27273042329658L,
				-27273042329634L, -27273042329635L, -27273042329639L, -27273042329657L, -27273042329640L, -27273042329656L, -27273042329606L, -27273042329611L, -27273042329641L, -27273042329655L,
				-27273042329645L, -27273042329655L, -27273042329632L, -27273042329635L, -27273042329644L, -27273042329656L, -27273042329643L, -27273042329657L, -27273042329646L, -27273042329607L,
				-27273042329647L, -27273042329648L, -27273042329660L, 21600000L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329637L, -27273042329650L), new Class887(-27273042329636L, -27273042329649L));
	}
}
