using ns16;
using ns24;

namespace ns32;

internal class Class694
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 16667L),
			new Class341("adj2", 0L)
		}, new Class541[16]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, 50000L, autogenerated: false),
			new Class541("tx1", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("tx2", Enum113.const_1, -27273042329610L, 0L, -27273042329614L, autogenerated: false),
			new Class541("bx1", Enum113.const_0, -27273042329604L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("bx2", Enum113.const_1, -27273042329610L, 0L, -27273042329616L, autogenerated: false),
			new Class541("by1", Enum113.const_1, -27273042329611L, 0L, -27273042329616L, autogenerated: false),
			new Class541("d", Enum113.const_1, -27273042329614L, 0L, -27273042329616L, autogenerated: false),
			new Class541("tdx", Enum113.const_0, -27273042329614L, 29289L, 100000L, autogenerated: false),
			new Class541("bdx", Enum113.const_0, -27273042329616L, 29289L, 100000L, autogenerated: false),
			new Class541("il", Enum113.const_3, -27273042329619L, -27273042329620L, -27273042329621L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329610L, 0L, -27273042329622L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329611L, 0L, -27273042329621L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329625L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329626L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329627L)
		}, new Class886[2]
		{
			new Class886(polar: false, 27273042316901L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329615L, -27273042329609L),
			new Class886(polar: false, 27273042316902L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329616L, -27273042329611L)
		}, new Class516[1]
		{
			new Class516(new Enum115[10]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[26]
			{
				-27273042329614L, -27273042329609L, -27273042329615L, -27273042329609L, -27273042329614L, -27273042329614L, -27273042329627L, -27273042329625L, -27273042329610L, -27273042329618L,
				-27273042329616L, -27273042329616L, 0L, -27273042329625L, -27273042329616L, -27273042329611L, -27273042329616L, -27273042329616L, -27273042329625L, -27273042329625L,
				-27273042329608L, -27273042329614L, -27273042329614L, -27273042329614L, -27273042329626L, -27273042329625L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329622L, -27273042329620L), new Class887(-27273042329623L, -27273042329624L));
	}
}
