using ns16;
using ns24;

namespace ns32;

internal class Class697
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 4653L)
		}, new Class541[25]
		{
			new Class541("a", Enum113.const_11, -4653L, 27273042316901L, 4653L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329602L, 4969L, 21699L, autogenerated: false),
			new Class541("x2", Enum113.const_0, -27273042329602L, 6215L, 21600L, autogenerated: false),
			new Class541("x3", Enum113.const_0, -27273042329602L, 13135L, 21600L, autogenerated: false),
			new Class541("x4", Enum113.const_0, -27273042329602L, 16640L, 21600L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329603L, 7570L, 21600L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, 16515L, 21600L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329618L, 0L, -27273042329619L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329618L, -27273042329619L, 0L, autogenerated: false),
			new Class541("dy3", Enum113.const_0, -27273042329603L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("y5", Enum113.const_1, -27273042329621L, -27273042329622L, 0L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329632L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329633L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329624L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329624L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329625L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329625L, 0L, autogenerated: false),
			new Class541("wR", Enum113.const_0, -27273042329602L, 1125L, 21600L, autogenerated: false),
			new Class541("hR", Enum113.const_0, -27273042329603L, 1125L, 21600L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[8]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329634L),
			new Class888(-27273042329626L, -27273042329628L, -27273042329634L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329635L),
			new Class888(-27273042329626L, -27273042329629L, -27273042329636L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329636L),
			new Class888(-27273042329627L, -27273042329629L, -27273042329636L),
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329627L, -27273042329628L, -27273042329634L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, -4653L, 4653L, -27273042329606L, -27273042329621L)
		}, new Class516[4]
		{
			new Class516(new Enum115[3]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[6] { -27273042329608L, -27273042329607L, -27273042329632L, -27273042329633L, -27273042329635L, 21600000L }, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3
			}, new long[12]
			{
				-27273042329614L, -27273042329617L, -27273042329630L, -27273042329631L, -27273042329635L, 21600000L, -27273042329615L, -27273042329617L, -27273042329630L, -27273042329631L,
				-27273042329635L, 21600000L
			}, 0L, 0L, Enum271.const_5, stroke: true, extrusionOk: false),
			new Class516(new Enum115[2]
			{
				Enum115.const_1,
				Enum115.const_4
			}, new long[6] { -27273042329613L, -27273042329620L, -27273042329606L, -27273042329623L, -27273042329616L, -27273042329620L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[3]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[6] { -27273042329608L, -27273042329607L, -27273042329632L, -27273042329633L, -27273042329635L, 21600000L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329626L, -27273042329628L), new Class887(-27273042329627L, -27273042329629L));
	}
}
