using ns16;
using ns24;

namespace ns32;

internal class Class583
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 2700000L),
			new Class341("adj2", 16200000L)
		}, new Class541[30]
		{
			new Class541("stAng", Enum113.const_11, 0L, 27273042316901L, 21599999L, autogenerated: false),
			new Class541("enAng", Enum113.const_11, 0L, 27273042316902L, 21599999L, autogenerated: false),
			new Class541("sw1", Enum113.const_1, -27273042329613L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw2", Enum113.const_1, -27273042329614L, 21600000L, 0L, autogenerated: false),
			new Class541("swAng", Enum113.const_3, -27273042329614L, -27273042329614L, -27273042329615L, autogenerated: false),
			new Class541("wt1", Enum113.const_13, -27273042329639L, -27273042329612L, 0L, autogenerated: false),
			new Class541("ht1", Enum113.const_7, -27273042329640L, -27273042329612L, 0L, autogenerated: false),
			new Class541("dx1", Enum113.const_6, -27273042329639L, -27273042329618L, -27273042329617L, autogenerated: false),
			new Class541("dy1", Enum113.const_12, -27273042329640L, -27273042329618L, -27273042329617L, autogenerated: false),
			new Class541("wt2", Enum113.const_13, -27273042329639L, -27273042329613L, 0L, autogenerated: false),
			new Class541("ht2", Enum113.const_7, -27273042329640L, -27273042329613L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_6, -27273042329639L, -27273042329622L, -27273042329621L, autogenerated: false),
			new Class541("dy2", Enum113.const_12, -27273042329640L, -27273042329622L, -27273042329621L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329619L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, -27273042329620L, 0L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, -27273042329623L, 0L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, -27273042329624L, 0L, autogenerated: false),
			new Class541("x3", Enum113.const_2, -27273042329625L, -27273042329627L, 2L, autogenerated: false),
			new Class541("y3", Enum113.const_2, -27273042329626L, -27273042329628L, 2L, autogenerated: false),
			new Class541("midAng0", Enum113.const_0, -27273042329616L, 1L, 2L, autogenerated: false),
			new Class541("midAng", Enum113.const_1, -27273042329612L, -27273042329631L, -27273042329641L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329639L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329640L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329633L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329633L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329634L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329634L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true)
		}, new Class888[3]
		{
			new Class888(-27273042329625L, -27273042329626L, -27273042329612L),
			new Class888(-27273042329627L, -27273042329628L, -27273042329613L),
			new Class888(-27273042329629L, -27273042329630L, -27273042329632L)
		}, new Class886[2]
		{
			new Class886(polar: true, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 21599999L, -27273042329625L, -27273042329626L),
			new Class886(polar: true, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, 0L, 21599999L, -27273042329627L, -27273042329628L)
		}, new Class516[1]
		{
			new Class516(new Enum115[3]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[6] { -27273042329625L, -27273042329626L, -27273042329639L, -27273042329640L, -27273042329612L, -27273042329616L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329635L, -27273042329637L), new Class887(-27273042329636L, -27273042329638L));
	}
}
