using ns16;
using ns24;

namespace ns32;

internal class Class650
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[14]
		{
			new Class541("x2", Enum113.const_0, -27273042329602L, 9722L, 21600L, autogenerated: false),
			new Class541("x5", Enum113.const_0, -27273042329602L, 5372L, 21600L, autogenerated: false),
			new Class541("x16", Enum113.const_0, -27273042329602L, 11612L, 21600L, autogenerated: false),
			new Class541("x19", Enum113.const_0, -27273042329602L, 14640L, 21600L, autogenerated: false),
			new Class541("y2", Enum113.const_0, -27273042329603L, 1887L, 21600L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, 6382L, 21600L, autogenerated: false),
			new Class541("y8", Enum113.const_0, -27273042329603L, 12877L, 21600L, autogenerated: false),
			new Class541("y14", Enum113.const_0, -27273042329603L, 19712L, 21600L, autogenerated: false),
			new Class541("y16", Enum113.const_0, -27273042329603L, 18842L, 21600L, autogenerated: false),
			new Class541("y17", Enum113.const_0, -27273042329603L, 15935L, 21600L, autogenerated: false),
			new Class541("y24", Enum113.const_0, -27273042329603L, 6645L, 21600L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329612L, -27273042329616L, -27273042329623L),
			new Class888(-27273042329608L, -27273042329618L, -27273042329624L),
			new Class888(-27273042329614L, -27273042329620L, -27273042329625L),
			new Class888(-27273042329610L, -27273042329622L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[29]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[56]
			{
				11462L, 4342L, 14790L, 0L, 14525L, 5777L, 18007L, 3172L, 16380L, 6532L,
				21600L, 6645L, 16985L, 9402L, 18270L, 11290L, 16380L, 12310L, 18877L, 15632L,
				14640L, 14350L, 14942L, 17370L, 12180L, 15935L, 11612L, 18842L, 9872L, 17370L,
				8700L, 19712L, 7527L, 18125L, 4917L, 21600L, 4805L, 18240L, 1285L, 17825L,
				3330L, 15370L, 0L, 12877L, 3935L, 11592L, 1172L, 8270L, 5372L, 7817L,
				4502L, 3625L, 8550L, 6382L, 9722L, 1887L
			}, 21600L, 21600L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329613L, -27273042329617L), new Class887(-27273042329615L, -27273042329621L));
	}
}
