using ns16;
using ns24;

namespace ns32;

internal class Class659
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[3]
		{
			new Class341("adj1", 50000L),
			new Class341("adj2", 50000L),
			new Class341("adj3", 16667L)
		}, new Class541[28]
		{
			new Class541("a3", Enum113.const_11, 0L, 27273042316903L, 33333L, autogenerated: false),
			new Class541("maxAdj1", Enum113.const_1, 100000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, -27273042329613L, autogenerated: false),
			new Class541("w1", Enum113.const_1, -27273042329635L, 0L, -27273042329636L, autogenerated: false),
			new Class541("maxAdj2", Enum113.const_0, 100000L, -27273042329615L, -27273042329604L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, -27273042329616L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329604L, -27273042329617L, 100000L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329610L, 0L, -27273042329618L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329603L, -27273042329614L, 200000L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329603L, -27273042329612L, -200000L, autogenerated: false),
			new Class541("ly1", Enum113.const_1, -27273042329607L, -27273042329621L, -27273042329620L, autogenerated: false),
			new Class541("ry4", Enum113.const_1, -27273042329607L, -27273042329620L, -27273042329621L, autogenerated: false),
			new Class541("ly2", Enum113.const_1, -27273042329622L, -27273042329620L, 0L, autogenerated: false),
			new Class541("ry3", Enum113.const_1, -27273042329611L, 0L, -27273042329624L, autogenerated: false),
			new Class541("ly4", Enum113.const_0, -27273042329624L, 2L, 1L, autogenerated: false),
			new Class541("ry1", Enum113.const_1, -27273042329611L, 0L, -27273042329626L, autogenerated: false),
			new Class541("ly3", Enum113.const_1, -27273042329626L, 0L, -27273042329622L, autogenerated: false),
			new Class541("ry2", Enum113.const_1, -27273042329611L, 0L, -27273042329628L, autogenerated: false),
			new Class541("hR", Enum113.const_0, -27273042329612L, -27273042329604L, 400000L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329636L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, -27273042329636L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329622L, -27273042329630L, 0L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329629L, 0L, -27273042329630L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("wd32", Enum113.const_0, -27273042329602L, 1L, 32L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[6]
		{
			new Class888(-27273042329610L, -27273042329625L, 0L),
			new Class888(-27273042329619L, -27273042329611L, -27273042329637L),
			new Class888(-27273042329618L, -27273042329626L, -27273042329637L),
			new Class888(-27273042329608L, -27273042329624L, -27273042329638L),
			new Class888(-27273042329618L, -27273042329609L, -27273042329639L),
			new Class888(-27273042329619L, -27273042329627L, -27273042329639L)
		}, new Class886[3]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, -27273042329613L, -27273042329619L, -27273042329629L),
			new Class886(polar: false, 27273042316902L, 0L, -27273042329616L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329618L, -27273042329609L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316903L, 0L, 33333L, -27273042329632L, -27273042329629L)
		}, new Class516[3]
		{
			new Class516(new Enum115[17]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[38]
			{
				-27273042329608L, -27273042329624L, -27273042329618L, -27273042329609L, -27273042329618L, -27273042329622L, -27273042329606L, -27273042329622L, -27273042329636L, -27273042329630L,
				-27273042329639L, -27273042329638L, -27273042329636L, -27273042329630L, -27273042329639L, -10800000L, -27273042329619L, -27273042329629L, -27273042329619L, -27273042329627L,
				-27273042329610L, -27273042329625L, -27273042329619L, -27273042329611L, -27273042329619L, -27273042329623L, -27273042329606L, -27273042329623L, -27273042329636L, -27273042329630L,
				-27273042329637L, -27273042329637L, -27273042329631L, -27273042329628L, -27273042329618L, -27273042329628L, -27273042329618L, -27273042329626L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_0
			}, new long[12]
			{
				-27273042329632L, -27273042329633L, -27273042329636L, -27273042329630L, 0L, -27273042329637L, -27273042329636L, -27273042329630L, -27273042329639L, -10800000L,
				-27273042329632L, -27273042329629L
			}, 0L, 0L, Enum271.const_5, stroke: false, extrusionOk: false),
			new Class516(new Enum115[21]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2
			}, new long[46]
			{
				-27273042329608L, -27273042329624L, -27273042329618L, -27273042329609L, -27273042329618L, -27273042329622L, -27273042329606L, -27273042329622L, -27273042329636L, -27273042329630L,
				-27273042329639L, -27273042329638L, -27273042329636L, -27273042329630L, -27273042329639L, -10800000L, -27273042329619L, -27273042329629L, -27273042329619L, -27273042329627L,
				-27273042329610L, -27273042329625L, -27273042329619L, -27273042329611L, -27273042329619L, -27273042329623L, -27273042329606L, -27273042329623L, -27273042329636L, -27273042329630L,
				-27273042329637L, -27273042329637L, -27273042329631L, -27273042329628L, -27273042329618L, -27273042329628L, -27273042329618L, -27273042329626L, -27273042329632L, -27273042329633L,
				-27273042329632L, -27273042329629L, -27273042329631L, -27273042329634L, -27273042329631L, -27273042329628L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329618L, -27273042329622L), new Class887(-27273042329619L, -27273042329623L));
	}
}
