using ns16;
using ns24;

namespace ns32;

internal class Class668
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj1", 23520L)
		}, new Class541[34]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 51965L, autogenerated: false),
			new Class541("th", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("a", Enum113.const_5, -27273042329602L, -27273042329603L, 0L, autogenerated: false),
			new Class541("sa", Enum113.const_13, 1L, -27273042329614L, 0L, autogenerated: false),
			new Class541("ca", Enum113.const_7, 1L, -27273042329614L, 0L, autogenerated: false),
			new Class541("ta", Enum113.const_15, 1L, -27273042329614L, 0L, autogenerated: false),
			new Class541("dl", Enum113.const_10, -27273042329602L, -27273042329603L, 0L, autogenerated: false),
			new Class541("rw", Enum113.const_0, -27273042329618L, 51965L, 100000L, autogenerated: false),
			new Class541("lM", Enum113.const_1, -27273042329618L, 0L, -27273042329619L, autogenerated: false),
			new Class541("xM", Enum113.const_0, -27273042329616L, -27273042329620L, 2L, autogenerated: false),
			new Class541("yM", Enum113.const_0, -27273042329615L, -27273042329620L, 2L, autogenerated: false),
			new Class541("dxAM", Enum113.const_0, -27273042329615L, -27273042329613L, 2L, autogenerated: false),
			new Class541("dyAM", Enum113.const_0, -27273042329616L, -27273042329613L, 2L, autogenerated: false),
			new Class541("xA", Enum113.const_1, -27273042329621L, 0L, -27273042329623L, autogenerated: false),
			new Class541("yA", Enum113.const_1, -27273042329622L, -27273042329624L, 0L, autogenerated: false),
			new Class541("xB", Enum113.const_1, -27273042329621L, -27273042329623L, 0L, autogenerated: false),
			new Class541("yB", Enum113.const_1, -27273042329622L, 0L, -27273042329624L, autogenerated: false),
			new Class541("xBC", Enum113.const_1, -27273042329606L, 0L, -27273042329627L, autogenerated: false),
			new Class541("yBC", Enum113.const_0, -27273042329629L, -27273042329617L, 1L, autogenerated: false),
			new Class541("yC", Enum113.const_1, -27273042329630L, -27273042329628L, 0L, autogenerated: false),
			new Class541("xD", Enum113.const_1, -27273042329610L, 0L, -27273042329627L, autogenerated: false),
			new Class541("xE", Enum113.const_1, -27273042329610L, 0L, -27273042329625L, autogenerated: false),
			new Class541("yFE", Enum113.const_1, -27273042329607L, 0L, -27273042329626L, autogenerated: false),
			new Class541("xFE", Enum113.const_0, -27273042329634L, 1L, -27273042329617L, autogenerated: false),
			new Class541("xF", Enum113.const_1, -27273042329633L, 0L, -27273042329635L, autogenerated: false),
			new Class541("xL", Enum113.const_1, -27273042329625L, -27273042329635L, 0L, autogenerated: false),
			new Class541("yG", Enum113.const_1, -27273042329611L, 0L, -27273042329626L, autogenerated: false),
			new Class541("yH", Enum113.const_1, -27273042329611L, 0L, -27273042329628L, autogenerated: false),
			new Class541("yI", Enum113.const_1, -27273042329611L, 0L, -27273042329631L, autogenerated: false),
			new Class541("xC2", Enum113.const_1, -27273042329610L, 0L, -27273042329621L, autogenerated: false),
			new Class541("yC3", Enum113.const_1, -27273042329611L, 0L, -27273042329622L, autogenerated: false),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329621L, -27273042329622L, -27273042329643L),
			new Class888(-27273042329641L, -27273042329622L, -27273042329644L),
			new Class888(-27273042329641L, -27273042329642L, 0L),
			new Class888(-27273042329621L, -27273042329642L, -27273042329645L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 51965L, -27273042329608L, -27273042329613L)
		}, new Class516[1]
		{
			new Class516(new Enum115[13]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[24]
			{
				-27273042329625L, -27273042329626L, -27273042329627L, -27273042329628L, -27273042329606L, -27273042329631L, -27273042329632L, -27273042329628L, -27273042329633L, -27273042329626L,
				-27273042329636L, -27273042329607L, -27273042329633L, -27273042329638L, -27273042329632L, -27273042329639L, -27273042329606L, -27273042329640L, -27273042329627L, -27273042329639L,
				-27273042329625L, -27273042329638L, -27273042329637L, -27273042329607L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329625L, -27273042329628L), new Class887(-27273042329633L, -27273042329639L));
	}
}
