using ns16;
using ns24;

namespace ns32;

internal class Class569
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[3]
		{
			new Class341("adj1", 10800000L),
			new Class341("adj2", 0L),
			new Class341("adj3", 25000L)
		}, new Class541[76]
		{
			new Class541("stAng", Enum113.const_11, 0L, 27273042316901L, 21599999L, autogenerated: false),
			new Class541("istAng", Enum113.const_11, 0L, 27273042316902L, 21599999L, autogenerated: false),
			new Class541("a3", Enum113.const_11, 0L, 27273042316903L, 50000L, autogenerated: false),
			new Class541("sw11", Enum113.const_1, -27273042329613L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw12", Enum113.const_1, -27273042329615L, 21600000L, 0L, autogenerated: false),
			new Class541("swAng", Enum113.const_3, -27273042329615L, -27273042329615L, -27273042329616L, autogenerated: false),
			new Class541("iswAng", Enum113.const_1, 0L, 0L, -27273042329617L, autogenerated: false),
			new Class541("wt1", Enum113.const_13, -27273042329683L, -27273042329612L, 0L, autogenerated: false),
			new Class541("ht1", Enum113.const_7, -27273042329684L, -27273042329612L, 0L, autogenerated: false),
			new Class541("wt3", Enum113.const_13, -27273042329683L, -27273042329613L, 0L, autogenerated: false),
			new Class541("ht3", Enum113.const_7, -27273042329684L, -27273042329613L, 0L, autogenerated: false),
			new Class541("dx1", Enum113.const_6, -27273042329683L, -27273042329620L, -27273042329619L, autogenerated: false),
			new Class541("dy1", Enum113.const_12, -27273042329684L, -27273042329620L, -27273042329619L, autogenerated: false),
			new Class541("dx3", Enum113.const_6, -27273042329683L, -27273042329622L, -27273042329621L, autogenerated: false),
			new Class541("dy3", Enum113.const_12, -27273042329684L, -27273042329622L, -27273042329621L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329623L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, -27273042329624L, 0L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, -27273042329625L, 0L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329607L, -27273042329626L, 0L, autogenerated: false),
			new Class541("dr", Enum113.const_0, -27273042329604L, -27273042329614L, 100000L, autogenerated: false),
			new Class541("iwd2", Enum113.const_1, -27273042329683L, 0L, -27273042329631L, autogenerated: false),
			new Class541("ihd2", Enum113.const_1, -27273042329684L, 0L, -27273042329631L, autogenerated: false),
			new Class541("wt2", Enum113.const_13, -27273042329632L, -27273042329613L, 0L, autogenerated: false),
			new Class541("ht2", Enum113.const_7, -27273042329633L, -27273042329613L, 0L, autogenerated: false),
			new Class541("wt4", Enum113.const_13, -27273042329632L, -27273042329612L, 0L, autogenerated: false),
			new Class541("ht4", Enum113.const_7, -27273042329633L, -27273042329612L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_6, -27273042329632L, -27273042329635L, -27273042329634L, autogenerated: false),
			new Class541("dy2", Enum113.const_12, -27273042329633L, -27273042329635L, -27273042329634L, autogenerated: false),
			new Class541("dx4", Enum113.const_6, -27273042329632L, -27273042329637L, -27273042329636L, autogenerated: false),
			new Class541("dy4", Enum113.const_12, -27273042329633L, -27273042329637L, -27273042329636L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, -27273042329638L, 0L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, -27273042329639L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329640L, 0L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329607L, -27273042329641L, 0L, autogenerated: false),
			new Class541("sw0", Enum113.const_1, 21600000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("da1", Enum113.const_1, -27273042329617L, 0L, -27273042329646L, autogenerated: false),
			new Class541("g1", Enum113.const_8, -27273042329627L, -27273042329642L, 0L, autogenerated: false),
			new Class541("g2", Enum113.const_8, -27273042329629L, -27273042329644L, 0L, autogenerated: false),
			new Class541("g3", Enum113.const_8, -27273042329648L, -27273042329649L, 0L, autogenerated: false),
			new Class541("ir", Enum113.const_3, -27273042329647L, -27273042329610L, -27273042329650L, autogenerated: false),
			new Class541("sw1", Enum113.const_1, -27273042329685L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw2", Enum113.const_1, 27000000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw3", Enum113.const_3, -27273042329652L, -27273042329652L, -27273042329653L, autogenerated: false),
			new Class541("da2", Enum113.const_1, -27273042329617L, 0L, -27273042329654L, autogenerated: false),
			new Class541("g5", Enum113.const_8, -27273042329628L, -27273042329643L, 0L, autogenerated: false),
			new Class541("g6", Enum113.const_8, -27273042329630L, -27273042329645L, 0L, autogenerated: false),
			new Class541("g7", Enum113.const_8, -27273042329656L, -27273042329657L, 0L, autogenerated: false),
			new Class541("ib", Enum113.const_3, -27273042329655L, -27273042329611L, -27273042329658L, autogenerated: false),
			new Class541("sw4", Enum113.const_1, -27273042329686L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw5", Enum113.const_1, 32400000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw6", Enum113.const_3, -27273042329660L, -27273042329660L, -27273042329661L, autogenerated: false),
			new Class541("da3", Enum113.const_1, -27273042329617L, 0L, -27273042329662L, autogenerated: false),
			new Class541("g9", Enum113.const_9, -27273042329627L, -27273042329642L, 0L, autogenerated: false),
			new Class541("g10", Enum113.const_9, -27273042329629L, -27273042329644L, 0L, autogenerated: false),
			new Class541("g11", Enum113.const_9, -27273042329664L, -27273042329665L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_3, -27273042329663L, -27273042329608L, -27273042329666L, autogenerated: false),
			new Class541("sw7", Enum113.const_1, -27273042329687L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw8", Enum113.const_1, 37800000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw9", Enum113.const_3, -27273042329668L, -27273042329668L, -27273042329669L, autogenerated: false),
			new Class541("da4", Enum113.const_1, -27273042329617L, 0L, -27273042329670L, autogenerated: false),
			new Class541("g13", Enum113.const_9, -27273042329628L, -27273042329643L, 0L, autogenerated: false),
			new Class541("g14", Enum113.const_9, -27273042329630L, -27273042329645L, 0L, autogenerated: false),
			new Class541("g15", Enum113.const_9, -27273042329672L, -27273042329673L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_3, -27273042329671L, -27273042329609L, -27273042329674L, autogenerated: false),
			new Class541("x5", Enum113.const_2, -27273042329627L, -27273042329644L, 2L, autogenerated: false),
			new Class541("y5", Enum113.const_2, -27273042329628L, -27273042329645L, 2L, autogenerated: false),
			new Class541("x6", Enum113.const_2, -27273042329629L, -27273042329642L, 2L, autogenerated: false),
			new Class541("y6", Enum113.const_2, -27273042329630L, -27273042329643L, 2L, autogenerated: false),
			new Class541("cang1", Enum113.const_1, -27273042329612L, 0L, -27273042329685L, autogenerated: false),
			new Class541("cang2", Enum113.const_1, -27273042329613L, -27273042329685L, 0L, autogenerated: false),
			new Class541("cang3", Enum113.const_2, -27273042329680L, -27273042329681L, 2L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[3]
		{
			new Class888(-27273042329676L, -27273042329677L, -27273042329680L),
			new Class888(-27273042329678L, -27273042329679L, -27273042329681L),
			new Class888(-27273042329606L, -27273042329607L, -27273042329682L)
		}, new Class886[2]
		{
			new Class886(polar: true, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 21599999L, -27273042329627L, -27273042329628L),
			new Class886(polar: true, 27273042316903L, 0L, 50000L, 27273042316902L, 0L, 21599999L, -27273042329642L, -27273042329643L)
		}, new Class516[1]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[12]
			{
				-27273042329627L, -27273042329628L, -27273042329683L, -27273042329684L, -27273042329612L, -27273042329617L, -27273042329642L, -27273042329643L, -27273042329632L, -27273042329633L,
				-27273042329613L, -27273042329618L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329667L, -27273042329675L), new Class887(-27273042329651L, -27273042329659L));
	}
}
