using ns16;
using ns24;

namespace ns32;

internal class Class618
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[5]
		{
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("wd8", Enum113.const_0, -27273042329602L, 1L, 8L, autogenerated: true),
			new Class541("hd8", Enum113.const_0, -27273042329603L, 1L, 8L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329612L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329613L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329614L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, null, new Class516[3]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { 0L, 0L, 1L, 0L, 1L, 1L, 0L, 1L }, 1L, 1L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2
			}, new long[8] { 1L, 0L, 1L, 8L, 0L, 1L, 8L, 1L }, 8L, 8L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { 0L, 0L, 1L, 0L, 1L, 1L, 0L, 1L }, 1L, 1L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329615L, -27273042329616L), new Class887(-27273042329610L, -27273042329611L));
	}
}
