using ns16;
using ns24;

namespace ns32;

internal class Class645
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("hf", 102572L),
			new Class341("vf", 105210L)
		}, new Class541[24]
		{
			new Class541("swd2", Enum113.const_0, -27273042329631L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("shd2", Enum113.const_0, -27273042329632L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("svc", Enum113.const_0, -27273042329607L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("dx1", Enum113.const_0, -27273042329612L, 97493L, 100000L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329612L, 78183L, 100000L, autogenerated: false),
			new Class541("dx3", Enum113.const_0, -27273042329612L, 43388L, 100000L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329613L, 62349L, 100000L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329613L, 22252L, 100000L, autogenerated: false),
			new Class541("dy3", Enum113.const_0, -27273042329613L, 90097L, 100000L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329615L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329616L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, 0L, -27273042329617L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329617L, 0L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329606L, -27273042329616L, 0L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329606L, -27273042329615L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329614L, 0L, -27273042329618L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329614L, -27273042329619L, 0L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329614L, -27273042329620L, 0L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329611L, 0L, -27273042329627L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[7]
		{
			new Class888(-27273042329625L, -27273042329627L, 0L),
			new Class888(-27273042329626L, -27273042329628L, 0L),
			new Class888(-27273042329624L, -27273042329629L, -27273042329633L),
			new Class888(-27273042329623L, -27273042329629L, -27273042329633L),
			new Class888(-27273042329621L, -27273042329628L, -27273042329634L),
			new Class888(-27273042329622L, -27273042329627L, -27273042329634L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329635L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[14]
			{
				-27273042329621L, -27273042329628L, -27273042329622L, -27273042329627L, -27273042329606L, -27273042329609L, -27273042329625L, -27273042329627L, -27273042329626L, -27273042329628L,
				-27273042329624L, -27273042329629L, -27273042329623L, -27273042329629L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329622L, -27273042329627L), new Class887(-27273042329625L, -27273042329630L));
	}
}
