using ns16;
using ns24;

namespace ns32;

internal class Class608
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[3]
		{
			new Class341("adj1", 25000L),
			new Class341("adj2", 50000L),
			new Class341("adj3", 12500L)
		}, new Class541[47]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 25000L, 27273042316902L, 75000L, autogenerated: false),
			new Class541("q10", Enum113.const_1, 100000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("q11", Enum113.const_0, -27273042329614L, 1L, 2L, autogenerated: false),
			new Class541("q12", Enum113.const_1, -27273042329612L, 0L, -27273042329615L, autogenerated: false),
			new Class541("minAdj3", Enum113.const_8, 0L, -27273042329616L, 0L, autogenerated: false),
			new Class541("a3", Enum113.const_11, -27273042329617L, 27273042316903L, -27273042329612L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329602L, -27273042329613L, 200000L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329619L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329620L, -27273042329655L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329610L, 0L, -27273042329621L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329610L, 0L, -27273042329620L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329610L, 0L, -27273042329655L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329603L, -27273042329618L, 100000L, autogenerated: false),
			new Class541("f1", Enum113.const_0, 4L, -27273042329625L, -27273042329602L, autogenerated: false),
			new Class541("q1", Enum113.const_0, -27273042329621L, -27273042329621L, -27273042329602L, autogenerated: false),
			new Class541("q2", Enum113.const_1, -27273042329621L, 0L, -27273042329627L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329626L, -27273042329628L, 1L, autogenerated: false),
			new Class541("cx1", Enum113.const_0, -27273042329621L, 1L, 2L, autogenerated: false),
			new Class541("cy1", Enum113.const_0, -27273042329626L, -27273042329630L, 1L, autogenerated: false),
			new Class541("cx2", Enum113.const_1, -27273042329610L, 0L, -27273042329630L, autogenerated: false),
			new Class541("q1dup0", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dy3", Enum113.const_1, -27273042329633L, 0L, -27273042329625L, autogenerated: false),
			new Class541("q3", Enum113.const_0, -27273042329620L, -27273042329620L, -27273042329602L, autogenerated: false),
			new Class541("q4", Enum113.const_1, -27273042329620L, 0L, -27273042329635L, autogenerated: false),
			new Class541("q5", Enum113.const_0, -27273042329626L, -27273042329636L, 1L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329637L, -27273042329634L, 0L, autogenerated: false),
			new Class541("q6", Enum113.const_1, -27273042329625L, -27273042329634L, -27273042329638L, autogenerated: false),
			new Class541("q7", Enum113.const_1, -27273042329639L, -27273042329625L, 0L, autogenerated: false),
			new Class541("cy3", Enum113.const_1, -27273042329640L, -27273042329634L, 0L, autogenerated: false),
			new Class541("rh", Enum113.const_1, -27273042329611L, 0L, -27273042329633L, autogenerated: false),
			new Class541("q8", Enum113.const_0, -27273042329625L, 14L, 16L, autogenerated: false),
			new Class541("y2", Enum113.const_2, -27273042329643L, -27273042329642L, 2L, autogenerated: false),
			new Class541("y5", Enum113.const_1, -27273042329637L, -27273042329642L, 0L, autogenerated: false),
			new Class541("y6", Enum113.const_1, -27273042329638L, -27273042329642L, 0L, autogenerated: false),
			new Class541("cx4", Enum113.const_0, -27273042329620L, 1L, 2L, autogenerated: false),
			new Class541("q9", Enum113.const_0, -27273042329626L, -27273042329647L, 1L, autogenerated: false),
			new Class541("cy4", Enum113.const_1, -27273042329648L, -27273042329642L, 0L, autogenerated: false),
			new Class541("cx5", Enum113.const_1, -27273042329610L, 0L, -27273042329647L, autogenerated: false),
			new Class541("cy6", Enum113.const_1, -27273042329641L, -27273042329642L, 0L, autogenerated: false),
			new Class541("y7", Enum113.const_1, -27273042329629L, -27273042329634L, 0L, autogenerated: false),
			new Class541("cy7", Enum113.const_1, -27273042329633L, -27273042329633L, -27273042329652L, autogenerated: false),
			new Class541("y8", Enum113.const_1, -27273042329611L, 0L, -27273042329625L, autogenerated: false),
			new Class541("wd8", Enum113.const_0, -27273042329602L, 1L, 8L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329633L, -27273042329656L),
			new Class888(-27273042329655L, -27273042329644L, -27273042329657L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329658L),
			new Class888(-27273042329624L, -27273042329644L, 0L)
		}, new Class886[3]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 100000L, -27273042329606L, -27273042329633L),
			new Class886(polar: false, 27273042316902L, 25000L, 75000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329620L, -27273042329611L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316903L, -27273042329617L, -27273042329612L, -27273042329608L, -27273042329654L)
		}, new Class516[3]
		{
			new Class516(new Enum115[15]
			{
				Enum115.const_1,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_0
			}, new long[40]
			{
				-27273042329608L, -27273042329609L, -27273042329630L, -27273042329631L, -27273042329621L, -27273042329629L, -27273042329620L, -27273042329638L, -27273042329606L, -27273042329641L,
				-27273042329623L, -27273042329638L, -27273042329622L, -27273042329629L, -27273042329632L, -27273042329631L, -27273042329610L, -27273042329609L, -27273042329624L, -27273042329644L,
				-27273042329610L, -27273042329642L, -27273042329650L, -27273042329649L, -27273042329623L, -27273042329645L, -27273042329623L, -27273042329646L, -27273042329606L, -27273042329651L,
				-27273042329620L, -27273042329646L, -27273042329620L, -27273042329645L, -27273042329647L, -27273042329649L, -27273042329608L, -27273042329642L, -27273042329655L, -27273042329644L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_0
			}, new long[18]
			{
				-27273042329621L, -27273042329652L, -27273042329621L, -27273042329629L, -27273042329620L, -27273042329638L, -27273042329606L, -27273042329641L, -27273042329623L, -27273042329638L,
				-27273042329622L, -27273042329629L, -27273042329622L, -27273042329652L, -27273042329606L, -27273042329653L, -27273042329621L, -27273042329652L
			}, 0L, 0L, Enum271.const_5, stroke: false, extrusionOk: false),
			new Class516(new Enum115[23]
			{
				Enum115.const_1,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_4,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2
			}, new long[56]
			{
				-27273042329608L, -27273042329609L, -27273042329630L, -27273042329631L, -27273042329621L, -27273042329629L, -27273042329620L, -27273042329638L, -27273042329606L, -27273042329641L,
				-27273042329623L, -27273042329638L, -27273042329622L, -27273042329629L, -27273042329632L, -27273042329631L, -27273042329610L, -27273042329609L, -27273042329624L, -27273042329644L,
				-27273042329610L, -27273042329642L, -27273042329650L, -27273042329649L, -27273042329623L, -27273042329645L, -27273042329623L, -27273042329646L, -27273042329606L, -27273042329651L,
				-27273042329620L, -27273042329646L, -27273042329620L, -27273042329645L, -27273042329647L, -27273042329649L, -27273042329608L, -27273042329642L, -27273042329655L, -27273042329644L,
				-27273042329620L, -27273042329645L, -27273042329620L, -27273042329638L, -27273042329623L, -27273042329638L, -27273042329623L, -27273042329645L, -27273042329621L, -27273042329629L,
				-27273042329621L, -27273042329652L, -27273042329622L, -27273042329652L, -27273042329622L, -27273042329629L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329620L, -27273042329633L), new Class887(-27273042329623L, -27273042329646L));
	}
}
