using ns16;
using ns24;

namespace ns32;

internal class Class554
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[8]
		{
			new Class541("dx2", Enum113.const_0, -27273042329604L, 3L, 8L, autogenerated: false),
			new Class541("g9", Enum113.const_1, -27273042329607L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g10", Enum113.const_1, -27273042329607L, -27273042329612L, 0L, autogenerated: false),
			new Class541("g11", Enum113.const_1, -27273042329606L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g12", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329617L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329618L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329619L)
		}, null, new Class516[4]
		{
			new Class516(new Enum115[9]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[14]
			{
				-27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L, -27273042329616L, -27273042329607L,
				-27273042329615L, -27273042329613L, -27273042329615L, -27273042329614L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[6] { -27273042329616L, -27273042329607L, -27273042329615L, -27273042329613L, -27273042329615L, -27273042329614L }, 0L, 0L, Enum271.const_4, stroke: false, extrusionOk: false),
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[6] { -27273042329616L, -27273042329607L, -27273042329615L, -27273042329614L, -27273042329615L, -27273042329613L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
