using ns16;
using ns24;

namespace ns32;

internal class Class717
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 100000L)
		}, new Class541[23]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 200000L, autogenerated: false),
			new Class541("r2", Enum113.const_14, 2L, 0L, 0L, autogenerated: false),
			new Class541("tw", Enum113.const_0, -27273042329630L, -27273042329613L, 1L, autogenerated: false),
			new Class541("th", Enum113.const_0, -27273042329631L, -27273042329613L, 1L, autogenerated: false),
			new Class541("sw", Enum113.const_0, -27273042329614L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("sh", Enum113.const_0, -27273042329615L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329616L, 2700000L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329617L, 2700000L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329618L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, 0L, -27273042329619L, autogenerated: false),
			new Class541("x2", Enum113.const_2, -27273042329606L, -27273042329620L, 2L, autogenerated: false),
			new Class541("y2", Enum113.const_2, -27273042329607L, -27273042329621L, 2L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329630L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329631L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329624L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329624L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329625L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329625L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[8]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329627L, -27273042329629L, -27273042329632L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329632L),
			new Class888(-27273042329626L, -27273042329629L, -27273042329632L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329633L),
			new Class888(-27273042329626L, -27273042329628L, -27273042329634L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329634L),
			new Class888(-27273042329620L, -27273042329621L, -27273042329634L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, 0L, 200000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329620L, -27273042329609L)
		}, new Class516[1]
		{
			new Class516(new Enum115[7]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_4,
				Enum115.const_4,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_0
			}, new long[22]
			{
				-27273042329608L, -27273042329607L, -27273042329630L, -27273042329631L, -27273042329633L, -27273042329632L, -27273042329622L, -27273042329609L, -27273042329620L, -27273042329621L,
				-27273042329610L, -27273042329623L, -27273042329610L, -27273042329607L, -27273042329630L, -27273042329631L, 0L, -27273042329632L, -27273042329630L, -27273042329631L,
				-27273042329632L, -27273042329632L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329626L, -27273042329628L), new Class887(-27273042329627L, -27273042329629L));
	}
}
