using ns16;
using ns24;

namespace ns32;

internal class Class704
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 37500L)
		}, new Class541[37]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329642L, 1800000L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329643L, 3600000L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329613L, autogenerated: false),
			new Class541("x3", Enum113.const_0, -27273042329602L, 3L, 4L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329613L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, 0L, -27273042329614L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, 3L, 4L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329607L, -27273042329614L, 0L, autogenerated: false),
			new Class541("iwd2", Enum113.const_0, -27273042329642L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("ihd2", Enum113.const_0, -27273042329643L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("sdx1", Enum113.const_7, -27273042329621L, 900000L, 0L, autogenerated: false),
			new Class541("sdx2", Enum113.const_7, -27273042329621L, 2700000L, 0L, autogenerated: false),
			new Class541("sdx3", Enum113.const_7, -27273042329621L, 4500000L, 0L, autogenerated: false),
			new Class541("sdy1", Enum113.const_13, -27273042329622L, 4500000L, 0L, autogenerated: false),
			new Class541("sdy2", Enum113.const_13, -27273042329622L, 2700000L, 0L, autogenerated: false),
			new Class541("sdy3", Enum113.const_13, -27273042329622L, 900000L, 0L, autogenerated: false),
			new Class541("sx1", Enum113.const_1, -27273042329606L, 0L, -27273042329623L, autogenerated: false),
			new Class541("sx2", Enum113.const_1, -27273042329606L, 0L, -27273042329624L, autogenerated: false),
			new Class541("sx3", Enum113.const_1, -27273042329606L, 0L, -27273042329625L, autogenerated: false),
			new Class541("sx4", Enum113.const_1, -27273042329606L, -27273042329625L, 0L, autogenerated: false),
			new Class541("sx5", Enum113.const_1, -27273042329606L, -27273042329624L, 0L, autogenerated: false),
			new Class541("sx6", Enum113.const_1, -27273042329606L, -27273042329623L, 0L, autogenerated: false),
			new Class541("sy1", Enum113.const_1, -27273042329607L, 0L, -27273042329626L, autogenerated: false),
			new Class541("sy2", Enum113.const_1, -27273042329607L, 0L, -27273042329627L, autogenerated: false),
			new Class541("sy3", Enum113.const_1, -27273042329607L, 0L, -27273042329628L, autogenerated: false),
			new Class541("sy4", Enum113.const_1, -27273042329607L, -27273042329628L, 0L, autogenerated: false),
			new Class541("sy5", Enum113.const_1, -27273042329607L, -27273042329627L, 0L, autogenerated: false),
			new Class541("sy6", Enum113.const_1, -27273042329607L, -27273042329626L, 0L, autogenerated: false),
			new Class541("yAdj", Enum113.const_1, -27273042329607L, 0L, -27273042329622L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("hd4", Enum113.const_0, -27273042329603L, 1L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("wd4", Enum113.const_0, -27273042329602L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[12]
		{
			new Class888(-27273042329617L, -27273042329644L, 0L),
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329617L, -27273042329619L, 0L),
			new Class888(-27273042329616L, -27273042329620L, -27273042329645L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329645L),
			new Class888(-27273042329646L, -27273042329620L, -27273042329645L),
			new Class888(-27273042329615L, -27273042329619L, -27273042329647L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329647L),
			new Class888(-27273042329615L, -27273042329644L, -27273042329647L),
			new Class888(-27273042329646L, -27273042329618L, -27273042329648L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329648L),
			new Class888(-27273042329616L, -27273042329618L, -27273042329648L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 50000L, -27273042329606L, -27273042329641L)
		}, new Class516[1]
		{
			new Class516(new Enum115[25]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[48]
			{
				-27273042329608L, -27273042329607L, -27273042329629L, -27273042329637L, -27273042329615L, -27273042329644L, -27273042329630L, -27273042329636L, -27273042329646L, -27273042329618L,
				-27273042329631L, -27273042329635L, -27273042329606L, -27273042329609L, -27273042329632L, -27273042329635L, -27273042329616L, -27273042329618L, -27273042329633L, -27273042329636L,
				-27273042329617L, -27273042329644L, -27273042329634L, -27273042329637L, -27273042329610L, -27273042329607L, -27273042329634L, -27273042329638L, -27273042329617L, -27273042329619L,
				-27273042329633L, -27273042329639L, -27273042329616L, -27273042329620L, -27273042329632L, -27273042329640L, -27273042329606L, -27273042329611L, -27273042329631L, -27273042329640L,
				-27273042329646L, -27273042329620L, -27273042329630L, -27273042329639L, -27273042329615L, -27273042329619L, -27273042329629L, -27273042329638L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329630L, -27273042329636L), new Class887(-27273042329633L, -27273042329639L));
	}
}
