using ns16;
using ns24;

namespace ns32;

internal class Class666
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 23520L),
			new Class341("adj2", 11760L)
		}, new Class541[18]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 36745L, autogenerated: false),
			new Class541("2a1", Enum113.const_0, -27273042329612L, 2L, 1L, autogenerated: false),
			new Class541("mAdj2", Enum113.const_1, 100000L, 0L, -27273042329613L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, -27273042329614L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329603L, -27273042329615L, 200000L, autogenerated: false),
			new Class541("dx1", Enum113.const_0, -27273042329602L, 73490L, 200000L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, 0L, -27273042329617L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329607L, -27273042329617L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329619L, 0L, -27273042329616L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329620L, -27273042329616L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329618L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, -27273042329618L, 0L, autogenerated: false),
			new Class541("yC1", Enum113.const_2, -27273042329621L, -27273042329619L, 2L, autogenerated: false),
			new Class541("yC2", Enum113.const_2, -27273042329620L, -27273042329622L, 2L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[6]
		{
			new Class888(-27273042329624L, -27273042329625L, 0L),
			new Class888(-27273042329624L, -27273042329626L, 0L),
			new Class888(-27273042329606L, -27273042329622L, -27273042329627L),
			new Class888(-27273042329623L, -27273042329625L, -27273042329628L),
			new Class888(-27273042329623L, -27273042329626L, -27273042329628L),
			new Class888(-27273042329606L, -27273042329621L, -27273042329629L)
		}, new Class886[2]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 36745L, -27273042329608L, -27273042329621L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, 0L, -27273042329614L, -27273042329610L, -27273042329619L)
		}, new Class516[1]
		{
			new Class516(new Enum115[10]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[16]
			{
				-27273042329623L, -27273042329621L, -27273042329624L, -27273042329621L, -27273042329624L, -27273042329619L, -27273042329623L, -27273042329619L, -27273042329623L, -27273042329620L,
				-27273042329624L, -27273042329620L, -27273042329624L, -27273042329622L, -27273042329623L, -27273042329622L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329623L, -27273042329621L), new Class887(-27273042329624L, -27273042329622L));
	}
}
