using ns16;
using ns24;

namespace ns32;

internal class Class615
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[5]
		{
			new Class541("y1", Enum113.const_0, -27273042329603L, 17322L, 21600L, autogenerated: false),
			new Class541("y2", Enum113.const_0, -27273042329603L, 20172L, 21600L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329614L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329615L),
			new Class888(-27273042329606L, -27273042329613L, -27273042329616L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_0
			}, new long[12]
			{
				0L, 0L, 21600L, 0L, 21600L, 17322L, 10800L, 17322L, 10800L, 23922L,
				0L, 20172L
			}, 21600L, 21600L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329612L));
	}
}
