using ns16;
using ns24;

namespace ns32;

internal class Class568
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 12500L)
		}, new Class541[7]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329610L, 0L, -27273042329613L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329611L, 0L, -27273042329613L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[8]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329614L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329616L),
			new Class888(-27273042329606L, -27273042329615L, -27273042329616L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329617L),
			new Class888(-27273042329613L, -27273042329607L, -27273042329617L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329618L),
			new Class888(-27273042329606L, -27273042329613L, -27273042329618L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329613L, -27273042329609L)
		}, new Class516[6]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329613L, -27273042329613L, -27273042329614L, -27273042329613L, -27273042329614L, -27273042329615L, -27273042329613L, -27273042329615L }, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329614L, -27273042329613L, -27273042329613L, -27273042329613L }, 0L, 0L, Enum271.const_3, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329611L, -27273042329613L, -27273042329615L, -27273042329614L, -27273042329615L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_5, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329613L, -27273042329613L, -27273042329613L, -27273042329615L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_2, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329614L, -27273042329615L, -27273042329614L, -27273042329613L }, 0L, 0L, Enum271.const_4, stroke: false, extrusionOk: false),
			new Class516(new Enum115[18]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2
			}, new long[32]
			{
				-27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L, -27273042329613L, -27273042329613L,
				-27273042329614L, -27273042329613L, -27273042329614L, -27273042329615L, -27273042329613L, -27273042329615L, -27273042329608L, -27273042329609L, -27273042329613L, -27273042329613L,
				-27273042329608L, -27273042329611L, -27273042329613L, -27273042329615L, -27273042329610L, -27273042329609L, -27273042329614L, -27273042329613L, -27273042329610L, -27273042329611L,
				-27273042329614L, -27273042329615L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329613L, -27273042329613L), new Class887(-27273042329614L, -27273042329615L));
	}
}
