using ns16;
using ns24;

namespace ns32;

internal class Class592
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 50000L),
			new Class341("adj2", 50000L)
		}, new Class541[10]
		{
			new Class541("x2", Enum113.const_0, -27273042329602L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("x1", Enum113.const_2, -27273042329608L, -27273042329612L, 2L, autogenerated: false),
			new Class541("x3", Enum113.const_2, -27273042329610L, -27273042329612L, 2L, autogenerated: false),
			new Class541("x4", Enum113.const_2, -27273042329612L, -27273042329614L, 2L, autogenerated: false),
			new Class541("x5", Enum113.const_2, -27273042329614L, -27273042329610L, 2L, autogenerated: false),
			new Class541("y4", Enum113.const_0, -27273042329603L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("y1", Enum113.const_2, -27273042329609L, -27273042329617L, 2L, autogenerated: false),
			new Class541("y2", Enum113.const_2, -27273042329609L, -27273042329618L, 2L, autogenerated: false),
			new Class541("y3", Enum113.const_2, -27273042329618L, -27273042329617L, 2L, autogenerated: false),
			new Class541("y5", Enum113.const_2, -27273042329611L, -27273042329617L, 2L, autogenerated: false)
		}, null, new Class886[2]
		{
			new Class886(polar: false, 27273042316901L, -2147483647L, 2147483647L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329612L, -27273042329618L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, -2147483647L, 2147483647L, -27273042329614L, -27273042329617L)
		}, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_5,
				Enum115.const_5,
				Enum115.const_5
			}, new long[20]
			{
				-27273042329608L, -27273042329609L, -27273042329613L, -27273042329609L, -27273042329612L, -27273042329619L, -27273042329612L, -27273042329618L, -27273042329612L, -27273042329620L,
				-27273042329615L, -27273042329617L, -27273042329614L, -27273042329617L, -27273042329616L, -27273042329617L, -27273042329610L, -27273042329621L, -27273042329610L, -27273042329611L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
