using ns16;
using ns24;

namespace ns32;

internal class Class663
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[2]
		{
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[2]
		{
			new Class888(-27273042329608L, -27273042329609L, -27273042329612L),
			new Class888(-27273042329610L, -27273042329611L, -27273042329613L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[2]
			{
				Enum115.const_1,
				Enum115.const_2
			}, new long[4] { -27273042329608L, -27273042329609L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, null, null);
	}
}
