using ns16;
using ns24;

namespace ns32;

internal class Class678
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 0L),
			new Class341("adj2", 16200000L)
		}, new Class541[28]
		{
			new Class541("stAng", Enum113.const_11, 0L, 27273042316901L, 21599999L, autogenerated: false),
			new Class541("enAng", Enum113.const_11, 0L, 27273042316902L, 21599999L, autogenerated: false),
			new Class541("sw1", Enum113.const_1, -27273042329613L, 0L, -27273042329612L, autogenerated: false),
			new Class541("sw2", Enum113.const_1, -27273042329614L, 21600000L, 0L, autogenerated: false),
			new Class541("swAng", Enum113.const_3, -27273042329614L, -27273042329614L, -27273042329615L, autogenerated: false),
			new Class541("wt1", Enum113.const_13, -27273042329635L, -27273042329612L, 0L, autogenerated: false),
			new Class541("ht1", Enum113.const_7, -27273042329636L, -27273042329612L, 0L, autogenerated: false),
			new Class541("dx1", Enum113.const_6, -27273042329635L, -27273042329618L, -27273042329617L, autogenerated: false),
			new Class541("dy1", Enum113.const_12, -27273042329636L, -27273042329618L, -27273042329617L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329619L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, -27273042329620L, 0L, autogenerated: false),
			new Class541("wt2", Enum113.const_13, -27273042329635L, -27273042329613L, 0L, autogenerated: false),
			new Class541("ht2", Enum113.const_7, -27273042329636L, -27273042329613L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_6, -27273042329635L, -27273042329624L, -27273042329623L, autogenerated: false),
			new Class541("dy2", Enum113.const_12, -27273042329636L, -27273042329624L, -27273042329623L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, -27273042329625L, 0L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, -27273042329626L, 0L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329635L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329636L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329629L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329629L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329630L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329630L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329637L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329638L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329639L)
		}, new Class886[2]
		{
			new Class886(polar: true, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 21599999L, -27273042329621L, -27273042329622L),
			new Class886(polar: true, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, 0L, 21599999L, -27273042329627L, -27273042329628L)
		}, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329621L, -27273042329622L, -27273042329635L, -27273042329636L, -27273042329612L, -27273042329616L, -27273042329606L, -27273042329607L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329631L, -27273042329632L), new Class887(-27273042329633L, -27273042329634L));
	}
}
