using ns16;
using ns24;

namespace ns32;

internal class Class601
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[11]
		{
			new Class541("x1", Enum113.const_0, -27273042329602L, 2894L, 21600L, autogenerated: false),
			new Class541("x2", Enum113.const_0, -27273042329602L, 7906L, 21600L, autogenerated: false),
			new Class541("x3", Enum113.const_0, -27273042329602L, 13694L, 21600L, autogenerated: false),
			new Class541("x4", Enum113.const_0, -27273042329602L, 18706L, 21600L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329603L, 2894L, 21600L, autogenerated: false),
			new Class541("y2", Enum113.const_0, -27273042329603L, 7906L, 21600L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, 13694L, 21600L, autogenerated: false),
			new Class541("y4", Enum113.const_0, -27273042329603L, 18706L, 21600L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[12]
		{
			new Class888(-27273042329615L, -27273042329616L, 0L),
			new Class888(-27273042329610L, -27273042329617L, 0L),
			new Class888(-27273042329610L, -27273042329618L, 0L),
			new Class888(-27273042329615L, -27273042329619L, 0L),
			new Class888(-27273042329614L, -27273042329611L, -27273042329620L),
			new Class888(-27273042329613L, -27273042329611L, -27273042329620L),
			new Class888(-27273042329612L, -27273042329619L, -27273042329621L),
			new Class888(-27273042329608L, -27273042329618L, -27273042329621L),
			new Class888(-27273042329608L, -27273042329617L, -27273042329621L),
			new Class888(-27273042329612L, -27273042329616L, -27273042329621L),
			new Class888(-27273042329613L, -27273042329609L, -27273042329622L),
			new Class888(-27273042329614L, -27273042329609L, -27273042329622L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[13]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[24]
			{
				-27273042329608L, -27273042329617L, -27273042329612L, -27273042329616L, -27273042329613L, -27273042329609L, -27273042329614L, -27273042329609L, -27273042329615L, -27273042329616L,
				-27273042329610L, -27273042329617L, -27273042329610L, -27273042329618L, -27273042329615L, -27273042329619L, -27273042329614L, -27273042329611L, -27273042329613L, -27273042329611L,
				-27273042329612L, -27273042329619L, -27273042329608L, -27273042329618L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329612L, -27273042329616L), new Class887(-27273042329615L, -27273042329619L));
	}
}
