using ns16;
using ns24;

namespace ns32;

internal class Class683
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[4]
		{
			new Class341("adj1", 18515L),
			new Class341("adj2", 18515L),
			new Class341("adj3", 18515L),
			new Class341("adj4", 48123L)
		}, new Class541[30]
		{
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, 50000L, autogenerated: false),
			new Class541("maxAdj1", Enum113.const_0, -27273042329612L, 2L, 1L, autogenerated: false),
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, -27273042329613L, autogenerated: false),
			new Class541("maxAdj3", Enum113.const_1, 50000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("a3", Enum113.const_11, 0L, 27273042316903L, -27273042329615L, autogenerated: false),
			new Class541("q2", Enum113.const_0, -27273042329616L, 2L, 1L, autogenerated: false),
			new Class541("maxAdj4", Enum113.const_1, 100000L, 0L, -27273042329617L, autogenerated: false),
			new Class541("a4", Enum113.const_11, -27273042329614L, 27273042316904L, -27273042329618L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dx3", Enum113.const_0, -27273042329604L, -27273042329614L, 200000L, autogenerated: false),
			new Class541("ah", Enum113.const_0, -27273042329604L, -27273042329616L, 100000L, autogenerated: false),
			new Class541("dx1", Enum113.const_0, -27273042329602L, -27273042329619L, 200000L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329603L, -27273042329619L, 200000L, autogenerated: false),
			new Class541("x8", Enum113.const_1, -27273042329610L, 0L, -27273042329622L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329623L, autogenerated: false),
			new Class541("x7", Enum113.const_1, -27273042329606L, -27273042329623L, 0L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, 0L, -27273042329620L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329606L, -27273042329620L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, 0L, -27273042329621L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329606L, -27273042329621L, 0L, autogenerated: false),
			new Class541("y8", Enum113.const_1, -27273042329611L, 0L, -27273042329622L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, 0L, -27273042329624L, autogenerated: false),
			new Class541("y7", Enum113.const_1, -27273042329607L, -27273042329624L, 0L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329607L, 0L, -27273042329620L, autogenerated: false),
			new Class541("y6", Enum113.const_1, -27273042329607L, -27273042329620L, 0L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329607L, 0L, -27273042329621L, autogenerated: false),
			new Class541("y5", Enum113.const_1, -27273042329607L, -27273042329621L, 0L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329639L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329640L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329641L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, new Class886[4]
		{
			new Class886(polar: false, 27273042316901L, 0L, -27273042329613L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329630L, -27273042329622L),
			new Class886(polar: false, 27273042316902L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329628L, -27273042329609L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316903L, 0L, -27273042329615L, -27273042329610L, -27273042329622L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316904L, -27273042329614L, -27273042329618L, -27273042329608L, -27273042329633L)
		}, new Class516[1]
		{
			new Class516(new Enum115[33]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[64]
			{
				-27273042329608L, -27273042329607L, -27273042329622L, -27273042329635L, -27273042329622L, -27273042329637L, -27273042329626L, -27273042329637L, -27273042329626L, -27273042329633L,
				-27273042329630L, -27273042329633L, -27273042329630L, -27273042329622L, -27273042329628L, -27273042329622L, -27273042329606L, -27273042329609L, -27273042329629L, -27273042329622L,
				-27273042329631L, -27273042329622L, -27273042329631L, -27273042329633L, -27273042329627L, -27273042329633L, -27273042329627L, -27273042329637L, -27273042329625L, -27273042329637L,
				-27273042329625L, -27273042329635L, -27273042329610L, -27273042329607L, -27273042329625L, -27273042329636L, -27273042329625L, -27273042329638L, -27273042329627L, -27273042329638L,
				-27273042329627L, -27273042329634L, -27273042329631L, -27273042329634L, -27273042329631L, -27273042329632L, -27273042329629L, -27273042329632L, -27273042329606L, -27273042329611L,
				-27273042329628L, -27273042329632L, -27273042329630L, -27273042329632L, -27273042329630L, -27273042329634L, -27273042329626L, -27273042329634L, -27273042329626L, -27273042329638L,
				-27273042329622L, -27273042329638L, -27273042329622L, -27273042329636L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329626L, -27273042329633L), new Class887(-27273042329627L, -27273042329634L));
	}
}
