using ns16;
using ns24;

namespace ns32;

internal class Class556
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[29]
		{
			new Class541("dx2", Enum113.const_0, -27273042329604L, 3L, 8L, autogenerated: false),
			new Class541("g9", Enum113.const_1, -27273042329607L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g10", Enum113.const_1, -27273042329607L, -27273042329612L, 0L, autogenerated: false),
			new Class541("g11", Enum113.const_1, -27273042329606L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g12", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("g13", Enum113.const_0, -27273042329604L, 3L, 4L, autogenerated: false),
			new Class541("g14", Enum113.const_0, -27273042329617L, 1L, 16L, autogenerated: false),
			new Class541("g15", Enum113.const_0, -27273042329617L, 1L, 8L, autogenerated: false),
			new Class541("g16", Enum113.const_0, -27273042329617L, 3L, 16L, autogenerated: false),
			new Class541("g17", Enum113.const_0, -27273042329617L, 5L, 16L, autogenerated: false),
			new Class541("g18", Enum113.const_0, -27273042329617L, 7L, 16L, autogenerated: false),
			new Class541("g19", Enum113.const_0, -27273042329617L, 9L, 16L, autogenerated: false),
			new Class541("g20", Enum113.const_0, -27273042329617L, 11L, 16L, autogenerated: false),
			new Class541("g21", Enum113.const_0, -27273042329617L, 3L, 4L, autogenerated: false),
			new Class541("g22", Enum113.const_0, -27273042329617L, 13L, 16L, autogenerated: false),
			new Class541("g23", Enum113.const_0, -27273042329617L, 7L, 8L, autogenerated: false),
			new Class541("g24", Enum113.const_1, -27273042329613L, -27273042329618L, 0L, autogenerated: false),
			new Class541("g25", Enum113.const_1, -27273042329613L, -27273042329620L, 0L, autogenerated: false),
			new Class541("g26", Enum113.const_1, -27273042329613L, -27273042329621L, 0L, autogenerated: false),
			new Class541("g27", Enum113.const_1, -27273042329613L, -27273042329625L, 0L, autogenerated: false),
			new Class541("g28", Enum113.const_1, -27273042329615L, -27273042329619L, 0L, autogenerated: false),
			new Class541("g29", Enum113.const_1, -27273042329615L, -27273042329622L, 0L, autogenerated: false),
			new Class541("g30", Enum113.const_1, -27273042329615L, -27273042329623L, 0L, autogenerated: false),
			new Class541("g31", Enum113.const_1, -27273042329615L, -27273042329624L, 0L, autogenerated: false),
			new Class541("g32", Enum113.const_1, -27273042329615L, -27273042329626L, 0L, autogenerated: false),
			new Class541("g33", Enum113.const_1, -27273042329615L, -27273042329627L, 0L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329638L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329639L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329640L)
		}, null, new Class516[5]
		{
			new Class516(new Enum115[17]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[30]
			{
				-27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L, -27273042329606L, -27273042329613L,
				-27273042329615L, -27273042329607L, -27273042329632L, -27273042329607L, -27273042329632L, -27273042329614L, -27273042329637L, -27273042329614L, -27273042329637L, -27273042329607L,
				-27273042329616L, -27273042329607L, -27273042329636L, -27273042329630L, -27273042329636L, -27273042329628L, -27273042329635L, -27273042329628L, -27273042329635L, -27273042329629L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[14]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[24]
			{
				-27273042329636L, -27273042329630L, -27273042329636L, -27273042329628L, -27273042329635L, -27273042329628L, -27273042329635L, -27273042329629L, -27273042329632L, -27273042329607L,
				-27273042329632L, -27273042329614L, -27273042329633L, -27273042329614L, -27273042329633L, -27273042329631L, -27273042329634L, -27273042329631L, -27273042329634L, -27273042329614L,
				-27273042329637L, -27273042329614L, -27273042329637L, -27273042329607L
			}, 0L, 0L, Enum271.const_5, stroke: false, extrusionOk: false),
			new Class516(new Enum115[9]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[14]
			{
				-27273042329606L, -27273042329613L, -27273042329615L, -27273042329607L, -27273042329616L, -27273042329607L, -27273042329633L, -27273042329631L, -27273042329634L, -27273042329631L,
				-27273042329634L, -27273042329614L, -27273042329633L, -27273042329614L
			}, 0L, 0L, Enum271.const_4, stroke: false, extrusionOk: false),
			new Class516(new Enum115[20]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2
			}, new long[38]
			{
				-27273042329606L, -27273042329613L, -27273042329635L, -27273042329629L, -27273042329635L, -27273042329628L, -27273042329636L, -27273042329628L, -27273042329636L, -27273042329630L,
				-27273042329616L, -27273042329607L, -27273042329637L, -27273042329607L, -27273042329637L, -27273042329614L, -27273042329632L, -27273042329614L, -27273042329632L, -27273042329607L,
				-27273042329615L, -27273042329607L, -27273042329635L, -27273042329629L, -27273042329636L, -27273042329630L, -27273042329637L, -27273042329607L, -27273042329632L, -27273042329607L,
				-27273042329633L, -27273042329614L, -27273042329633L, -27273042329631L, -27273042329634L, -27273042329631L, -27273042329634L, -27273042329614L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
