using ns16;
using ns24;

namespace ns32;

internal class Class625
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[8]
		{
			new Class541("y2", Enum113.const_0, -27273042329603L, 3675L, 21600L, autogenerated: false),
			new Class541("y8", Enum113.const_0, -27273042329603L, 20782L, 21600L, autogenerated: false),
			new Class541("x3", Enum113.const_0, -27273042329602L, 9298L, 21600L, autogenerated: false),
			new Class541("x4", Enum113.const_0, -27273042329602L, 12286L, 21600L, autogenerated: false),
			new Class541("x5", Enum113.const_0, -27273042329602L, 18595L, 21600L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329615L, -27273042329609L, -27273042329617L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329618L),
			new Class888(-27273042329614L, -27273042329613L, -27273042329619L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, null, new Class516[3]
		{
			new Class516(new Enum115[19]
			{
				Enum115.const_1,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_0
			}, new long[44]
			{
				0L, 20782L, 9298L, 23542L, 9298L, 18022L, 18595L, 18022L, 18595L, 3675L,
				0L, 3675L, 1532L, 3675L, 1532L, 1815L, 20000L, 1815L, 20000L, 16252L,
				19298L, 16252L, 18595L, 16352L, 18595L, 16352L, 18595L, 3675L, 2972L, 1815L,
				2972L, 0L, 21600L, 0L, 21600L, 14392L, 20800L, 14392L, 20000L, 14467L,
				20000L, 14467L, 20000L, 1815L
			}, 21600L, 21600L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[15]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_5
			}, new long[40]
			{
				0L, 3675L, 18595L, 3675L, 18595L, 18022L, 9298L, 18022L, 9298L, 23542L,
				0L, 20782L, 1532L, 3675L, 1532L, 1815L, 20000L, 1815L, 20000L, 16252L,
				19298L, 16252L, 18595L, 16352L, 18595L, 16352L, 2972L, 1815L, 2972L, 0L,
				21600L, 0L, 21600L, 14392L, 20800L, 14392L, 20000L, 14467L, 20000L, 14467L
			}, 21600L, 21600L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[13]
			{
				Enum115.const_1,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[36]
			{
				0L, 20782L, 9298L, 23542L, 9298L, 18022L, 18595L, 18022L, 18595L, 16352L,
				18595L, 16352L, 19298L, 16252L, 20000L, 16252L, 20000L, 14467L, 20000L, 14467L,
				20800L, 14392L, 21600L, 14392L, 21600L, 0L, 2972L, 0L, 2972L, 1815L,
				1532L, 1815L, 1532L, 3675L, 0L, 3675L
			}, 21600L, 21600L, Enum271.const_0, stroke: false, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329612L), new Class887(-27273042329616L, -27273042329613L));
	}
}
