using ns16;
using ns24;

namespace ns32;

internal class Class649
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[11]
		{
			new Class541("x5", Enum113.const_0, -27273042329602L, 4627L, 21600L, autogenerated: false),
			new Class541("x12", Enum113.const_0, -27273042329602L, 8485L, 21600L, autogenerated: false),
			new Class541("x21", Enum113.const_0, -27273042329602L, 16702L, 21600L, autogenerated: false),
			new Class541("x24", Enum113.const_0, -27273042329602L, 14522L, 21600L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, 6320L, 21600L, autogenerated: false),
			new Class541("y6", Enum113.const_0, -27273042329603L, 8615L, 21600L, autogenerated: false),
			new Class541("y9", Enum113.const_0, -27273042329603L, 13937L, 21600L, autogenerated: false),
			new Class541("y18", Enum113.const_0, -27273042329603L, 13290L, 21600L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329615L, -27273042329609L, -27273042329620L),
			new Class888(-27273042329608L, -27273042329617L, -27273042329621L),
			new Class888(-27273042329613L, -27273042329611L, -27273042329622L),
			new Class888(-27273042329610L, -27273042329619L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[25]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[48]
			{
				10800L, 5800L, 14522L, 0L, 14155L, 5325L, 18380L, 4457L, 16702L, 7315L,
				21097L, 8137L, 17607L, 10475L, 21600L, 13290L, 16837L, 12942L, 18145L, 18095L,
				14020L, 14457L, 13247L, 19737L, 10532L, 14935L, 8485L, 21600L, 7715L, 15627L,
				4762L, 17617L, 5667L, 13937L, 135L, 14587L, 3722L, 11775L, 0L, 8615L,
				4627L, 7617L, 370L, 2295L, 7312L, 6320L, 8352L, 2295L
			}, 21600L, 21600L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329612L, -27273042329616L), new Class887(-27273042329614L, -27273042329618L));
	}
}
