using ns16;
using ns24;

namespace ns32;

internal class Class727
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", -20833L),
			new Class341("adj2", 62500L)
		}, new Class541[32]
		{
			new Class541("dxPos", Enum113.const_0, -27273042329602L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("dyPos", Enum113.const_0, -27273042329603L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("xPos", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("yPos", Enum113.const_1, -27273042329607L, -27273042329613L, 0L, autogenerated: false),
			new Class541("sdx", Enum113.const_0, -27273042329612L, -27273042329603L, 1L, autogenerated: false),
			new Class541("sdy", Enum113.const_0, -27273042329613L, -27273042329602L, 1L, autogenerated: false),
			new Class541("pang", Enum113.const_5, -27273042329616L, -27273042329617L, 0L, autogenerated: false),
			new Class541("stAng", Enum113.const_1, -27273042329618L, 660000L, 0L, autogenerated: false),
			new Class541("enAng", Enum113.const_1, -27273042329618L, 0L, 660000L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329640L, -27273042329619L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329641L, -27273042329619L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, -27273042329621L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, -27273042329622L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_7, -27273042329640L, -27273042329620L, 0L, autogenerated: false),
			new Class541("dy2", Enum113.const_13, -27273042329641L, -27273042329620L, 0L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, -27273042329625L, 0L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, -27273042329626L, 0L, autogenerated: false),
			new Class541("stAng1", Enum113.const_5, -27273042329621L, -27273042329622L, 0L, autogenerated: false),
			new Class541("enAng1", Enum113.const_5, -27273042329625L, -27273042329626L, 0L, autogenerated: false),
			new Class541("swAng1", Enum113.const_1, -27273042329630L, 0L, -27273042329629L, autogenerated: false),
			new Class541("swAng2", Enum113.const_1, -27273042329631L, 21600000L, 0L, autogenerated: false),
			new Class541("swAng", Enum113.const_3, -27273042329631L, -27273042329631L, -27273042329632L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329640L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329641L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329634L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329634L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329635L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329635L, 0L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[8]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329642L),
			new Class888(-27273042329636L, -27273042329638L, -27273042329642L),
			new Class888(-27273042329636L, -27273042329639L, -27273042329643L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329643L),
			new Class888(-27273042329637L, -27273042329639L, -27273042329643L),
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329637L, -27273042329638L, -27273042329642L),
			new Class888(-27273042329614L, -27273042329615L, -27273042329618L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, -2147483647L, 2147483647L, 27273042316902L, -2147483647L, 2147483647L, -27273042329614L, -27273042329615L)
		}, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[8] { -27273042329614L, -27273042329615L, -27273042329623L, -27273042329624L, -27273042329640L, -27273042329641L, -27273042329629L, -27273042329633L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329636L, -27273042329638L), new Class887(-27273042329637L, -27273042329639L));
	}
}
