using ns16;
using ns24;

namespace ns32;

internal class Class709
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[3]
		{
			new Class341("adj", 19098L),
			new Class341("hf", 105146L),
			new Class341("vf", 110557L)
		}, new Class541[33]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("swd2", Enum113.const_0, -27273042329640L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("shd2", Enum113.const_0, -27273042329641L, 27273042316903L, 100000L, autogenerated: false),
			new Class541("svc", Enum113.const_0, -27273042329607L, 27273042316903L, 100000L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329613L, 1080000L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_7, -27273042329613L, 18360000L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329614L, 1080000L, 0L, autogenerated: false),
			new Class541("dy2", Enum113.const_13, -27273042329614L, 18360000L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329616L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329617L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, -27273042329617L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329616L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329615L, 0L, -27273042329618L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329615L, 0L, -27273042329619L, autogenerated: false),
			new Class541("iwd2", Enum113.const_0, -27273042329613L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("ihd2", Enum113.const_0, -27273042329614L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("sdx1", Enum113.const_7, -27273042329626L, 20520000L, 0L, autogenerated: false),
			new Class541("sdx2", Enum113.const_7, -27273042329626L, 3240000L, 0L, autogenerated: false),
			new Class541("sdy1", Enum113.const_13, -27273042329627L, 3240000L, 0L, autogenerated: false),
			new Class541("sdy2", Enum113.const_13, -27273042329627L, 20520000L, 0L, autogenerated: false),
			new Class541("sx1", Enum113.const_1, -27273042329606L, 0L, -27273042329628L, autogenerated: false),
			new Class541("sx2", Enum113.const_1, -27273042329606L, 0L, -27273042329629L, autogenerated: false),
			new Class541("sx3", Enum113.const_1, -27273042329606L, -27273042329629L, 0L, autogenerated: false),
			new Class541("sx4", Enum113.const_1, -27273042329606L, -27273042329628L, 0L, autogenerated: false),
			new Class541("sy1", Enum113.const_1, -27273042329615L, 0L, -27273042329630L, autogenerated: false),
			new Class541("sy2", Enum113.const_1, -27273042329615L, 0L, -27273042329631L, autogenerated: false),
			new Class541("sy3", Enum113.const_1, -27273042329615L, -27273042329627L, 0L, autogenerated: false),
			new Class541("yAdj", Enum113.const_1, -27273042329615L, 0L, -27273042329627L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[5]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329642L),
			new Class888(-27273042329620L, -27273042329624L, -27273042329643L),
			new Class888(-27273042329621L, -27273042329625L, -27273042329644L),
			new Class888(-27273042329622L, -27273042329625L, -27273042329644L),
			new Class888(-27273042329623L, -27273042329624L, 0L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 50000L, -27273042329606L, -27273042329639L)
		}, new Class516[1]
		{
			new Class516(new Enum115[11]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[20]
			{
				-27273042329620L, -27273042329624L, -27273042329633L, -27273042329636L, -27273042329606L, -27273042329609L, -27273042329634L, -27273042329636L, -27273042329623L, -27273042329624L,
				-27273042329635L, -27273042329637L, -27273042329622L, -27273042329625L, -27273042329606L, -27273042329638L, -27273042329621L, -27273042329625L, -27273042329632L, -27273042329637L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329632L, -27273042329636L), new Class887(-27273042329635L, -27273042329638L));
	}
}
