using ns16;
using ns24;

namespace ns32;

internal class Class564
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj1", 50000L)
		}, new Class541[1]
		{
			new Class541("x1", Enum113.const_0, -27273042329602L, 27273042316901L, 100000L, autogenerated: false)
		}, null, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, -2147483647L, 2147483647L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329612L, -27273042329607L)
		}, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329612L, -27273042329609L, -27273042329612L, -27273042329611L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
