using ns16;
using ns24;

namespace ns32;

internal class Class677
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("hf", 105146L),
			new Class341("vf", 110557L)
		}, new Class541[19]
		{
			new Class541("swd2", Enum113.const_0, -27273042329626L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("shd2", Enum113.const_0, -27273042329627L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("svc", Enum113.const_0, -27273042329607L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329612L, 1080000L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_7, -27273042329612L, 18360000L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329613L, 1080000L, 0L, autogenerated: false),
			new Class541("dy2", Enum113.const_13, -27273042329613L, 18360000L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329615L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329616L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, -27273042329616L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329615L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329614L, 0L, -27273042329617L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329614L, 0L, -27273042329618L, autogenerated: false),
			new Class541("it", Enum113.const_0, -27273042329623L, -27273042329616L, -27273042329615L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[6]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329628L),
			new Class888(-27273042329619L, -27273042329623L, -27273042329629L),
			new Class888(-27273042329620L, -27273042329624L, -27273042329630L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329630L),
			new Class888(-27273042329621L, -27273042329624L, -27273042329630L),
			new Class888(-27273042329622L, -27273042329623L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[6]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[10] { -27273042329619L, -27273042329623L, -27273042329606L, -27273042329609L, -27273042329622L, -27273042329623L, -27273042329621L, -27273042329624L, -27273042329620L, -27273042329624L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329620L, -27273042329625L), new Class887(-27273042329621L, -27273042329624L));
	}
}
