using ns16;
using ns24;

namespace ns32;

internal class Class674
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 50000L),
			new Class341("adj2", 50000L)
		}, new Class541[14]
		{
			new Class541("maxAdj2", Enum113.const_0, 100000L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, -27273042329612L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329604L, -27273042329614L, 100000L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329610L, 0L, -27273042329615L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329603L, -27273042329613L, 200000L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, 0L, -27273042329617L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, -27273042329617L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329617L, -27273042329615L, -27273042329622L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329610L, 0L, -27273042329620L, autogenerated: false),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329616L, -27273042329609L, -27273042329623L),
			new Class888(-27273042329620L, -27273042329607L, -27273042329624L),
			new Class888(-27273042329616L, -27273042329611L, -27273042329625L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, new Class886[2]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 100000L, -27273042329610L, -27273042329618L),
			new Class886(polar: false, 27273042316902L, 0L, -27273042329612L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329616L, -27273042329609L)
		}, new Class516[1]
		{
			new Class516(new Enum115[9]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[16]
			{
				-27273042329608L, -27273042329618L, -27273042329616L, -27273042329618L, -27273042329616L, -27273042329609L, -27273042329610L, -27273042329607L, -27273042329616L, -27273042329611L,
				-27273042329616L, -27273042329619L, -27273042329608L, -27273042329619L, -27273042329620L, -27273042329607L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329620L, -27273042329618L), new Class887(-27273042329621L, -27273042329619L));
	}
}
