using ns16;
using ns24;

namespace ns32;

internal class Class701
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 16667L),
			new Class341("adj2", 16667L)
		}, new Class541[10]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, 50000L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329604L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329610L, 0L, -27273042329615L, autogenerated: false),
			new Class541("il", Enum113.const_0, -27273042329614L, 29289L, 100000L, autogenerated: false),
			new Class541("ir", Enum113.const_2, -27273042329616L, -27273042329610L, 2L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329619L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329620L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329621L)
		}, new Class886[2]
		{
			new Class886(polar: false, 27273042316901L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329614L, -27273042329609L),
			new Class886(polar: false, 27273042316902L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329616L, -27273042329609L)
		}, new Class516[1]
		{
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[16]
			{
				-27273042329614L, -27273042329609L, -27273042329616L, -27273042329609L, -27273042329610L, -27273042329615L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L,
				-27273042329608L, -27273042329614L, -27273042329614L, -27273042329614L, -27273042329620L, -27273042329619L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329617L, -27273042329617L), new Class887(-27273042329618L, -27273042329611L));
	}
}
