using ns16;
using ns24;

namespace ns32;

internal class Class690
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 8333L),
			new Class341("adj2", 50000L)
		}, new Class541[19]
		{
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("q1", Enum113.const_1, 100000L, 0L, -27273042329612L, autogenerated: false),
			new Class541("q2", Enum113.const_9, -27273042329613L, -27273042329612L, 0L, autogenerated: false),
			new Class541("q3", Enum113.const_0, -27273042329614L, 1L, 2L, autogenerated: false),
			new Class541("maxAdj1", Enum113.const_0, -27273042329615L, -27273042329603L, -27273042329604L, autogenerated: false),
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, -27273042329616L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329604L, -27273042329617L, 100000L, autogenerated: false),
			new Class541("y3", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329619L, 0L, -27273042329618L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329611L, 0L, -27273042329618L, autogenerated: false),
			new Class541("dx1", Enum113.const_7, -27273042329627L, 2700000L, 0L, autogenerated: false),
			new Class541("dy1", Enum113.const_13, -27273042329618L, 2700000L, 0L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329608L, -27273042329622L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329618L, 0L, -27273042329623L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329611L, -27273042329623L, -27273042329618L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[3]
		{
			new Class888(-27273042329608L, -27273042329609L, -27273042329628L),
			new Class888(-27273042329610L, -27273042329619L, -27273042329629L),
			new Class888(-27273042329608L, -27273042329611L, -27273042329630L)
		}, new Class886[2]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, -27273042329616L, -27273042329606L, -27273042329618L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, 0L, 100000L, -27273042329610L, -27273042329619L)
		}, new Class516[2]
		{
			new Class516(new Enum115[8]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_0
			}, new long[22]
			{
				-27273042329608L, -27273042329609L, -27273042329627L, -27273042329618L, -27273042329630L, -27273042329628L, -27273042329606L, -27273042329620L, -27273042329627L, -27273042329618L,
				-27273042329629L, -5400000L, -27273042329627L, -27273042329618L, -27273042329630L, -5400000L, -27273042329606L, -27273042329621L, -27273042329627L, -27273042329618L,
				0L, -27273042329628L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[7]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_3
			}, new long[22]
			{
				-27273042329608L, -27273042329609L, -27273042329627L, -27273042329618L, -27273042329630L, -27273042329628L, -27273042329606L, -27273042329620L, -27273042329627L, -27273042329618L,
				-27273042329629L, -5400000L, -27273042329627L, -27273042329618L, -27273042329630L, -5400000L, -27273042329606L, -27273042329621L, -27273042329627L, -27273042329618L,
				0L, -27273042329628L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329625L), new Class887(-27273042329624L, -27273042329626L));
	}
}
