using ns16;
using ns24;

namespace ns32;

internal class Class708
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 12500L)
		}, new Class541[15]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("iwd2", Enum113.const_0, -27273042329622L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("ihd2", Enum113.const_0, -27273042329623L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("sdx", Enum113.const_7, -27273042329613L, 2700000L, 0L, autogenerated: false),
			new Class541("sdy", Enum113.const_13, -27273042329614L, 2700000L, 0L, autogenerated: false),
			new Class541("sx1", Enum113.const_1, -27273042329606L, 0L, -27273042329615L, autogenerated: false),
			new Class541("sx2", Enum113.const_1, -27273042329606L, -27273042329615L, 0L, autogenerated: false),
			new Class541("sy1", Enum113.const_1, -27273042329607L, 0L, -27273042329616L, autogenerated: false),
			new Class541("sy2", Enum113.const_1, -27273042329607L, -27273042329616L, 0L, autogenerated: false),
			new Class541("yAdj", Enum113.const_1, -27273042329607L, 0L, -27273042329614L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329624L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329625L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329626L),
			new Class888(-27273042329610L, -27273042329607L, 0L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 50000L, -27273042329606L, -27273042329621L)
		}, new Class516[1]
		{
			new Class516(new Enum115[9]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[16]
			{
				-27273042329608L, -27273042329607L, -27273042329617L, -27273042329619L, -27273042329606L, -27273042329609L, -27273042329618L, -27273042329619L, -27273042329610L, -27273042329607L,
				-27273042329618L, -27273042329620L, -27273042329606L, -27273042329611L, -27273042329617L, -27273042329620L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329617L, -27273042329619L), new Class887(-27273042329618L, -27273042329620L));
	}
}
