using ns16;
using ns24;

namespace ns32;

internal class Class562
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[4]
		{
			new Class341("adj1", 25000L),
			new Class341("adj2", 25000L),
			new Class341("adj3", 25000L),
			new Class341("adj4", 43750L)
		}, new Class541[26]
		{
			new Class541("a2", Enum113.const_11, 0L, 27273042316902L, 50000L, autogenerated: false),
			new Class541("maxAdj1", Enum113.const_0, -27273042329612L, 2L, 1L, autogenerated: false),
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, -27273042329613L, autogenerated: false),
			new Class541("a3", Enum113.const_11, 0L, 27273042316903L, 50000L, autogenerated: false),
			new Class541("th", Enum113.const_0, -27273042329604L, -27273042329614L, 100000L, autogenerated: false),
			new Class541("aw2", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("th2", Enum113.const_0, -27273042329616L, 1L, 2L, autogenerated: false),
			new Class541("dh2", Enum113.const_1, -27273042329617L, 0L, -27273042329618L, autogenerated: false),
			new Class541("ah", Enum113.const_0, -27273042329604L, -27273042329615L, 100000L, autogenerated: false),
			new Class541("bw", Enum113.const_1, -27273042329610L, 0L, -27273042329620L, autogenerated: false),
			new Class541("bh", Enum113.const_1, -27273042329611L, 0L, -27273042329619L, autogenerated: false),
			new Class541("bs", Enum113.const_9, -27273042329621L, -27273042329622L, 0L, autogenerated: false),
			new Class541("maxAdj4", Enum113.const_0, 100000L, -27273042329623L, -27273042329604L, autogenerated: false),
			new Class541("a4", Enum113.const_11, 0L, 27273042316904L, -27273042329624L, autogenerated: false),
			new Class541("bd", Enum113.const_0, -27273042329604L, -27273042329625L, 100000L, autogenerated: false),
			new Class541("bd3", Enum113.const_1, -27273042329626L, 0L, -27273042329616L, autogenerated: false),
			new Class541("bd2", Enum113.const_8, -27273042329627L, 0L, 0L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329616L, -27273042329628L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329610L, 0L, -27273042329620L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329619L, -27273042329616L, 0L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329631L, -27273042329619L, 0L, autogenerated: false),
			new Class541("y5", Enum113.const_1, -27273042329619L, -27273042329626L, 0L, autogenerated: false),
			new Class541("y6", Enum113.const_1, -27273042329631L, -27273042329628L, 0L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329630L, -27273042329609L, -27273042329635L),
			new Class888(-27273042329630L, -27273042329632L, -27273042329636L),
			new Class888(-27273042329618L, -27273042329611L, -27273042329636L),
			new Class888(-27273042329610L, -27273042329617L, 0L)
		}, new Class886[4]
		{
			new Class886(polar: false, 27273042316901L, 0L, -27273042329613L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329616L, -27273042329611L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, 0L, 50000L, -27273042329610L, -27273042329632L),
			new Class886(polar: false, 27273042316903L, 0L, 50000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329630L, -27273042329609L),
			new Class886(polar: false, 27273042316904L, 0L, -27273042329624L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329626L, -27273042329609L)
		}, new Class516[1]
		{
			new Class516(new Enum115[12]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_0
			}, new long[26]
			{
				-27273042329608L, -27273042329611L, -27273042329608L, -27273042329633L, -27273042329626L, -27273042329626L, -27273042329637L, -27273042329636L, -27273042329630L, -27273042329619L,
				-27273042329630L, -27273042329609L, -27273042329610L, -27273042329617L, -27273042329630L, -27273042329632L, -27273042329630L, -27273042329631L, -27273042329629L, -27273042329631L,
				-27273042329628L, -27273042329628L, -27273042329635L, -5400000L, -27273042329616L, -27273042329611L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
