using ns16;
using ns24;

namespace ns32;

internal class Class671
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 50000L)
		}, new Class541[38]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 87500L, autogenerated: false),
			new Class541("g0", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("g0w", Enum113.const_0, -27273042329613L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("g1", Enum113.const_1, -27273042329604L, 0L, -27273042329613L, autogenerated: false),
			new Class541("g2", Enum113.const_0, -27273042329613L, -27273042329613L, -27273042329615L, autogenerated: false),
			new Class541("g3", Enum113.const_0, -27273042329604L, -27273042329604L, -27273042329615L, autogenerated: false),
			new Class541("g4", Enum113.const_0, -27273042329617L, 2L, 1L, autogenerated: false),
			new Class541("g5", Enum113.const_1, -27273042329618L, 0L, -27273042329616L, autogenerated: false),
			new Class541("g6", Enum113.const_1, -27273042329619L, 0L, -27273042329613L, autogenerated: false),
			new Class541("g6w", Enum113.const_0, -27273042329620L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("g7", Enum113.const_0, -27273042329619L, 1L, 2L, autogenerated: false),
			new Class541("g8", Enum113.const_1, -27273042329622L, 0L, -27273042329613L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329623L, -27273042329646L, -27273042329604L, autogenerated: false),
			new Class541("g10h", Enum113.const_1, -27273042329607L, 0L, -27273042329624L, autogenerated: false),
			new Class541("g11h", Enum113.const_1, -27273042329607L, -27273042329624L, 0L, autogenerated: false),
			new Class541("g12", Enum113.const_0, -27273042329613L, 9598L, 32768L, autogenerated: false),
			new Class541("g12w", Enum113.const_0, -27273042329627L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("g13", Enum113.const_1, -27273042329604L, 0L, -27273042329627L, autogenerated: false),
			new Class541("q1", Enum113.const_0, -27273042329604L, -27273042329604L, 1L, autogenerated: false),
			new Class541("q2", Enum113.const_0, -27273042329629L, -27273042329629L, 1L, autogenerated: false),
			new Class541("q3", Enum113.const_1, -27273042329630L, 0L, -27273042329631L, autogenerated: false),
			new Class541("q4", Enum113.const_14, -27273042329632L, 0L, 0L, autogenerated: false),
			new Class541("dy4", Enum113.const_0, -27273042329633L, -27273042329646L, -27273042329604L, autogenerated: false),
			new Class541("g15h", Enum113.const_1, -27273042329607L, 0L, -27273042329634L, autogenerated: false),
			new Class541("g16h", Enum113.const_1, -27273042329607L, -27273042329634L, 0L, autogenerated: false),
			new Class541("g17w", Enum113.const_1, -27273042329621L, 0L, -27273042329614L, autogenerated: false),
			new Class541("g18w", Enum113.const_0, -27273042329637L, 1L, 2L, autogenerated: false),
			new Class541("dx2p", Enum113.const_1, -27273042329614L, -27273042329638L, -27273042329602L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329639L, -1L, 1L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329646L, -1L, 1L, autogenerated: false),
			new Class541("stAng1", Enum113.const_5, -27273042329640L, -27273042329641L, 0L, autogenerated: false),
			new Class541("enAngp1", Enum113.const_5, -27273042329640L, -27273042329646L, 0L, autogenerated: false),
			new Class541("enAng1", Enum113.const_1, -27273042329643L, 0L, 21600000L, autogenerated: false),
			new Class541("swAng1", Enum113.const_1, -27273042329644L, 0L, -27273042329642L, autogenerated: false),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329609L, -27273042329647L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329648L),
			new Class888(-27273042329610L, -27273042329611L, -27273042329649L),
			new Class888(-27273042329614L, -27273042329607L, 0L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, 0L, 87500L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329614L, -27273042329607L)
		}, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_0
			}, new long[10] { -27273042329610L, -27273042329611L, -27273042329602L, -27273042329646L, -27273042329649L, -27273042329648L, -27273042329638L, -27273042329624L, -27273042329642L, -27273042329645L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329628L, -27273042329635L), new Class887(-27273042329614L, -27273042329636L));
	}
}
