using ns16;
using ns24;

namespace ns32;

internal class Class589
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 25000L)
		}, new Class541[11]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329604L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329611L, 0L, -27273042329613L, autogenerated: false),
			new Class541("y2", Enum113.const_0, -27273042329614L, 1L, 2L, autogenerated: false),
			new Class541("y3", Enum113.const_2, -27273042329613L, -27273042329611L, 2L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329610L, 0L, -27273042329613L, autogenerated: false),
			new Class541("x2", Enum113.const_0, -27273042329617L, 1L, 2L, autogenerated: false),
			new Class541("x3", Enum113.const_2, -27273042329613L, -27273042329610L, 2L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[6]
		{
			new Class888(-27273042329619L, -27273042329609L, -27273042329620L),
			new Class888(-27273042329618L, -27273042329613L, -27273042329620L),
			new Class888(-27273042329608L, -27273042329616L, -27273042329621L),
			new Class888(-27273042329618L, -27273042329611L, -27273042329622L),
			new Class888(-27273042329617L, -27273042329616L, 0L),
			new Class888(-27273042329610L, -27273042329615L, 0L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 100000L, -27273042329608L, -27273042329613L)
		}, new Class516[4]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329613L, -27273042329617L, -27273042329613L, -27273042329617L, -27273042329611L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329617L, -27273042329613L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329614L, -27273042329617L, -27273042329611L }, 0L, 0L, Enum271.const_5, stroke: false, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329613L, -27273042329613L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329617L, -27273042329613L }, 0L, 0L, Enum271.const_3, stroke: false, extrusionOk: false),
			new Class516(new Enum115[12]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_1,
				Enum115.const_2
			}, new long[22]
			{
				-27273042329608L, -27273042329613L, -27273042329613L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329614L, -27273042329617L, -27273042329611L,
				-27273042329608L, -27273042329611L, -27273042329608L, -27273042329613L, -27273042329617L, -27273042329613L, -27273042329610L, -27273042329609L, -27273042329617L, -27273042329613L,
				-27273042329617L, -27273042329611L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329608L, -27273042329613L), new Class887(-27273042329617L, -27273042329611L));
	}
}
