using ns16;
using ns24;

namespace ns32;

internal class Class558
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[44]
		{
			new Class541("dx2", Enum113.const_0, -27273042329604L, 3L, 8L, autogenerated: false),
			new Class541("g9", Enum113.const_1, -27273042329607L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g10", Enum113.const_1, -27273042329607L, -27273042329612L, 0L, autogenerated: false),
			new Class541("g11", Enum113.const_1, -27273042329606L, 0L, -27273042329612L, autogenerated: false),
			new Class541("g12", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("g13", Enum113.const_0, -27273042329604L, 3L, 4L, autogenerated: false),
			new Class541("g14", Enum113.const_0, -27273042329617L, 1455L, 21600L, autogenerated: false),
			new Class541("g15", Enum113.const_0, -27273042329617L, 1905L, 21600L, autogenerated: false),
			new Class541("g16", Enum113.const_0, -27273042329617L, 2325L, 21600L, autogenerated: false),
			new Class541("g17", Enum113.const_0, -27273042329617L, 16155L, 21600L, autogenerated: false),
			new Class541("g18", Enum113.const_0, -27273042329617L, 17010L, 21600L, autogenerated: false),
			new Class541("g19", Enum113.const_0, -27273042329617L, 19335L, 21600L, autogenerated: false),
			new Class541("g20", Enum113.const_0, -27273042329617L, 19725L, 21600L, autogenerated: false),
			new Class541("g21", Enum113.const_0, -27273042329617L, 20595L, 21600L, autogenerated: false),
			new Class541("g22", Enum113.const_0, -27273042329617L, 5280L, 21600L, autogenerated: false),
			new Class541("g23", Enum113.const_0, -27273042329617L, 5730L, 21600L, autogenerated: false),
			new Class541("g24", Enum113.const_0, -27273042329617L, 6630L, 21600L, autogenerated: false),
			new Class541("g25", Enum113.const_0, -27273042329617L, 7492L, 21600L, autogenerated: false),
			new Class541("g26", Enum113.const_0, -27273042329617L, 9067L, 21600L, autogenerated: false),
			new Class541("g27", Enum113.const_0, -27273042329617L, 9555L, 21600L, autogenerated: false),
			new Class541("g28", Enum113.const_0, -27273042329617L, 13342L, 21600L, autogenerated: false),
			new Class541("g29", Enum113.const_0, -27273042329617L, 14580L, 21600L, autogenerated: false),
			new Class541("g30", Enum113.const_0, -27273042329617L, 15592L, 21600L, autogenerated: false),
			new Class541("g31", Enum113.const_1, -27273042329615L, -27273042329618L, 0L, autogenerated: false),
			new Class541("g32", Enum113.const_1, -27273042329615L, -27273042329619L, 0L, autogenerated: false),
			new Class541("g33", Enum113.const_1, -27273042329615L, -27273042329620L, 0L, autogenerated: false),
			new Class541("g34", Enum113.const_1, -27273042329615L, -27273042329621L, 0L, autogenerated: false),
			new Class541("g35", Enum113.const_1, -27273042329615L, -27273042329622L, 0L, autogenerated: false),
			new Class541("g36", Enum113.const_1, -27273042329615L, -27273042329623L, 0L, autogenerated: false),
			new Class541("g37", Enum113.const_1, -27273042329615L, -27273042329624L, 0L, autogenerated: false),
			new Class541("g38", Enum113.const_1, -27273042329615L, -27273042329625L, 0L, autogenerated: false),
			new Class541("g39", Enum113.const_1, -27273042329613L, -27273042329626L, 0L, autogenerated: false),
			new Class541("g40", Enum113.const_1, -27273042329613L, -27273042329627L, 0L, autogenerated: false),
			new Class541("g41", Enum113.const_1, -27273042329613L, -27273042329628L, 0L, autogenerated: false),
			new Class541("g42", Enum113.const_1, -27273042329613L, -27273042329629L, 0L, autogenerated: false),
			new Class541("g43", Enum113.const_1, -27273042329613L, -27273042329630L, 0L, autogenerated: false),
			new Class541("g44", Enum113.const_1, -27273042329613L, -27273042329631L, 0L, autogenerated: false),
			new Class541("g45", Enum113.const_1, -27273042329613L, -27273042329632L, 0L, autogenerated: false),
			new Class541("g46", Enum113.const_1, -27273042329613L, -27273042329633L, 0L, autogenerated: false),
			new Class541("g47", Enum113.const_1, -27273042329613L, -27273042329634L, 0L, autogenerated: false),
			new Class541("g48", Enum113.const_1, -27273042329613L, -27273042329635L, 0L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329653L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329654L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329655L)
		}, null, new Class516[4]
		{
			new Class516(new Enum115[25]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0,
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[46]
			{
				-27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L, -27273042329615L, -27273042329643L,
				-27273042329615L, -27273042329648L, -27273042329635L, -27273042329648L, -27273042329636L, -27273042329647L, -27273042329637L, -27273042329647L, -27273042329637L, -27273042329651L,
				-27273042329639L, -27273042329651L, -27273042329639L, -27273042329649L, -27273042329640L, -27273042329649L, -27273042329642L, -27273042329650L, -27273042329616L, -27273042329650L,
				-27273042329616L, -27273042329645L, -27273042329642L, -27273042329645L, -27273042329641L, -27273042329646L, -27273042329639L, -27273042329646L, -27273042329639L, -27273042329645L,
				-27273042329638L, -27273042329644L, -27273042329636L, -27273042329644L, -27273042329635L, -27273042329643L
			}, 0L, 0L, Enum271.const_1, stroke: false, extrusionOk: false),
			new Class516(new Enum115[20]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[38]
			{
				-27273042329615L, -27273042329643L, -27273042329615L, -27273042329648L, -27273042329635L, -27273042329648L, -27273042329636L, -27273042329647L, -27273042329637L, -27273042329647L,
				-27273042329637L, -27273042329651L, -27273042329639L, -27273042329651L, -27273042329639L, -27273042329649L, -27273042329640L, -27273042329649L, -27273042329642L, -27273042329650L,
				-27273042329616L, -27273042329650L, -27273042329616L, -27273042329645L, -27273042329642L, -27273042329645L, -27273042329641L, -27273042329646L, -27273042329639L, -27273042329646L,
				-27273042329639L, -27273042329645L, -27273042329638L, -27273042329644L, -27273042329636L, -27273042329644L, -27273042329635L, -27273042329643L
			}, 0L, 0L, Enum271.const_4, stroke: false, extrusionOk: false),
			new Class516(new Enum115[20]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[38]
			{
				-27273042329615L, -27273042329643L, -27273042329635L, -27273042329643L, -27273042329636L, -27273042329644L, -27273042329638L, -27273042329644L, -27273042329639L, -27273042329645L,
				-27273042329639L, -27273042329646L, -27273042329641L, -27273042329646L, -27273042329642L, -27273042329645L, -27273042329616L, -27273042329645L, -27273042329616L, -27273042329650L,
				-27273042329642L, -27273042329650L, -27273042329640L, -27273042329649L, -27273042329639L, -27273042329649L, -27273042329639L, -27273042329651L, -27273042329637L, -27273042329651L,
				-27273042329637L, -27273042329647L, -27273042329636L, -27273042329647L, -27273042329635L, -27273042329648L, -27273042329615L, -27273042329648L
			}, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: false),
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329610L, -27273042329609L, -27273042329610L, -27273042329611L, -27273042329608L, -27273042329611L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
