using ns16;
using ns24;

namespace ns32;

internal class Class705
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 37500L)
		}, new Class541[57]
		{
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("dx1", Enum113.const_0, -27273042329664L, 92388L, 100000L, autogenerated: false),
			new Class541("dx2", Enum113.const_0, -27273042329664L, 70711L, 100000L, autogenerated: false),
			new Class541("dx3", Enum113.const_0, -27273042329664L, 38268L, 100000L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329665L, 92388L, 100000L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329665L, 70711L, 100000L, autogenerated: false),
			new Class541("dy3", Enum113.const_0, -27273042329665L, 38268L, 100000L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329613L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329606L, 0L, -27273042329614L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329606L, 0L, -27273042329615L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329606L, -27273042329615L, 0L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329606L, -27273042329614L, 0L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329606L, -27273042329613L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329607L, 0L, -27273042329616L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, 0L, -27273042329617L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329607L, 0L, -27273042329618L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329607L, -27273042329618L, 0L, autogenerated: false),
			new Class541("y5", Enum113.const_1, -27273042329607L, -27273042329617L, 0L, autogenerated: false),
			new Class541("y6", Enum113.const_1, -27273042329607L, -27273042329616L, 0L, autogenerated: false),
			new Class541("iwd2", Enum113.const_0, -27273042329664L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("ihd2", Enum113.const_0, -27273042329665L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("sdx1", Enum113.const_0, -27273042329631L, 98079L, 100000L, autogenerated: false),
			new Class541("sdx2", Enum113.const_0, -27273042329631L, 83147L, 100000L, autogenerated: false),
			new Class541("sdx3", Enum113.const_0, -27273042329631L, 55557L, 100000L, autogenerated: false),
			new Class541("sdx4", Enum113.const_0, -27273042329631L, 19509L, 100000L, autogenerated: false),
			new Class541("sdy1", Enum113.const_0, -27273042329632L, 98079L, 100000L, autogenerated: false),
			new Class541("sdy2", Enum113.const_0, -27273042329632L, 83147L, 100000L, autogenerated: false),
			new Class541("sdy3", Enum113.const_0, -27273042329632L, 55557L, 100000L, autogenerated: false),
			new Class541("sdy4", Enum113.const_0, -27273042329632L, 19509L, 100000L, autogenerated: false),
			new Class541("sx1", Enum113.const_1, -27273042329606L, 0L, -27273042329633L, autogenerated: false),
			new Class541("sx2", Enum113.const_1, -27273042329606L, 0L, -27273042329634L, autogenerated: false),
			new Class541("sx3", Enum113.const_1, -27273042329606L, 0L, -27273042329635L, autogenerated: false),
			new Class541("sx4", Enum113.const_1, -27273042329606L, 0L, -27273042329636L, autogenerated: false),
			new Class541("sx5", Enum113.const_1, -27273042329606L, -27273042329636L, 0L, autogenerated: false),
			new Class541("sx6", Enum113.const_1, -27273042329606L, -27273042329635L, 0L, autogenerated: false),
			new Class541("sx7", Enum113.const_1, -27273042329606L, -27273042329634L, 0L, autogenerated: false),
			new Class541("sx8", Enum113.const_1, -27273042329606L, -27273042329633L, 0L, autogenerated: false),
			new Class541("sy1", Enum113.const_1, -27273042329607L, 0L, -27273042329637L, autogenerated: false),
			new Class541("sy2", Enum113.const_1, -27273042329607L, 0L, -27273042329638L, autogenerated: false),
			new Class541("sy3", Enum113.const_1, -27273042329607L, 0L, -27273042329639L, autogenerated: false),
			new Class541("sy4", Enum113.const_1, -27273042329607L, 0L, -27273042329640L, autogenerated: false),
			new Class541("sy5", Enum113.const_1, -27273042329607L, -27273042329640L, 0L, autogenerated: false),
			new Class541("sy6", Enum113.const_1, -27273042329607L, -27273042329639L, 0L, autogenerated: false),
			new Class541("sy7", Enum113.const_1, -27273042329607L, -27273042329638L, 0L, autogenerated: false),
			new Class541("sy8", Enum113.const_1, -27273042329607L, -27273042329637L, 0L, autogenerated: false),
			new Class541("idx", Enum113.const_7, -27273042329631L, 2700000L, 0L, autogenerated: false),
			new Class541("idy", Enum113.const_13, -27273042329632L, 2700000L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_1, -27273042329606L, 0L, -27273042329657L, autogenerated: false),
			new Class541("it", Enum113.const_1, -27273042329607L, 0L, -27273042329658L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329606L, -27273042329657L, 0L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329607L, -27273042329658L, 0L, autogenerated: false),
			new Class541("yAdj", Enum113.const_1, -27273042329607L, 0L, -27273042329632L, autogenerated: false),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[16]
		{
			new Class888(-27273042329623L, -27273042329626L, 0L),
			new Class888(-27273042329624L, -27273042329627L, 0L),
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329624L, -27273042329628L, 0L),
			new Class888(-27273042329623L, -27273042329629L, 0L),
			new Class888(-27273042329622L, -27273042329630L, -27273042329666L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329666L),
			new Class888(-27273042329621L, -27273042329630L, -27273042329666L),
			new Class888(-27273042329620L, -27273042329629L, -27273042329667L),
			new Class888(-27273042329619L, -27273042329628L, -27273042329667L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329667L),
			new Class888(-27273042329619L, -27273042329627L, -27273042329667L),
			new Class888(-27273042329620L, -27273042329626L, -27273042329667L),
			new Class888(-27273042329621L, -27273042329625L, -27273042329668L),
			new Class888(-27273042329606L, -27273042329609L, -27273042329668L),
			new Class888(-27273042329622L, -27273042329625L, -27273042329668L)
		}, new Class886[1]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 50000L, -27273042329606L, -27273042329663L)
		}, new Class516[1]
		{
			new Class516(new Enum115[33]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[64]
			{
				-27273042329608L, -27273042329607L, -27273042329641L, -27273042329652L, -27273042329619L, -27273042329627L, -27273042329642L, -27273042329651L, -27273042329620L, -27273042329626L,
				-27273042329643L, -27273042329650L, -27273042329621L, -27273042329625L, -27273042329644L, -27273042329649L, -27273042329606L, -27273042329609L, -27273042329645L, -27273042329649L,
				-27273042329622L, -27273042329625L, -27273042329646L, -27273042329650L, -27273042329623L, -27273042329626L, -27273042329647L, -27273042329651L, -27273042329624L, -27273042329627L,
				-27273042329648L, -27273042329652L, -27273042329610L, -27273042329607L, -27273042329648L, -27273042329653L, -27273042329624L, -27273042329628L, -27273042329647L, -27273042329654L,
				-27273042329623L, -27273042329629L, -27273042329646L, -27273042329655L, -27273042329622L, -27273042329630L, -27273042329645L, -27273042329656L, -27273042329606L, -27273042329611L,
				-27273042329644L, -27273042329656L, -27273042329621L, -27273042329630L, -27273042329643L, -27273042329655L, -27273042329620L, -27273042329629L, -27273042329642L, -27273042329654L,
				-27273042329619L, -27273042329628L, -27273042329641L, -27273042329653L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329659L, -27273042329660L), new Class887(-27273042329661L, -27273042329662L));
	}
}
