using ns16;
using ns24;

namespace ns32;

internal class Class728
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", -20833L),
			new Class341("adj2", 62500L)
		}, new Class541[37]
		{
			new Class541("dxPos", Enum113.const_0, -27273042329602L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("dyPos", Enum113.const_0, -27273042329603L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("xPos", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("yPos", Enum113.const_1, -27273042329607L, -27273042329613L, 0L, autogenerated: false),
			new Class541("dx", Enum113.const_1, -27273042329614L, 0L, -27273042329606L, autogenerated: false),
			new Class541("dy", Enum113.const_1, -27273042329615L, 0L, -27273042329607L, autogenerated: false),
			new Class541("dq", Enum113.const_0, -27273042329612L, -27273042329603L, -27273042329602L, autogenerated: false),
			new Class541("ady", Enum113.const_4, -27273042329613L, 0L, 0L, autogenerated: false),
			new Class541("adq", Enum113.const_4, -27273042329618L, 0L, 0L, autogenerated: false),
			new Class541("dz", Enum113.const_1, -27273042329619L, 0L, -27273042329620L, autogenerated: false),
			new Class541("xg1", Enum113.const_3, -27273042329612L, 7L, 2L, autogenerated: false),
			new Class541("xg2", Enum113.const_3, -27273042329612L, 10L, 5L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329602L, -27273042329622L, 12L, autogenerated: false),
			new Class541("x2", Enum113.const_0, -27273042329602L, -27273042329623L, 12L, autogenerated: false),
			new Class541("yg1", Enum113.const_3, -27273042329613L, 7L, 2L, autogenerated: false),
			new Class541("yg2", Enum113.const_3, -27273042329613L, 10L, 5L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329603L, -27273042329626L, 12L, autogenerated: false),
			new Class541("y2", Enum113.const_0, -27273042329603L, -27273042329627L, 12L, autogenerated: false),
			new Class541("t1", Enum113.const_3, -27273042329612L, -27273042329608L, -27273042329614L, autogenerated: false),
			new Class541("xl", Enum113.const_3, -27273042329621L, -27273042329608L, -27273042329630L, autogenerated: false),
			new Class541("t2", Enum113.const_3, -27273042329613L, -27273042329624L, -27273042329614L, autogenerated: false),
			new Class541("xt", Enum113.const_3, -27273042329621L, -27273042329632L, -27273042329624L, autogenerated: false),
			new Class541("t3", Enum113.const_3, -27273042329612L, -27273042329614L, -27273042329610L, autogenerated: false),
			new Class541("xr", Enum113.const_3, -27273042329621L, -27273042329610L, -27273042329634L, autogenerated: false),
			new Class541("t4", Enum113.const_3, -27273042329613L, -27273042329614L, -27273042329624L, autogenerated: false),
			new Class541("xb", Enum113.const_3, -27273042329621L, -27273042329636L, -27273042329624L, autogenerated: false),
			new Class541("t5", Enum113.const_3, -27273042329612L, -27273042329628L, -27273042329615L, autogenerated: false),
			new Class541("yl", Enum113.const_3, -27273042329621L, -27273042329628L, -27273042329638L, autogenerated: false),
			new Class541("t6", Enum113.const_3, -27273042329613L, -27273042329609L, -27273042329615L, autogenerated: false),
			new Class541("yt", Enum113.const_3, -27273042329621L, -27273042329640L, -27273042329609L, autogenerated: false),
			new Class541("t7", Enum113.const_3, -27273042329612L, -27273042329615L, -27273042329628L, autogenerated: false),
			new Class541("yr", Enum113.const_3, -27273042329621L, -27273042329628L, -27273042329642L, autogenerated: false),
			new Class541("t8", Enum113.const_3, -27273042329613L, -27273042329615L, -27273042329611L, autogenerated: false),
			new Class541("yb", Enum113.const_3, -27273042329621L, -27273042329644L, -27273042329611L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[5]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329646L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329647L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329648L),
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329614L, -27273042329615L, -27273042329648L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, -2147483647L, 2147483647L, 27273042316902L, -2147483647L, 2147483647L, -27273042329614L, -27273042329615L)
		}, new Class516[1]
		{
			new Class516(new Enum115[17]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[32]
			{
				-27273042329608L, -27273042329609L, -27273042329624L, -27273042329609L, -27273042329633L, -27273042329641L, -27273042329625L, -27273042329609L, -27273042329610L, -27273042329609L,
				-27273042329610L, -27273042329628L, -27273042329635L, -27273042329643L, -27273042329610L, -27273042329629L, -27273042329610L, -27273042329611L, -27273042329625L, -27273042329611L,
				-27273042329637L, -27273042329645L, -27273042329624L, -27273042329611L, -27273042329608L, -27273042329611L, -27273042329608L, -27273042329629L, -27273042329631L, -27273042329639L,
				-27273042329608L, -27273042329628L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
