using ns16;
using ns24;

namespace ns32;

internal class Class679
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[6]
		{
			new Class541("g1", Enum113.const_7, -27273042329602L, 13500000L, 0L, autogenerated: false),
			new Class541("g2", Enum113.const_13, -27273042329603L, 13500000L, 0L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329610L, -27273042329612L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329611L, -27273042329613L, 0L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true)
		}, new Class888[2]
		{
			new Class888(-27273042329610L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329616L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329611L, -27273042329602L, -27273042329603L, -27273042329617L, -27273042329616L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329614L, -27273042329615L), new Class887(-27273042329610L, -27273042329611L));
	}
}
