using ns16;
using ns24;

namespace ns32;

internal class Class585
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", -20833L),
			new Class341("adj2", 62500L)
		}, new Class541[48]
		{
			new Class541("dxPos", Enum113.const_0, -27273042329602L, 27273042316901L, 100000L, autogenerated: false),
			new Class541("dyPos", Enum113.const_0, -27273042329603L, 27273042316902L, 100000L, autogenerated: false),
			new Class541("xPos", Enum113.const_1, -27273042329606L, -27273042329612L, 0L, autogenerated: false),
			new Class541("yPos", Enum113.const_1, -27273042329607L, -27273042329613L, 0L, autogenerated: false),
			new Class541("ht", Enum113.const_6, -27273042329655L, -27273042329612L, -27273042329613L, autogenerated: false),
			new Class541("wt", Enum113.const_12, -27273042329656L, -27273042329612L, -27273042329613L, autogenerated: false),
			new Class541("g2", Enum113.const_6, -27273042329656L, -27273042329616L, -27273042329617L, autogenerated: false),
			new Class541("g3", Enum113.const_12, -27273042329655L, -27273042329616L, -27273042329617L, autogenerated: false),
			new Class541("g4", Enum113.const_1, -27273042329606L, -27273042329618L, 0L, autogenerated: false),
			new Class541("g5", Enum113.const_1, -27273042329607L, -27273042329619L, 0L, autogenerated: false),
			new Class541("g6", Enum113.const_1, -27273042329620L, 0L, -27273042329614L, autogenerated: false),
			new Class541("g7", Enum113.const_1, -27273042329621L, 0L, -27273042329615L, autogenerated: false),
			new Class541("g8", Enum113.const_10, -27273042329622L, -27273042329623L, 0L, autogenerated: false),
			new Class541("g9", Enum113.const_0, -27273042329604L, 6600L, 21600L, autogenerated: false),
			new Class541("g10", Enum113.const_1, -27273042329624L, 0L, -27273042329625L, autogenerated: false),
			new Class541("g11", Enum113.const_0, -27273042329626L, 1L, 3L, autogenerated: false),
			new Class541("g12", Enum113.const_0, -27273042329604L, 1800L, 21600L, autogenerated: false),
			new Class541("g13", Enum113.const_1, -27273042329627L, -27273042329628L, 0L, autogenerated: false),
			new Class541("g14", Enum113.const_0, -27273042329629L, -27273042329622L, -27273042329624L, autogenerated: false),
			new Class541("g15", Enum113.const_0, -27273042329629L, -27273042329623L, -27273042329624L, autogenerated: false),
			new Class541("g16", Enum113.const_1, -27273042329630L, -27273042329614L, 0L, autogenerated: false),
			new Class541("g17", Enum113.const_1, -27273042329631L, -27273042329615L, 0L, autogenerated: false),
			new Class541("g18", Enum113.const_0, -27273042329604L, 4800L, 21600L, autogenerated: false),
			new Class541("g19", Enum113.const_0, -27273042329627L, 2L, 1L, autogenerated: false),
			new Class541("g20", Enum113.const_1, -27273042329634L, -27273042329635L, 0L, autogenerated: false),
			new Class541("g21", Enum113.const_0, -27273042329636L, -27273042329622L, -27273042329624L, autogenerated: false),
			new Class541("g22", Enum113.const_0, -27273042329636L, -27273042329623L, -27273042329624L, autogenerated: false),
			new Class541("g23", Enum113.const_1, -27273042329637L, -27273042329614L, 0L, autogenerated: false),
			new Class541("g24", Enum113.const_1, -27273042329638L, -27273042329615L, 0L, autogenerated: false),
			new Class541("g25", Enum113.const_0, -27273042329604L, 1200L, 21600L, autogenerated: false),
			new Class541("g26", Enum113.const_0, -27273042329604L, 600L, 21600L, autogenerated: false),
			new Class541("x23", Enum113.const_1, -27273042329614L, -27273042329642L, 0L, autogenerated: false),
			new Class541("x24", Enum113.const_1, -27273042329632L, -27273042329641L, 0L, autogenerated: false),
			new Class541("x25", Enum113.const_1, -27273042329639L, -27273042329628L, 0L, autogenerated: false),
			new Class541("il", Enum113.const_0, -27273042329602L, 2977L, 21600L, autogenerated: false),
			new Class541("it", Enum113.const_0, -27273042329603L, 3262L, 21600L, autogenerated: false),
			new Class541("ir", Enum113.const_0, -27273042329602L, 17087L, 21600L, autogenerated: false),
			new Class541("ib", Enum113.const_0, -27273042329603L, 17337L, 21600L, autogenerated: false),
			new Class541("g27", Enum113.const_0, -27273042329602L, 67L, 21600L, autogenerated: false),
			new Class541("g28", Enum113.const_0, -27273042329603L, 21577L, 21600L, autogenerated: false),
			new Class541("g29", Enum113.const_0, -27273042329602L, 21582L, 21600L, autogenerated: false),
			new Class541("g30", Enum113.const_0, -27273042329603L, 1235L, 21600L, autogenerated: false),
			new Class541("pang", Enum113.const_5, -27273042329612L, -27273042329613L, 0L, autogenerated: false),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[5]
		{
			new Class888(-27273042329650L, -27273042329607L, -27273042329657L),
			new Class888(-27273042329606L, -27273042329651L, -27273042329658L),
			new Class888(-27273042329652L, -27273042329607L, 0L),
			new Class888(-27273042329606L, -27273042329653L, -27273042329659L),
			new Class888(-27273042329614L, -27273042329615L, -27273042329654L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, -2147483647L, 2147483647L, 27273042316902L, -2147483647L, 2147483647L, -27273042329614L, -27273042329615L)
		}, new Class516[5]
		{
			new Class516(new Enum115[13]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_3,
				Enum115.const_0
			}, new long[46]
			{
				3900L, 14370L, 6753L, 9190L, -11429249L, 7426832L, 5333L, 7267L, -8646143L, 5396714L,
				4365L, 5945L, -8748475L, 5983381L, 4857L, 6595L, -7859164L, 7034504L, 5333L, 7273L,
				-4722533L, 6541615L, 6775L, 9220L, -2776035L, 7816140L, 5785L, 7867L, 37501L, 6842000L,
				6752L, 9215L, 1347096L, 6910353L, 7720L, 10543L, 3974558L, 4542661L, 4360L, 5918L,
				-16496525L, 8804134L, 4345L, 5945L, -14809710L, 9151131L
			}, 43200L, 43200L, Enum271.const_1, stroke: true, extrusionOk: true),
			new Class516(new Enum115[3]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[6] { -27273042329643L, -27273042329615L, -27273042329642L, -27273042329642L, 0L, 21600000L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true),
			new Class516(new Enum115[3]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[6] { -27273042329644L, -27273042329633L, -27273042329641L, -27273042329641L, 0L, 21600000L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true),
			new Class516(new Enum115[3]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_0
			}, new long[6] { -27273042329645L, -27273042329640L, -27273042329628L, -27273042329628L, 0L, 21600000L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true),
			new Class516(new Enum115[22]
			{
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3,
				Enum115.const_1,
				Enum115.const_3
			}, new long[66]
			{
				4693L, 26177L, 4345L, 5945L, 5204520L, 1585770L, 6928L, 34899L, 4360L, 5918L,
				4416628L, 686848L, 16478L, 39090L, 6752L, 9215L, 8257449L, 844866L, 28827L, 34751L,
				6752L, 9215L, 387196L, 959901L, 34129L, 22954L, 5785L, 7867L, -4217541L, 4255042L,
				41798L, 15354L, 5333L, 7273L, 1819082L, 1665090L, 38324L, 5426L, 4857L, 6595L,
				-824660L, 891534L, 29078L, 3952L, 4857L, 6595L, -8950887L, 1091722L, 22141L, 4720L,
				4365L, 5945L, -9809656L, 1061181L, 14000L, 5192L, 6753L, 9190L, -4002417L, 739161L,
				4127L, 15789L, 6753L, 9190L, 9459261L, 711490L
			}, 43200L, 43200L, Enum271.const_0, stroke: true, extrusionOk: false)
		}, new Class887(-27273042329646L, -27273042329647L), new Class887(-27273042329648L, -27273042329649L));
	}
}
