using ns16;
using ns24;

namespace ns32;

internal class Class726
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[2]
		{
			new Class341("adj1", 12500L),
			new Class341("adj2", 0L)
		}, new Class541[33]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 20000L, autogenerated: false),
			new Class541("a2", Enum113.const_11, -10000L, 27273042316902L, 10000L, autogenerated: false),
			new Class541("y1", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329614L, 10L, 3L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329614L, 0L, -27273042329615L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329614L, -27273042329615L, 0L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329611L, 0L, -27273042329614L, autogenerated: false),
			new Class541("y5", Enum113.const_1, -27273042329618L, 0L, -27273042329615L, autogenerated: false),
			new Class541("y6", Enum113.const_1, -27273042329618L, -27273042329615L, 0L, autogenerated: false),
			new Class541("dx1", Enum113.const_0, -27273042329602L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("of2", Enum113.const_0, -27273042329602L, -27273042329613L, 50000L, autogenerated: false),
			new Class541("x1", Enum113.const_4, -27273042329621L, 0L, 0L, autogenerated: false),
			new Class541("dx2", Enum113.const_3, -27273042329622L, 0L, -27273042329622L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329608L, 0L, -27273042329624L, autogenerated: false),
			new Class541("dx5", Enum113.const_3, -27273042329622L, -27273042329622L, 0L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329610L, 0L, -27273042329626L, autogenerated: false),
			new Class541("dx3", Enum113.const_2, -27273042329624L, -27273042329627L, 3L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329625L, -27273042329628L, 0L, autogenerated: false),
			new Class541("x4", Enum113.const_2, -27273042329629L, -27273042329627L, 2L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329608L, -27273042329626L, 0L, autogenerated: false),
			new Class541("x10", Enum113.const_1, -27273042329610L, -27273042329624L, 0L, autogenerated: false),
			new Class541("x7", Enum113.const_1, -27273042329631L, -27273042329628L, 0L, autogenerated: false),
			new Class541("x8", Enum113.const_2, -27273042329633L, -27273042329632L, 2L, autogenerated: false),
			new Class541("x9", Enum113.const_1, -27273042329610L, 0L, -27273042329623L, autogenerated: false),
			new Class541("xAdj", Enum113.const_1, -27273042329606L, -27273042329621L, 0L, autogenerated: false),
			new Class541("xAdj2", Enum113.const_1, -27273042329606L, 0L, -27273042329621L, autogenerated: false),
			new Class541("il", Enum113.const_8, -27273042329625L, -27273042329631L, 0L, autogenerated: false),
			new Class541("ir", Enum113.const_9, -27273042329627L, -27273042329632L, 0L, autogenerated: false),
			new Class541("it", Enum113.const_0, -27273042329603L, -27273042329612L, 50000L, autogenerated: false),
			new Class541("ib", Enum113.const_1, -27273042329611L, 0L, -27273042329640L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329637L, -27273042329614L, -27273042329642L),
			new Class888(-27273042329623L, -27273042329607L, -27273042329643L),
			new Class888(-27273042329636L, -27273042329618L, -27273042329644L),
			new Class888(-27273042329635L, -27273042329607L, 0L)
		}, new Class886[2]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 20000L, -27273042329608L, -27273042329614L),
			new Class886(polar: false, 27273042316902L, -10000L, 10000L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329636L, -27273042329611L)
		}, new Class516[1]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_5,
				Enum115.const_2,
				Enum115.const_5,
				Enum115.const_0
			}, new long[16]
			{
				-27273042329625L, -27273042329614L, -27273042329629L, -27273042329616L, -27273042329630L, -27273042329617L, -27273042329627L, -27273042329614L, -27273042329632L, -27273042329618L,
				-27273042329634L, -27273042329620L, -27273042329633L, -27273042329619L, -27273042329631L, -27273042329618L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329638L, -27273042329640L), new Class887(-27273042329639L, -27273042329641L));
	}
}
