using ns16;
using ns24;

namespace ns32;

internal class Class718
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[1]
		{
			new Class341("adj", 25000L)
		}, new Class541[14]
		{
			new Class541("maxAdj", Enum113.const_0, 50000L, -27273042329602L, -27273042329604L, autogenerated: false),
			new Class541("a", Enum113.const_11, 0L, 27273042316901L, -27273042329612L, autogenerated: false),
			new Class541("x1", Enum113.const_0, -27273042329604L, -27273042329613L, 200000L, autogenerated: false),
			new Class541("x2", Enum113.const_0, -27273042329604L, -27273042329613L, 100000L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329610L, 0L, -27273042329615L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329610L, 0L, -27273042329614L, autogenerated: false),
			new Class541("il", Enum113.const_0, -27273042329621L, -27273042329613L, -27273042329612L, autogenerated: false),
			new Class541("it", Enum113.const_0, -27273042329622L, -27273042329613L, -27273042329612L, autogenerated: false),
			new Class541("ir", Enum113.const_1, -27273042329610L, 0L, -27273042329618L, autogenerated: false),
			new Class541("wd3", Enum113.const_0, -27273042329602L, 1L, 3L, autogenerated: true),
			new Class541("hd3", Enum113.const_0, -27273042329603L, 1L, 3L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true)
		}, new Class888[4]
		{
			new Class888(-27273042329606L, -27273042329609L, -27273042329623L),
			new Class888(-27273042329614L, -27273042329607L, -27273042329624L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329625L),
			new Class888(-27273042329617L, -27273042329607L, 0L)
		}, new Class886[1]
		{
			new Class886(polar: false, 27273042316901L, 0L, -27273042329612L, long.MaxValue, long.MaxValue, long.MaxValue, -27273042329615L, -27273042329609L)
		}, new Class516[1]
		{
			new Class516(new Enum115[5]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[8] { -27273042329608L, -27273042329611L, -27273042329615L, -27273042329609L, -27273042329616L, -27273042329609L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329618L, -27273042329619L), new Class887(-27273042329620L, -27273042329611L));
	}
}
