using ns16;
using ns24;

namespace ns32;

internal class Class696
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[7]
		{
			new Class541("it", Enum113.const_0, -27273042329603L, 7L, 12L, autogenerated: false),
			new Class541("ir", Enum113.const_0, -27273042329602L, 7L, 12L, autogenerated: false),
			new Class541("ib", Enum113.const_0, -27273042329603L, 11L, 12L, autogenerated: false),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("wd12", Enum113.const_0, -27273042329602L, 1L, 12L, autogenerated: true)
		}, new Class888[6]
		{
			new Class888(-27273042329608L, -27273042329609L, -27273042329615L),
			new Class888(-27273042329608L, -27273042329607L, -27273042329616L),
			new Class888(-27273042329608L, -27273042329611L, -27273042329617L),
			new Class888(-27273042329606L, -27273042329611L, -27273042329617L),
			new Class888(-27273042329610L, -27273042329611L, -27273042329617L),
			new Class888(-27273042329606L, -27273042329607L, 0L)
		}, null, new Class516[1]
		{
			new Class516(new Enum115[4]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[6] { -27273042329608L, -27273042329611L, -27273042329608L, -27273042329609L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329618L, -27273042329612L), new Class887(-27273042329613L, -27273042329614L));
	}
}
