using ns16;
using ns24;

namespace ns32;

internal class Class669
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[3]
		{
			new Class341("adj1", 23520L),
			new Class341("adj2", 6600000L),
			new Class341("adj3", 11760L)
		}, new Class541[59]
		{
			new Class541("a1", Enum113.const_11, 0L, 27273042316901L, 50000L, autogenerated: false),
			new Class541("crAng", Enum113.const_11, 4200000L, 27273042316902L, 6600000L, autogenerated: false),
			new Class541("2a1", Enum113.const_0, -27273042329612L, 2L, 1L, autogenerated: false),
			new Class541("maxAdj3", Enum113.const_1, 100000L, 0L, -27273042329614L, autogenerated: false),
			new Class541("a3", Enum113.const_11, 0L, 27273042316903L, -27273042329615L, autogenerated: false),
			new Class541("dy1", Enum113.const_0, -27273042329603L, -27273042329612L, 100000L, autogenerated: false),
			new Class541("dy2", Enum113.const_0, -27273042329603L, -27273042329616L, 200000L, autogenerated: false),
			new Class541("dx1", Enum113.const_0, -27273042329602L, 73490L, 200000L, autogenerated: false),
			new Class541("x1", Enum113.const_1, -27273042329606L, 0L, -27273042329619L, autogenerated: false),
			new Class541("x8", Enum113.const_1, -27273042329606L, -27273042329619L, 0L, autogenerated: false),
			new Class541("y2", Enum113.const_1, -27273042329607L, 0L, -27273042329618L, autogenerated: false),
			new Class541("y3", Enum113.const_1, -27273042329607L, -27273042329618L, 0L, autogenerated: false),
			new Class541("y1", Enum113.const_1, -27273042329622L, 0L, -27273042329617L, autogenerated: false),
			new Class541("y4", Enum113.const_1, -27273042329623L, -27273042329617L, 0L, autogenerated: false),
			new Class541("cadj2", Enum113.const_1, -27273042329613L, 0L, -27273042329667L, autogenerated: false),
			new Class541("xadj2", Enum113.const_15, -27273042329668L, -27273042329626L, 0L, autogenerated: false),
			new Class541("len", Enum113.const_10, -27273042329627L, -27273042329668L, 0L, autogenerated: false),
			new Class541("bhw", Enum113.const_0, -27273042329628L, -27273042329617L, -27273042329668L, autogenerated: false),
			new Class541("bhw2", Enum113.const_0, -27273042329629L, 1L, 2L, autogenerated: false),
			new Class541("x7", Enum113.const_1, -27273042329606L, -27273042329627L, -27273042329630L, autogenerated: false),
			new Class541("dx67", Enum113.const_0, -27273042329627L, -27273042329624L, -27273042329668L, autogenerated: false),
			new Class541("x6", Enum113.const_1, -27273042329631L, 0L, -27273042329632L, autogenerated: false),
			new Class541("dx57", Enum113.const_0, -27273042329627L, -27273042329622L, -27273042329668L, autogenerated: false),
			new Class541("x5", Enum113.const_1, -27273042329631L, 0L, -27273042329634L, autogenerated: false),
			new Class541("dx47", Enum113.const_0, -27273042329627L, -27273042329623L, -27273042329668L, autogenerated: false),
			new Class541("x4", Enum113.const_1, -27273042329631L, 0L, -27273042329636L, autogenerated: false),
			new Class541("dx37", Enum113.const_0, -27273042329627L, -27273042329625L, -27273042329668L, autogenerated: false),
			new Class541("x3", Enum113.const_1, -27273042329631L, 0L, -27273042329638L, autogenerated: false),
			new Class541("dx27", Enum113.const_0, -27273042329627L, 2L, 1L, autogenerated: false),
			new Class541("x2", Enum113.const_1, -27273042329631L, 0L, -27273042329640L, autogenerated: false),
			new Class541("rx7", Enum113.const_1, -27273042329631L, -27273042329629L, 0L, autogenerated: false),
			new Class541("rx6", Enum113.const_1, -27273042329633L, -27273042329629L, 0L, autogenerated: false),
			new Class541("rx5", Enum113.const_1, -27273042329635L, -27273042329629L, 0L, autogenerated: false),
			new Class541("rx4", Enum113.const_1, -27273042329637L, -27273042329629L, 0L, autogenerated: false),
			new Class541("rx3", Enum113.const_1, -27273042329639L, -27273042329629L, 0L, autogenerated: false),
			new Class541("rx2", Enum113.const_1, -27273042329641L, -27273042329629L, 0L, autogenerated: false),
			new Class541("dx7", Enum113.const_0, -27273042329617L, -27273042329668L, -27273042329628L, autogenerated: false),
			new Class541("rxt", Enum113.const_1, -27273042329631L, -27273042329648L, 0L, autogenerated: false),
			new Class541("lxt", Enum113.const_1, -27273042329642L, 0L, -27273042329648L, autogenerated: false),
			new Class541("rx", Enum113.const_3, -27273042329626L, -27273042329649L, -27273042329642L, autogenerated: false),
			new Class541("lx", Enum113.const_3, -27273042329626L, -27273042329631L, -27273042329650L, autogenerated: false),
			new Class541("dy3", Enum113.const_0, -27273042329617L, -27273042329627L, -27273042329628L, autogenerated: false),
			new Class541("dy4", Enum113.const_1, 0L, 0L, -27273042329653L, autogenerated: false),
			new Class541("ry", Enum113.const_3, -27273042329626L, -27273042329653L, -27273042329609L, autogenerated: false),
			new Class541("ly", Enum113.const_3, -27273042329626L, -27273042329609L, -27273042329654L, autogenerated: false),
			new Class541("dlx", Enum113.const_1, -27273042329602L, 0L, -27273042329651L, autogenerated: false),
			new Class541("drx", Enum113.const_1, -27273042329602L, 0L, -27273042329652L, autogenerated: false),
			new Class541("dly", Enum113.const_1, -27273042329603L, 0L, -27273042329655L, autogenerated: false),
			new Class541("dry", Enum113.const_1, -27273042329603L, 0L, -27273042329656L, autogenerated: false),
			new Class541("xC1", Enum113.const_2, -27273042329651L, -27273042329652L, 2L, autogenerated: false),
			new Class541("xC2", Enum113.const_2, -27273042329658L, -27273042329657L, 2L, autogenerated: false),
			new Class541("yC1", Enum113.const_2, -27273042329655L, -27273042329656L, 2L, autogenerated: false),
			new Class541("yC2", Enum113.const_2, -27273042329624L, -27273042329622L, 2L, autogenerated: false),
			new Class541("yC3", Enum113.const_2, -27273042329623L, -27273042329625L, 2L, autogenerated: false),
			new Class541("yC4", Enum113.const_2, -27273042329660L, -27273042329659L, 2L, autogenerated: false),
			new Class541("cd4", Enum113.const_0, -27273042329601L, 1L, 4L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true),
			new Class541("cd2", Enum113.const_0, -27273042329601L, 1L, 2L, autogenerated: true),
			new Class541("3cd4", Enum113.const_0, -27273042329601L, 3L, 4L, autogenerated: true)
		}, new Class888[6]
		{
			new Class888(-27273042329621L, -27273042329664L, 0L),
			new Class888(-27273042329621L, -27273042329665L, 0L),
			new Class888(-27273042329662L, -27273042329666L, -27273042329667L),
			new Class888(-27273042329620L, -27273042329664L, -27273042329669L),
			new Class888(-27273042329620L, -27273042329665L, -27273042329669L),
			new Class888(-27273042329661L, -27273042329663L, -27273042329670L)
		}, new Class886[3]
		{
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316901L, 0L, 50000L, -27273042329608L, -27273042329624L),
			new Class886(polar: true, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316902L, 4200000L, 6600000L, -27273042329652L, -27273042329609L),
			new Class886(polar: false, long.MaxValue, long.MaxValue, long.MaxValue, 27273042316903L, 0L, -27273042329615L, -27273042329610L, -27273042329622L)
		}, new Class516[1]
		{
			new Class516(new Enum115[21]
			{
				Enum115.const_1,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_2,
				Enum115.const_0
			}, new long[40]
			{
				-27273042329620L, -27273042329624L, -27273042329633L, -27273042329624L, -27273042329652L, -27273042329656L, -27273042329651L, -27273042329655L, -27273042329643L, -27273042329624L,
				-27273042329621L, -27273042329624L, -27273042329621L, -27273042329622L, -27273042329644L, -27273042329622L, -27273042329645L, -27273042329623L, -27273042329621L, -27273042329623L,
				-27273042329621L, -27273042329625L, -27273042329646L, -27273042329625L, -27273042329658L, -27273042329660L, -27273042329657L, -27273042329659L, -27273042329639L, -27273042329625L,
				-27273042329620L, -27273042329625L, -27273042329620L, -27273042329623L, -27273042329637L, -27273042329623L, -27273042329635L, -27273042329622L, -27273042329620L, -27273042329622L
			}, 0L, 0L, Enum271.const_1, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329620L, -27273042329624L), new Class887(-27273042329621L, -27273042329625L));
	}
}
