using ns16;
using ns24;

namespace ns32;

internal class Class590
{
	public static Class342 smethod_0()
	{
		return new Class342(new Class341[0], new Class541[2]
		{
			new Class541("wd2", Enum113.const_0, -27273042329602L, 1L, 2L, autogenerated: true),
			new Class541("hd2", Enum113.const_0, -27273042329603L, 1L, 2L, autogenerated: true)
		}, null, null, new Class516[1]
		{
			new Class516(new Enum115[2]
			{
				Enum115.const_1,
				Enum115.const_5
			}, new long[8] { -27273042329608L, -27273042329609L, -27273042329612L, -27273042329609L, -27273042329610L, -27273042329613L, -27273042329610L, -27273042329611L }, 0L, 0L, Enum271.const_0, stroke: true, extrusionOk: true)
		}, new Class887(-27273042329608L, -27273042329609L), new Class887(-27273042329610L, -27273042329611L));
	}
}
