using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using ns218;
using ns221;
using ns224;
using ns233;
using ns234;
using ns235;

namespace ns220;

internal class Class6694
{
	private bool bool_0;

	private readonly Class6688 class6688_0;

	private readonly Class5947 class5947_0;

	private readonly bool bool_1;

	private int int_0;

	internal Class6694(Class6688 wpfContext, Class5947 fiexdPageWriter, bool isXps)
	{
		class6688_0 = wpfContext;
		class5947_0 = fiexdPageWriter;
		bool_1 = isXps;
	}

	internal void method_0(int pageNumber, float width, float height)
	{
		int_0 = pageNumber;
		if (bool_1)
		{
			class5947_0.method_0("FixedPage");
		}
		else
		{
			class5947_0.method_2("FixedPage");
		}
		if (bool_1)
		{
			class5947_0.method_14("xmlns", "http://schemas.microsoft.com/xps/2005/06");
			class5947_0.method_14("xmlns:x", "http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key");
		}
		class5947_0.method_14("xml:lang", "en-us");
		class5947_0.method_19("Width", Class6693.smethod_0(width));
		class5947_0.method_19("Height", Class6693.smethod_0(height));
		class5947_0.method_14("Name", $"Page{pageNumber}");
		if (Class5964.smethod_20(class6688_0.Info.GeneratorName) && bool_1)
		{
			class5947_0.XmlWriter.WriteComment($"Generated by {class6688_0.Info.GeneratorName}");
		}
		class5947_0.method_2("Canvas");
		Class6002 @class = new Class6002();
		@class.method_5(1.3333334f, 1.3333334f, MatrixOrder.Prepend);
		class5947_0.method_24("RenderTransform", @class);
	}

	internal void method_1()
	{
		class5947_0.method_3();
		if (bool_1)
		{
			class5947_0.method_1();
		}
		else
		{
			class5947_0.method_3();
		}
	}

	internal void method_2(Class6213 canvas)
	{
		class5947_0.method_2("Canvas");
		if (canvas.Hyperlink != null)
		{
			method_11(canvas.Hyperlink);
			class5947_0.method_14("FixedPage.NavigateUri", method_9(canvas.Hyperlink));
		}
		if (canvas.RenderTransform != null)
		{
			class5947_0.method_24("RenderTransform", canvas.RenderTransform);
		}
		if (!Class6224.smethod_2(canvas))
		{
			return;
		}
		Class6201 @class = new Class6201();
		if (canvas.Clip != null)
		{
			if (canvas.Clip.RenderTransform == null)
			{
				class5947_0.method_14("Clip", @class.method_0(canvas.Clip));
				return;
			}
			class5947_0.method_2("Canvas.Clip");
			class5947_0.method_2("PathGeometry");
			class5947_0.method_24("Transform", canvas.Clip.RenderTransform);
			canvas.Clip.FillMode = FillMode.Alternate;
			class5947_0.method_14("Figures", @class.method_0(canvas.Clip));
			class5947_0.method_3();
			class5947_0.method_3();
		}
	}

	internal void method_3()
	{
		class5947_0.method_3();
	}

	internal void method_4(Class6217 path)
	{
		bool_0 = Class6705.smethod_0(class5947_0, class6688_0, path);
	}

	internal void method_5()
	{
		if (bool_0)
		{
			Class6705.smethod_1(class5947_0);
		}
	}

	internal void method_6(Class6220 imageNode)
	{
		class5947_0.method_2("Path");
		if (imageNode.Hyperlink != null)
		{
			method_11(imageNode.Hyperlink);
			class5947_0.method_14("FixedPage.NavigateUri", method_9(imageNode.Hyperlink));
		}
		Class6217 path = Class6217.smethod_1(new RectangleF(imageNode.Origin, imageNode.Size));
		Class6201 @class = new Class6201();
		class5947_0.method_14("Data", @class.method_0(path));
		if (imageNode.ChromaKey != null)
		{
			method_10(imageNode);
		}
		class5947_0.method_2("Path.Fill");
		Class6692.smethod_1(class5947_0, class6688_0, imageNode.ImageBytes, imageNode.Crop, imageNode.Bounds, WrapMode.Clamp, null);
		class5947_0.method_3();
		class5947_0.method_3();
	}

	internal void method_7(Class6219 glyphs)
	{
		string text = class5947_0.method_17(glyphs.Text, glyphs.Indices != null);
		text = class6688_0.method_1(glyphs.Font.TrueTypeFont, text);
		if (Class5964.smethod_20(text))
		{
			text = (text.StartsWith("{") ? ("{}" + text) : text);
			class5947_0.method_2("Glyphs");
			class5947_0.method_20("OriginX", glyphs.Origin.X);
			class5947_0.method_20("OriginY", glyphs.Origin.Y);
			class5947_0.method_14("UnicodeString", text);
			if (glyphs.Indices != null)
			{
				Class6268 @class = new Class6268(glyphs.Indices);
				class5947_0.method_14("Indices", @class.method_5(glyphs.Font.SizePoints));
			}
			if (glyphs.OutlineColor != Class5998.class5998_141)
			{
				class6688_0.method_2(Enum743.const_2, $"Rendering of Outlined and Embossed text is not supported upon exporting to XPS. Text will be rendered as normal text. Page {int_0}.");
			}
			Class5998 value = ((!glyphs.Color.IsEmpty) ? glyphs.Color : (glyphs.OutlineColor.IsEmpty ? Class5998.class5998_7 : glyphs.OutlineColor));
			class5947_0.method_21("Fill", value);
			class5947_0.method_20("FontRenderingEmSize", glyphs.Font.SizePoints);
			string value2 = class6688_0.vmethod_0(glyphs.Font.TrueTypeFont);
			class5947_0.method_14("FontUri", value2);
			string value3 = smethod_0(glyphs.Font);
			if (Class5964.smethod_20(value3))
			{
				class5947_0.method_14("StyleSimulations", value3);
			}
			if (glyphs.RenderTransform != null)
			{
				class5947_0.method_24("RenderTransform", glyphs.RenderTransform);
			}
			if (glyphs.Clip != null)
			{
				Class6201 class2 = new Class6201();
				class5947_0.method_14("Clip", class2.method_0(glyphs.Clip));
			}
			if (glyphs.Hyperlink != null && glyphs.Hyperlink.HyperlinkType == Enum802.const_0)
			{
				method_11(glyphs.Hyperlink);
				class5947_0.method_14("FixedPage.NavigateUri", method_9(glyphs.Hyperlink));
			}
			class5947_0.method_3();
		}
	}

	internal void method_8(string bookmarkName, PointF bookmarkOrigin)
	{
		class5947_0.method_2("Path");
		class5947_0.method_14("Name", bookmarkName);
		string value = $"M {Class6159.smethod_43(bookmarkOrigin.X)},{Class6159.smethod_43(bookmarkOrigin.Y)}";
		class5947_0.method_14("Data", value);
		class5947_0.method_21("Fill", Class5998.class5998_141);
		class5947_0.method_3();
	}

	private static string smethod_0(Class5999 font)
	{
		string result = string.Empty;
		if (font.TrueTypeFont.Style != font.Style)
		{
			if (font.IsBold && font.IsItalic)
			{
				result = "BoldItalicSimulation";
			}
			else if (font.IsBold)
			{
				result = "BoldSimulation";
			}
			else if (font.IsItalic)
			{
				result = "ItalicSimulation";
			}
		}
		return result;
	}

	private string method_9(Class6270 hyperlink)
	{
		if (!hyperlink.IsLocal)
		{
			return hyperlink.Target;
		}
		return string.Format(bool_1 ? "../FixedDocument.fdoc#{0}" : "#{0}", class6688_0.method_0(hyperlink.Target));
	}

	private void method_10(Class6220 imageNode)
	{
		class5947_0.method_2("Path.OpacityMask");
		using (Class6150 @class = new Class6150(imageNode.ImageBytes))
		{
			@class.method_18(imageNode.ChromaKey);
			using MemoryStream memoryStream = new MemoryStream();
			@class.Save(memoryStream, Enum788.const_5);
			Class6692.smethod_1(class5947_0, class6688_0, memoryStream.ToArray(), imageNode.Crop, imageNode.Bounds, WrapMode.Clamp, null);
		}
		class5947_0.method_3();
	}

	private void method_11(Class6270 hyperlink)
	{
		if (Class5973.smethod_7(hyperlink.Target))
		{
			class6688_0.method_2(Enum743.const_3, $"Hyperlinks to local resources can crash XPS viewer. This is a bug in XPS viewer. Page {int_0}.");
		}
	}
}
