using System.Data.Entity.Edm.Db;
using System.Data.Entity.Edm.Serialization;
using System.Data.Entity.Infrastructure;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Xml;

namespace System.Data.Entity.Internal;

/// <summary>
/// Calculates the model hash values used the EdmMetadata table from EF 4.1/4.2.
/// </summary>
internal class ModelHashCalculator
{
	/// <summary>
	/// Calculates an SHA256 hash of the EDMX from the given code first model. This is the hash stored in
	/// the database in the EdmMetadata table in EF 4.1/4.2. The hash is always calculated using a v2 schema
	/// as was generated by EF 4.1/4.2 and with the <see cref="T:System.Data.Entity.Infrastructure.EdmMetadata" /> entity included in the model.
	/// </summary>
	public virtual string Calculate(DbCompiledModel compiledModel)
	{
		DbProviderInfo providerInfo = compiledModel.ProviderInfo;
		DbModelBuilder dbModelBuilder = compiledModel.CachedModelBuilder.Clone();
		EdmMetadataContext.ConfigureEdmMetadata(dbModelBuilder.ModelConfiguration);
		DbDatabaseMetadata database = dbModelBuilder.Build(providerInfo).DatabaseMapping.Database;
		database.Version = 2.0;
		StringBuilder stringBuilder = new StringBuilder();
		using (XmlWriter xmlWriter = XmlWriter.Create(stringBuilder, new XmlWriterSettings
		{
			Indent = true
		}))
		{
			new SsdlSerializer().Serialize(database, providerInfo.ProviderInvariantName, providerInfo.ProviderManifestToken, xmlWriter);
		}
		return ComputeSha256Hash(stringBuilder.ToString());
	}

	private static string ComputeSha256Hash(string input)
	{
		byte[] array = GetSha256HashAlgorithm().ComputeHash(Encoding.ASCII.GetBytes(input));
		StringBuilder stringBuilder = new StringBuilder(array.Length * 2);
		byte[] array2 = array;
		foreach (byte b in array2)
		{
			stringBuilder.Append(b.ToString("X2", CultureInfo.InvariantCulture));
		}
		return stringBuilder.ToString();
	}

	private static SHA256 GetSha256HashAlgorithm()
	{
		try
		{
			return new SHA256CryptoServiceProvider();
		}
		catch (PlatformNotSupportedException)
		{
			return new SHA256Managed();
		}
	}
}
