namespace Aspose.Words.BuildingBlocks;

public enum BuildingBlockGallery
{
	All = 0,
	AutoText = 1,
	Bibliography = 2,
	CoverPage = 3,
	CustomAutoText = 4,
	CustomBibliography = 5,
	CustomCoverPage = 6,
	CustomEquations = 7,
	CustomFooters = 8,
	CustomHeaders = 9,
	Custom1 = 10,
	Custom2 = 11,
	Custom3 = 12,
	Custom4 = 13,
	Custom5 = 14,
	CustomPageNumber = 15,
	CustomPageNumberAtBottom = 16,
	CustomPageNumberAtMargin = 17,
	CustomPageNumberAtTop = 18,
	CustomQuickParts = 19,
	CustomTableOfContents = 20,
	CustomTables = 21,
	CustomTextBox = 22,
	CustomWatermarks = 23,
	NoGallery = 24,
	QuickParts = 25,
	Equations = 26,
	Footers = 27,
	Headers = 28,
	PageNumber = 29,
	PageNumberAtBottom = 30,
	PageNumberAtMargin = 31,
	PageNumberAtTop = 32,
	StructuredDocumentTagPlaceholderText = 33,
	TableOfContents = 34,
	Tables = 35,
	TextBox = 36,
	Watermarks = 37,
	Default = 0
}
