using System.Runtime.InteropServices;

namespace Aspose.Slides;

[Guid("fd6e8570-9907-48ce-bce5-7847f101cabb")]
[ComVisible(true)]
public enum PatternStyle : sbyte
{
	NotDefined = -1,
	Unknown,
	Percent05,
	Percent10,
	Percent20,
	Percent25,
	Percent30,
	Percent40,
	Percent50,
	Percent60,
	Percent70,
	Percent75,
	Percent80,
	Percent90,
	DarkHorizontal,
	DarkVertical,
	DarkDownwardDiagonal,
	DarkUpwardDiagonal,
	SmallCheckerBoard,
	Trellis,
	LightHorizontal,
	LightVertical,
	LightDownwardDiagonal,
	LightUpwardDiagonal,
	SmallGrid,
	DottedDiamond,
	WideDownwardDiagonal,
	WideUpwardDiagonal,
	DashedDownwardDiagonal,
	DashedUpwardDiagonal,
	NarrowVertical,
	NarrowHorizontal,
	DashedVertical,
	DashedHorizontal,
	LargeConfetti,
	LargeGrid,
	HorizontalBrick,
	LargeCheckerBoard,
	SmallConfetti,
	Zigzag,
	SolidDiamond,
	DiagonalBrick,
	OutlinedDiamond,
	Plaid,
	Sphere,
	Weave,
	DottedGrid,
	Divot,
	Shingle,
	Wave,
	Horizontal,
	Vertical,
	Cross,
	DownwardDiagonal,
	UpwardDiagonal,
	DiagonalCross
}
