using System.Runtime.InteropServices;

namespace Aspose.Slides.Animation;

[ComVisible(true)]
[Guid("50d9388f-fe47-4934-bbf9-6e63c4950eb4")]
public enum PropertyType
{
	NotDefined = -1,
	Color,
	PptHeight,
	Opacity,
	Rotation,
	RotationPPT,
	ShapeStrokeColor,
	StrokeOn,
	ShapeFillType,
	ShapeFillBackColor,
	ShapeFillColor,
	ShapeFillColor2,
	ShapeFillOn,
	ShapeFillOpacity,
	ShapeLineColor,
	ShapeLineOn,
	ShapePictureBrightness,
	ShapePictureContrast,
	ShapePictureGamma,
	ShapePictureGrayscale,
	ShapeShadowColor,
	ShapeShadowOffsetX,
	ShapeShadowOffsetY,
	ShapeShadowOn,
	ShapeShadowOpacity,
	ShapeShadowType,
	TextBulletCharacter,
	TextBulletColor,
	TextBulletFontName,
	TextBulletNumber,
	TextBulletRelativeSize,
	TextBulletStyle,
	TextBulletType,
	TextFontBold,
	TextFontColor,
	TextFontEmboss,
	TextFontItalic,
	TextFontName,
	TextFontShadow,
	TextFontSize,
	TextFontStyle,
	TextFontWeight,
	TextFontStrikeThrough,
	TextFontSubscript,
	TextFontSuperscript,
	TextFontUnderline,
	Visibility,
	PptWidth,
	PptX,
	PptY,
	XShear
}
