using System.Runtime.InteropServices;

namespace Microsoft.Office.Interop.Visio;

[TypeLibType(16)]
[Guid("000D0C19-0000-0000-C000-000000000046")]
public enum tagVisEventCodes
{
	visEvtIDInval = -1,
	visScopeIDInval = -1,
	visEvtCodeInval = 0,
	visEvtCodeDocCreate = 1,
	visEvtCodeDocOpen = 2,
	visEvtCodeDocSave = 3,
	visEvtCodeDocSaveAs = 4,
	visEvtCodeDocRunning = 5,
	visEvtCodeDocDesign = 6,
	visEvtCodeBefDocSave = 7,
	visEvtCodeBefDocSaveAs = 8,
	visEvtCodeQueryCancelDocClose = 9,
	visEvtCodeCancelDocClose = 10,
	visEvtCodeBefForcedFlush = 200,
	visEvtCodeAfterForcedFlush = 201,
	visEvtCodeEnterScope = 202,
	visEvtCodeExitScope = 203,
	visEvtCodeQueryCancelQuit = 204,
	visEvtCodeCancelQuit = 205,
	visEvtCodeQueryCancelSuspend = 206,
	visEvtCodeCancelSuspend = 207,
	visEvtCodeBeforeSuspend = 208,
	visEvtCodeAfterResume = 209,
	visEvtCodeQueryCancelStyleDel = 300,
	visEvtCodeCancelStyleDel = 301,
	visEvtCodeQueryCancelMasterDel = 400,
	visEvtCodeCancelMasterDel = 401,
	visEvtCodeQueryCancelPageDel = 500,
	visEvtCodeCancelPageDel = 501,
	visEvtCodeWinSelChange = 701,
	visEvtCodeBefWinSelDel = 702,
	visEvtCodeBefWinPageTurn = 703,
	visEvtCodeWinPageTurn = 704,
	visEvtCodeViewChanged = 705,
	visEvtCodeQueryCancelWinClose = 706,
	visEvtCodeCancelWinClose = 707,
	visEvtCodeWinOnAddonKeyMSG = 708,
	visEvtCodeShapeDelete = 801,
	visEvtCodeShapeParentChange = 802,
	visEvtCodeShapeBeforeTextEdit = 803,
	visEvtCodeShapeExitTextEdit = 804,
	visEvtCodeBefSelDel = 901,
	visEvtCodeSelAdded = 902,
	visEvtCodeQueryCancelSelDel = 903,
	visEvtCodeCancelSelDel = 904,
	visEvtCodeQueryCancelUngroup = 905,
	visEvtCodeCancelUngroup = 906,
	visEvtCodeQueryCancelConvertToGroup = 907,
	visEvtCodeCancelConvertToGroup = 908,
	visEvtAdd = 32768,
	visEvtDel = 16384,
	visEvtMod = 8192,
	visEvtWindow = 1,
	visEvtDoc = 2,
	visEvtStyle = 4,
	visEvtMaster = 8,
	visEvtPage = 16,
	[TypeLibVar(64)]
	visEvtLayer = 32,
	visEvtShape = 64,
	visEvtText = 128,
	visEvtConnect = 256,
	visEvtSection = 512,
	visEvtRow = 1024,
	visEvtCell = 2048,
	visEvtFormula = 4096,
	visEvtApp = 4096,
	visEvtAppActivate = 1,
	visEvtAppDeactivate = 2,
	visEvtObjActivate = 4,
	visEvtObjDeactivate = 8,
	visEvtBeforeQuit = 16,
	visEvtBeforeModal = 32,
	visEvtAfterModal = 64,
	visEvtWinActivate = 128,
	visEvtMarker = 256,
	visEvtNonePending = 512,
	visEvtIdle = 1024,
	[TypeLibVar(64)]
	visEvtCode1stUser = 28672,
	[TypeLibVar(64)]
	visEvtCodeLastUser = 32767,
	[TypeLibVar(64)]
	visEvtCodeCreate = 1,
	[TypeLibVar(64)]
	visEvtCodeOpen = 2,
	visActCodeRunAddon = 1,
	visActCodeAdvise = 2,
	visEvtIdMostRecent = 0,
	visEvtCodeMouseDown = 709,
	visEvtCodeMouseMove = 710,
	visEvtCodeMouseUp = 711,
	visEvtCodeKeyDown = 712,
	visEvtCodeKeyPress = 713,
	visEvtCodeKeyUp = 714,
	visEvtDataRecordset = 32,
	visEvtShapeLinkAdded = 805,
	visEvtShapeLinkDeleted = 806,
	visEvtShapeDataGraphicChanged = 807,
	visEvtCodeQueryCancelSelGroup = 909,
	visEvtCodeCancelSelGroup = 910,
	visEvtRemoveHiddenInformation = 11,
	visEvtCodeQueryCancelSuspendEvents = 210,
	visEvtCodeCancelSuspendEvents = 211,
	visEvtCodeBeforeSuspendEvents = 212,
	visEvtCodeAfterResumeEvents = 213,
	visEvtCodeContainerRelationshipAdded = 502,
	visEvtCodeContainerRelationshipDeleted = 503,
	visEvtCodeCalloutRelationshipAdded = 504,
	visEvtCodeCalloutRelationshipDeleted = 505,
	visEvtCodeSelectionMovedToSubprocess = 12,
	visEvtCodeRuleSetValidated = 13,
	visEvtCodeQueryCancelReplaceShapes = 911,
	visEvtCodeCancelReplaceShapes = 912,
	visEvtCodeBeforeReplaceShapes = 913,
	visEvtCodeShapesReplaced = 914,
	visEvtCodeAfterCoauthMerge = 14
}
