using System.Runtime.InteropServices;

namespace Microsoft.Office.Interop.Visio;

[TypeLibType(16)]
[Guid("000D0C1D-0000-0000-C000-000000000046")]
public enum tagVisFieldFormats
{
	visFmtNumGenNoUnits = 0,
	visFmtNumGenDefUnits = 1,
	visFmt0PlNoUnits = 2,
	visFmt0PlDefUnits = 3,
	visFmt1PlNoUnits = 4,
	visFmt1PlDefUnits = 5,
	visFmt2PlNoUnits = 6,
	visFmt2PlDefUnits = 7,
	visFmt3PlNoUnits = 8,
	visFmt3PlDefUnits = 9,
	visFmtFeetAndInches = 10,
	visFmtRadians = 11,
	visFmtDegrees = 12,
	visFmtFeetAndInches1Pl = 13,
	visFmtFeetAndInches2Pl = 14,
	visFmtFraction1PlNoUnits = 15,
	visFmtFraction1PlDefUnits = 16,
	visFmtFraction2PlNoUnits = 17,
	visFmtFraction2PlDefUnits = 18,
	visFmtDateShort = 20,
	visFmtDateLong = 21,
	visFmtDateMDYY = 22,
	visFmtDateMMDDYY = 23,
	visFmtDateMmmDYYYY = 24,
	visFmtDateMmmmDYYYY = 25,
	visFmtDateDMYY = 26,
	visFmtDateDDMMYY = 27,
	visFmtDateDMMMYYYY = 28,
	visFmtDateDMMMMYYYY = 29,
	visFmtTimeGen = 30,
	visFmtTimeHMM = 31,
	visFmtTimeHHMM = 32,
	visFmtTimeHMM24 = 33,
	visFmtTimeHHMM24 = 34,
	visFmtTimeHMMAMPM = 35,
	visFmtTimeHHMMAMPM = 36,
	visFmtStrNormal = 37,
	visFmtStrLower = 38,
	visFmtStrUpper = 39,
	[TypeLibVar(64)]
	visFmtJDategggeXmXdXww = 40,
	[TypeLibVar(64)]
	visFmtJDateyyyyXmXdXww = 41,
	[TypeLibVar(64)]
	visFmtJDategggeXmXdX = 42,
	[TypeLibVar(64)]
	visFmtJDateyyyyXmXdX = 43,
	[TypeLibVar(64)]
	visFmtJDateyyyymd = 44,
	[TypeLibVar(64)]
	visFmtJDateyymmdd = 45,
	[TypeLibVar(64)]
	visFmtJDatehmmaxpx = 46,
	[TypeLibVar(64)]
	visFmtJDateaxpxhmm = 47,
	[TypeLibVar(64)]
	visFmtJDateaxpxhXmmX = 48,
	[TypeLibVar(64)]
	visFmtJDatehXmmX = 49,
	[TypeLibVar(64)]
	visFmtCDateiiieXmmmmXdddd = 50,
	[TypeLibVar(64)]
	visFmtCDateiieXmmmmXdddd = 51,
	[TypeLibVar(64)]
	visFmtCDateieXmmmmXddddXww = 52,
	[TypeLibVar(64)]
	visFmtCDateieXmmmmXdddd = 53,
	visFmtDateyyyymd = 44,
	visFmtDateyymmdd = 45,
	visFmtTimeAMPMhmm_J = 46,
	visFmtDateTWNfYYYYMMDDD_C = 50,
	visFmtDateTWNsYYYYMMDDD_C = 51,
	visFmtDateTWNfyyyymmddww_C = 52,
	visFmtDateTWNfyyyymmdd_C = 53,
	visFmtDategggemdww_J = 54,
	visFmtDateyyyymdww_J = 55,
	visFmtDategggemd_J = 56,
	visFmtDateyyyymd_J = 57,
	visFmtDateYYYYMMMDDDWWW_C = 58,
	visFmtDateYYYYMMMDDD_C = 59,
	visFmtDategeMMMMddddww_K = 60,
	visFmtDateyyyymdww_K = 61,
	visFmtDategeMMMMddd_K = 62,
	visFmtDateyyyymd_K = 63,
	visFmtDateyyyy_m_d = 64,
	visFmtDateyy_mm_dd = 65,
	visFmtTimeAMPMhmm_C = 66,
	visFmtTimeAMPMhmm_K = 67,
	visFmtTimeAMPM_hmm_J = 68,
	visFmtTimehmm_J = 69,
	visFmtTimeAMPM_hmm_C = 70,
	visFmtTimehmm_C = 71,
	visFmtTimeAMPM_hmm_K = 72,
	visFmtTimehmm_K = 73,
	visFmtTimeHMMAMPM_E = 74,
	visFmtTimeHHMMAMPM_E = 75,
	visFmtDateyyyymd_S = 76,
	visFmtDateyyyymmdd_S = 77,
	visFmtDatewwyyyymmdd_S = 78,
	visFmtDatewwyyyymd_S = 79,
	visFmtTimeAMPMhmm_S = 80,
	visFmtTimeAMPMhhmm_S = 81,
	visFmtMsoDateShort = 200,
	visFmtMsoDateLongDay = 201,
	visFmtMsoDateLong = 202,
	visFmtMsoDateShortAlt = 203,
	visFmtMsoDateISO = 204,
	visFmtMsoDateShortMon = 205,
	visFmtMsoDateShortSlash = 206,
	visFmtMsoDateShortAbb = 207,
	visFmtMsoDateEnglish = 208,
	visFmtMsoDateMonthYr = 209,
	visFmtMsoDateMon_Yr = 210,
	visFmtMsoTimeDatePM = 211,
	visFmtMsoTimeDateSecPM = 212,
	visFmtMsoTimePM = 213,
	visFmtMsoTimeSecPM = 214,
	visFmtMsoTime24 = 215,
	visFmtMsoTimeSec24 = 216,
	visFmtMsoFEExtra1 = 217,
	visFmtMsoFEExtra2 = 218,
	visFmtMsoFEExtra3 = 219,
	visFmtMsoFEExtra4 = 220,
	visFmtMsoFEExtra5 = 221
}
