using System.Runtime.InteropServices;

namespace Microsoft.Office.Interop.Visio;

[TypeLibType(16)]
[Guid("000D0C1A-0000-0000-C000-000000000046")]
public enum tagVisObjectTypes
{
	visObjTypeUnknown = 1,
	visObjTypeApp = 3,
	visObjTypeCell = 4,
	visObjTypeChars = 5,
	visObjTypeConnect = 8,
	visObjTypeConnects = 9,
	visObjTypeDoc = 10,
	visObjTypeDocs = 11,
	visObjTypeMaster = 12,
	visObjTypeMasters = 13,
	visObjTypePage = 14,
	visObjTypePages = 15,
	visObjTypeSelection = 16,
	visObjTypeShape = 17,
	visObjTypeShapes = 18,
	visObjTypeStyle = 19,
	visObjTypeStyles = 20,
	visObjTypeWindow = 21,
	visObjTypeWindows = 22,
	visObjTypeLayer = 25,
	visObjTypeLayers = 26,
	visObjTypeFont = 27,
	visObjTypeFonts = 28,
	visObjTypeColor = 29,
	visObjTypeColors = 30,
	visObjTypeAddon = 31,
	visObjTypeAddons = 32,
	visObjTypeEvent = 33,
	visObjTypeEventList = 34,
	visObjTypeGlobal = 36,
	visObjTypeHyperlink = 37,
	visObjTypeOLEObjects = 38,
	visObjTypeOLEObject = 39,
	visObjTypePaths = 40,
	visObjTypePath = 41,
	visObjTypeCurve = 42,
	visObjTypeHyperlinks = 43,
	visObjTypeSection = 44,
	visObjTypeRow = 45,
	visObjTypeMasterShortcuts = 46,
	visObjTypeMasterShortcut = 47,
	visObjTypeMSGWrap = 48,
	visObjTypeMouseEvent = 49,
	visObjTypeKeyboardEvent = 50,
	visObjTypeApplicationSettings = 51,
	visObjTypeDataRecordsets = 52,
	visObjTypeDataRecordset = 53,
	visObjTypeDataConnection = 54,
	visObjTypeDataColumns = 55,
	visObjTypeDataColumn = 56,
	visObjTypeDataRecordsetChangedEvent = 57,
	visObjTypeGraphicItems = 58,
	visObjTypeGraphicItem = 59,
	visObjTypeContainerProperties = 60,
	visObjTypeRelatedShapePairEvent = 61,
	visObjTypeMovedSelectionEvent = 62,
	visObjTypeServerPublishOptions = 63,
	visObjTypeValidation = 64,
	visObjTypeValidationRuleSets = 65,
	visObjTypeValidationRuleSet = 66,
	visObjTypeValidationRules = 67,
	visObjTypeValidationRule = 68,
	visObjTypeValidationIssues = 69,
	visObjTypeValidationIssue = 70,
	visObjTypeReplaceShapesEvent = 71,
	visObjTypeComments = 73,
	visObjTypeComment = 74
}
