using System.Drawing;
using Aspose.Slides;
using Aspose.Slides.Theme;

namespace ns4;

internal class Class1075
{
	internal static void smethod_0(IMasterTheme theme)
	{
		theme.Name = "Office Theme";
		((ColorScheme)theme.ColorScheme).Name = "Office";
		((ColorFormat)theme.ColorScheme[ColorSchemeIndex.Dark1]).method_10(SystemColor.WindowText, Color.FromArgb(0));
		((ColorFormat)theme.ColorScheme[ColorSchemeIndex.Light1]).method_10(SystemColor.Window, Color.FromArgb(16777215));
		theme.ColorScheme[ColorSchemeIndex.Dark2].Color = Color.FromArgb(-14726787);
		theme.ColorScheme[ColorSchemeIndex.Light2].Color = Color.FromArgb(-1119007);
		theme.ColorScheme[ColorSchemeIndex.Accent1].Color = Color.FromArgb(-11566659);
		theme.ColorScheme[ColorSchemeIndex.Accent2].Color = Color.FromArgb(-4173747);
		theme.ColorScheme[ColorSchemeIndex.Accent3].Color = Color.FromArgb(-6571175);
		theme.ColorScheme[ColorSchemeIndex.Accent4].Color = Color.FromArgb(-8362846);
		theme.ColorScheme[ColorSchemeIndex.Accent5].Color = Color.FromArgb(-11817786);
		theme.ColorScheme[ColorSchemeIndex.Accent6].Color = Color.FromArgb(-551354);
		theme.ColorScheme[ColorSchemeIndex.Hyperlink].Color = Color.FromArgb(-16776961);
		theme.ColorScheme[ColorSchemeIndex.FollowedHyperlink].Color = Color.FromArgb(-8388480);
		theme.FontScheme.Name = "Office";
		Fonts fonts = (Fonts)theme.FontScheme.Major;
		fonts.LatinFont = new FontData("Calibri");
		fonts.EastAsianFont = new FontData("");
		fonts.ComplexScriptFont = new FontData("");
		fonts.PPTXUnsupportedProps.method_0("Jpan", "ＭＳ%20Ｐゴシック");
		fonts.PPTXUnsupportedProps.method_0("Hang", "맑은%20고딕");
		fonts.PPTXUnsupportedProps.method_0("Hans", "宋体");
		fonts.PPTXUnsupportedProps.method_0("Hant", "新細明體");
		fonts.PPTXUnsupportedProps.method_0("Arab", "Times New Roman");
		fonts.PPTXUnsupportedProps.method_0("Hebr", "Times New Roman");
		fonts.PPTXUnsupportedProps.method_0("Thai", "Angsana New");
		fonts.PPTXUnsupportedProps.method_0("Ethi", "Nyala");
		fonts.PPTXUnsupportedProps.method_0("Beng", "Vrinda");
		fonts.PPTXUnsupportedProps.method_0("Gujr", "Shruti");
		fonts.PPTXUnsupportedProps.method_0("Khmr", "MoolBoran");
		fonts.PPTXUnsupportedProps.method_0("Knda", "Tunga");
		fonts.PPTXUnsupportedProps.method_0("Guru", "Raavi");
		fonts.PPTXUnsupportedProps.method_0("Cans", "Euphemia");
		fonts.PPTXUnsupportedProps.method_0("Cher", "Plantagenet Cherokee");
		fonts.PPTXUnsupportedProps.method_0("Yiii", "Microsoft Yi Baiti");
		fonts.PPTXUnsupportedProps.method_0("Tibt", "Microsoft Himalaya");
		fonts.PPTXUnsupportedProps.method_0("Thaa", "MV Boli");
		fonts.PPTXUnsupportedProps.method_0("Deva", "Mangal");
		fonts.PPTXUnsupportedProps.method_0("Telu", "Gautami");
		fonts.PPTXUnsupportedProps.method_0("Taml", "Latha");
		fonts.PPTXUnsupportedProps.method_0("Syrc", "Estrangelo Edessa");
		fonts.PPTXUnsupportedProps.method_0("Orya", "Kalinga");
		fonts.PPTXUnsupportedProps.method_0("Mlym", "Kartika");
		fonts.PPTXUnsupportedProps.method_0("Laoo", "DokChampa");
		fonts.PPTXUnsupportedProps.method_0("Sinh", "Iskoola Pota");
		fonts.PPTXUnsupportedProps.method_0("Mong", "Mongolian Baiti");
		fonts.PPTXUnsupportedProps.method_0("Viet", "Times New Roman");
		fonts.PPTXUnsupportedProps.method_0("Uigh", "Microsoft Uighur");
		fonts.PPTXUnsupportedProps.method_0("Geor", "Sylfaen");
		Fonts fonts2 = (Fonts)theme.FontScheme.Minor;
		fonts2.LatinFont = new FontData("Calibri");
		fonts2.EastAsianFont = new FontData("");
		fonts2.ComplexScriptFont = new FontData("");
		fonts2.PPTXUnsupportedProps.method_0("Jpan", "ＭＳ%20Ｐゴシック");
		fonts2.PPTXUnsupportedProps.method_0("Hang", "맑은%20고딕");
		fonts2.PPTXUnsupportedProps.method_0("Hans", "宋体");
		fonts2.PPTXUnsupportedProps.method_0("Hant", "新細明體");
		fonts2.PPTXUnsupportedProps.method_0("Arab", "Arial");
		fonts2.PPTXUnsupportedProps.method_0("Hebr", "Arial");
		fonts2.PPTXUnsupportedProps.method_0("Thai", "Cordia New");
		fonts2.PPTXUnsupportedProps.method_0("Ethi", "Nyala");
		fonts2.PPTXUnsupportedProps.method_0("Beng", "Vrinda");
		fonts2.PPTXUnsupportedProps.method_0("Gujr", "Shruti");
		fonts2.PPTXUnsupportedProps.method_0("Khmr", "DaunPenh");
		fonts2.PPTXUnsupportedProps.method_0("Knda", "Tunga");
		fonts2.PPTXUnsupportedProps.method_0("Guru", "Raavi");
		fonts2.PPTXUnsupportedProps.method_0("Cans", "Euphemia");
		fonts2.PPTXUnsupportedProps.method_0("Cher", "Plantagenet Cherokee");
		fonts2.PPTXUnsupportedProps.method_0("Yiii", "Microsoft Yi Baiti");
		fonts2.PPTXUnsupportedProps.method_0("Tibt", "Microsoft Himalaya");
		fonts2.PPTXUnsupportedProps.method_0("Thaa", "MV Boli");
		fonts2.PPTXUnsupportedProps.method_0("Deva", "Mangal");
		fonts2.PPTXUnsupportedProps.method_0("Telu", "Gautami");
		fonts2.PPTXUnsupportedProps.method_0("Taml", "Latha");
		fonts2.PPTXUnsupportedProps.method_0("Syrc", "Estrangelo Edessa");
		fonts2.PPTXUnsupportedProps.method_0("Orya", "Kalinga");
		fonts2.PPTXUnsupportedProps.method_0("Mlym", "Kartika");
		fonts2.PPTXUnsupportedProps.method_0("Laoo", "DokChampa");
		fonts2.PPTXUnsupportedProps.method_0("Sinh", "Iskoola Pota");
		fonts2.PPTXUnsupportedProps.method_0("Mong", "Mongolian Baiti");
		fonts2.PPTXUnsupportedProps.method_0("Viet", "Arial");
		fonts2.PPTXUnsupportedProps.method_0("Uigh", "Microsoft Uighur");
		fonts2.PPTXUnsupportedProps.method_0("Geor", "Sylfaen");
		((FormatScheme)theme.FormatScheme).Name = "Office";
		IFillFormat fillFormat = ((FillFormatCollection)theme.FormatScheme.FillStyles).Add();
		fillFormat.FillType = FillType.Solid;
		fillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		fillFormat = ((FillFormatCollection)theme.FormatScheme.FillStyles).Add();
		fillFormat.RotateWithShape = NullableBool.True;
		fillFormat.FillType = FillType.Gradient;
		fillFormat.GradientFormat.GradientShape = GradientShape.Linear;
		fillFormat.GradientFormat.LinearGradientAngle = 270f;
		fillFormat.GradientFormat.LinearGradientScaled = NullableBool.True;
		ColorFormat colorFormat = new ColorFormat(((FillFormat)fillFormat).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat.ColorTransform.Add(ColorTransformOperation.Tint, 0.5f);
		colorFormat.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3f);
		((GradientStopCollection)fillFormat.GradientFormat.GradientStops).Add(0f, colorFormat);
		colorFormat = new ColorFormat(((FillFormat)fillFormat).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat.ColorTransform.Add(ColorTransformOperation.Tint, 0.37f);
		colorFormat.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3f);
		((GradientStopCollection)fillFormat.GradientFormat.GradientStops).Add(0.35f, colorFormat);
		colorFormat = new ColorFormat(((FillFormat)fillFormat).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat.ColorTransform.Add(ColorTransformOperation.Tint, 0.15f);
		colorFormat.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3.5f);
		((GradientStopCollection)fillFormat.GradientFormat.GradientStops).Add(1f, colorFormat);
		fillFormat = ((FillFormatCollection)theme.FormatScheme.FillStyles).Add();
		fillFormat.RotateWithShape = NullableBool.True;
		fillFormat.FillType = FillType.Gradient;
		fillFormat.GradientFormat.GradientShape = GradientShape.Linear;
		fillFormat.GradientFormat.LinearGradientAngle = 270f;
		fillFormat.GradientFormat.LinearGradientScaled = NullableBool.False;
		colorFormat = new ColorFormat(((FillFormat)fillFormat).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat.ColorTransform.Add(ColorTransformOperation.Shade, 0.51f);
		colorFormat.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.3f);
		((GradientStopCollection)fillFormat.GradientFormat.GradientStops).Add(0f, colorFormat);
		colorFormat = new ColorFormat(((FillFormat)fillFormat).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat.ColorTransform.Add(ColorTransformOperation.Shade, 0.93f);
		colorFormat.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.3f);
		((GradientStopCollection)fillFormat.GradientFormat.GradientStops).Add(0.8f, colorFormat);
		colorFormat = new ColorFormat(((FillFormat)fillFormat).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat.ColorTransform.Add(ColorTransformOperation.Shade, 0.94f);
		colorFormat.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.35f);
		((GradientStopCollection)fillFormat.GradientFormat.GradientStops).Add(1f, colorFormat);
		LineFormat lineFormat = new LineFormat(theme.FormatScheme);
		lineFormat.FillFormat.FillType = FillType.Solid;
		lineFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		lineFormat.FillFormat.SolidFillColor.ColorTransform.Add(ColorTransformOperation.Shade, 0.95f);
		lineFormat.FillFormat.SolidFillColor.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.05f);
		lineFormat.DashStyle = LineDashStyle.Solid;
		lineFormat.Width = 0.75;
		lineFormat.CapStyle = LineCapStyle.Flat;
		lineFormat.Style = LineStyle.Single;
		lineFormat.Alignment = LineAlignment.Center;
		((LineFormatCollection)theme.FormatScheme.LineStyles).Add(lineFormat);
		lineFormat = new LineFormat(theme.FormatScheme);
		lineFormat.FillFormat.FillType = FillType.Solid;
		lineFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		lineFormat.DashStyle = LineDashStyle.Solid;
		lineFormat.Width = 2.0;
		lineFormat.CapStyle = LineCapStyle.Flat;
		lineFormat.Style = LineStyle.Single;
		lineFormat.Alignment = LineAlignment.Center;
		((LineFormatCollection)theme.FormatScheme.LineStyles).Add(lineFormat);
		lineFormat = new LineFormat(theme.FormatScheme);
		lineFormat.FillFormat.FillType = FillType.Solid;
		lineFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		lineFormat.DashStyle = LineDashStyle.Solid;
		lineFormat.Width = 3.0;
		lineFormat.CapStyle = LineCapStyle.Flat;
		lineFormat.Style = LineStyle.Single;
		lineFormat.Alignment = LineAlignment.Center;
		((LineFormatCollection)theme.FormatScheme.LineStyles).Add(lineFormat);
		IEffectStyle effectStyle = ((EffectStyleCollection)theme.FormatScheme.EffectStyles).Add();
		effectStyle.EffectFormat.EnableOuterShadowEffect();
		effectStyle.EffectFormat.OuterShadowEffect.BlurRadius = 3.1496062992125986;
		effectStyle.EffectFormat.OuterShadowEffect.Direction = 90f;
		effectStyle.EffectFormat.OuterShadowEffect.Distance = 1.5748031496062993;
		effectStyle.EffectFormat.OuterShadowEffect.ShadowColor.ColorType = ColorType.RGB;
		effectStyle.EffectFormat.OuterShadowEffect.ShadowColor.ColorTransform.Add(ColorTransformOperation.SetAlpha, 0.38f);
		effectStyle.EffectFormat.OuterShadowEffect.RotateShadowWithShape = false;
		effectStyle = ((EffectStyleCollection)theme.FormatScheme.EffectStyles).Add();
		effectStyle.EffectFormat.EnableOuterShadowEffect();
		effectStyle.EffectFormat.OuterShadowEffect.BlurRadius = 3.1496062992125986;
		effectStyle.EffectFormat.OuterShadowEffect.Direction = 90f;
		effectStyle.EffectFormat.OuterShadowEffect.Distance = 1.811023622047244;
		effectStyle.EffectFormat.OuterShadowEffect.ShadowColor.ColorType = ColorType.RGB;
		effectStyle.EffectFormat.OuterShadowEffect.ShadowColor.ColorTransform.Add(ColorTransformOperation.SetAlpha, 0.35f);
		effectStyle.EffectFormat.OuterShadowEffect.RotateShadowWithShape = false;
		effectStyle = ((EffectStyleCollection)theme.FormatScheme.EffectStyles).Add();
		effectStyle.EffectFormat.EnableOuterShadowEffect();
		effectStyle.EffectFormat.OuterShadowEffect.BlurRadius = 3.1496062992125986;
		effectStyle.EffectFormat.OuterShadowEffect.Direction = 90f;
		effectStyle.EffectFormat.OuterShadowEffect.Distance = 1.811023622047244;
		effectStyle.EffectFormat.OuterShadowEffect.ShadowColor.ColorType = ColorType.RGB;
		effectStyle.EffectFormat.OuterShadowEffect.ShadowColor.ColorTransform.Add(ColorTransformOperation.SetAlpha, 0.35f);
		effectStyle.EffectFormat.OuterShadowEffect.RotateShadowWithShape = false;
		effectStyle.ThreeDFormat.Material = MaterialPresetType.WarmMatte;
		effectStyle.ThreeDFormat.BevelTop.Width = 5.0;
		effectStyle.ThreeDFormat.BevelTop.Height = 2.0;
		effectStyle.ThreeDFormat.BevelTop.BevelType = BevelPresetType.Circle;
		effectStyle.ThreeDFormat.Camera.CameraType = CameraPresetType.OrthographicFront;
		effectStyle.ThreeDFormat.Camera.SetRotation(0f, 0f, 0f);
		effectStyle.ThreeDFormat.LightRig.Direction = LightingDirection.Top;
		effectStyle.ThreeDFormat.LightRig.LightType = LightRigPresetType.ThreePt;
		effectStyle.ThreeDFormat.LightRig.SetRotation(0f, 0f, 20f);
		IFillFormat fillFormat2 = ((FillFormatCollection)theme.FormatScheme.BackgroundFillStyles).Add();
		fillFormat2.FillType = FillType.Solid;
		fillFormat2.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		fillFormat2 = ((FillFormatCollection)theme.FormatScheme.BackgroundFillStyles).Add();
		fillFormat2.RotateWithShape = NullableBool.True;
		fillFormat2.FillType = FillType.Gradient;
		fillFormat2.GradientFormat.GradientShape = GradientShape.Radial;
		((GradientFormat)fillFormat2.GradientFormat).method_6(0.5f, -0.8f, 0f - ((GradientFormat)fillFormat2.GradientFormat).FillToRectangleX, 0f - ((GradientFormat)fillFormat2.GradientFormat).FillToRectangleY);
		ColorFormat colorFormat2 = new ColorFormat(((FillFormat)fillFormat2).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.Tint, 0.4f);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3.5f);
		((GradientStopCollection)fillFormat2.GradientFormat.GradientStops).Add(0f, colorFormat2);
		colorFormat2 = new ColorFormat(((FillFormat)fillFormat2).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.Tint, 0.45f);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.Shade, 0.99f);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3.5f);
		((GradientStopCollection)fillFormat2.GradientFormat.GradientStops).Add(0.4f, colorFormat2);
		colorFormat2 = new ColorFormat(((FillFormat)fillFormat2).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.Shade, 0.2f);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 2.55f);
		((GradientStopCollection)fillFormat2.GradientFormat.GradientStops).Add(1f, colorFormat2);
		fillFormat2 = ((FillFormatCollection)theme.FormatScheme.BackgroundFillStyles).Add();
		fillFormat2.RotateWithShape = NullableBool.True;
		fillFormat2.FillType = FillType.Gradient;
		fillFormat2.GradientFormat.GradientShape = GradientShape.Radial;
		((GradientFormat)fillFormat2.GradientFormat).method_6(0.5f, 0.5f, 0f - ((GradientFormat)fillFormat2.GradientFormat).FillToRectangleX, 0f - ((GradientFormat)fillFormat2.GradientFormat).FillToRectangleY);
		colorFormat2 = new ColorFormat(((FillFormat)fillFormat2).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.Tint, 0.8f);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3f);
		((GradientStopCollection)fillFormat2.GradientFormat.GradientStops).Add(0f, colorFormat2);
		colorFormat2 = new ColorFormat(((FillFormat)fillFormat2).Parent as ISlideComponent, SchemeColor.StyleColor);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.Shade, 0.3f);
		colorFormat2.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 2f);
		((GradientStopCollection)fillFormat2.GradientFormat.GradientStops).Add(1f, colorFormat2);
	}
}
