using System.Drawing;
using Aspose.Slides;
using Aspose.Slides.Effects;
using Aspose.Slides.Theme;

namespace ns4;

internal class Class1074
{
	internal static void smethod_0(FormatScheme formatScheme)
	{
		formatScheme.Name = "Office";
		FillFormatCollection fillFormatCollection = (FillFormatCollection)formatScheme.FillStyles;
		fillFormatCollection.list_0.Clear();
		FillFormat fillFormat = (FillFormat)fillFormatCollection.Add();
		fillFormat.FillType = FillType.Solid;
		fillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		FillFormat fillFormat2 = (FillFormat)fillFormatCollection.Add();
		fillFormat2.FillType = FillType.Gradient;
		fillFormat2.RotateWithShape = NullableBool.True;
		fillFormat2.GradientFormat.GradientShape = GradientShape.Linear;
		fillFormat2.GradientFormat.LinearGradientAngle = 270f;
		fillFormat2.GradientFormat.LinearGradientScaled = NullableBool.True;
		IGradientStop gradientStop = fillFormat2.GradientFormat.GradientStops.Add(0f, SchemeColor.StyleColor);
		gradientStop.Color.ColorTransform.Add(ColorTransformOperation.Tint, 0.5f);
		gradientStop.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3f);
		gradientStop = fillFormat2.GradientFormat.GradientStops.Add(0.35f, SchemeColor.StyleColor);
		gradientStop.Color.ColorTransform.Add(ColorTransformOperation.Tint, 0.37f);
		gradientStop.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3f);
		gradientStop = fillFormat2.GradientFormat.GradientStops.Add(1f, SchemeColor.StyleColor);
		gradientStop.Color.ColorTransform.Add(ColorTransformOperation.Tint, 0.15f);
		gradientStop.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3.5f);
		FillFormat fillFormat3 = (FillFormat)fillFormatCollection.Add();
		fillFormat3.FillType = FillType.Gradient;
		fillFormat3.RotateWithShape = NullableBool.True;
		fillFormat3.GradientFormat.GradientShape = GradientShape.Linear;
		fillFormat3.GradientFormat.LinearGradientAngle = 270f;
		fillFormat3.GradientFormat.LinearGradientScaled = NullableBool.False;
		IGradientStop gradientStop2 = fillFormat3.GradientFormat.GradientStops.Add(0f, SchemeColor.StyleColor);
		gradientStop2.Color.ColorTransform.Add(ColorTransformOperation.Shade, 0.51f);
		gradientStop2.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.3f);
		gradientStop2 = fillFormat3.GradientFormat.GradientStops.Add(0.8f, SchemeColor.StyleColor);
		gradientStop2.Color.ColorTransform.Add(ColorTransformOperation.Shade, 0.93f);
		gradientStop2.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.3f);
		gradientStop2 = fillFormat3.GradientFormat.GradientStops.Add(1f, SchemeColor.StyleColor);
		gradientStop2.Color.ColorTransform.Add(ColorTransformOperation.Shade, 0.94f);
		gradientStop2.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.35f);
		LineFormatCollection lineFormatCollection = (LineFormatCollection)formatScheme.LineStyles;
		lineFormatCollection.Clear();
		ILineFormat lineFormat = lineFormatCollection.Add();
		lineFormat.FillFormat.FillType = FillType.Solid;
		IColorFormat solidFillColor = lineFormat.FillFormat.SolidFillColor;
		solidFillColor.SchemeColor = SchemeColor.StyleColor;
		solidFillColor.ColorTransform.Add(ColorTransformOperation.Shade, 0.95f);
		solidFillColor.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 1.05f);
		lineFormat.DashStyle = LineDashStyle.Solid;
		lineFormat.Width = 0.75;
		lineFormat.CapStyle = LineCapStyle.Flat;
		lineFormat.Style = LineStyle.Single;
		lineFormat.Alignment = LineAlignment.Center;
		ILineFormat lineFormat2 = lineFormatCollection.Add();
		lineFormat2.FillFormat.FillType = FillType.Solid;
		lineFormat2.FillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		lineFormat2.DashStyle = LineDashStyle.Solid;
		lineFormat2.Width = 2.0;
		lineFormat2.CapStyle = LineCapStyle.Flat;
		lineFormat2.Style = LineStyle.Single;
		lineFormat2.Alignment = LineAlignment.Center;
		ILineFormat lineFormat3 = lineFormatCollection.Add();
		lineFormat3.FillFormat.FillType = FillType.Solid;
		lineFormat3.FillFormat.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		lineFormat3.DashStyle = LineDashStyle.Solid;
		lineFormat3.Width = 3.0;
		lineFormat3.CapStyle = LineCapStyle.Flat;
		lineFormat3.Style = LineStyle.Single;
		lineFormat3.Alignment = LineAlignment.Center;
		EffectStyleCollection effectStyleCollection = (EffectStyleCollection)formatScheme.EffectStyles;
		effectStyleCollection.list_0.Clear();
		IEffectStyle effectStyle = effectStyleCollection.Add();
		effectStyle.EffectFormat.EnableOuterShadowEffect();
		IOuterShadow outerShadowEffect = effectStyle.EffectFormat.OuterShadowEffect;
		outerShadowEffect.BlurRadius = 3.1496062992125986;
		outerShadowEffect.Direction = 90f;
		outerShadowEffect.Distance = 1.5748031496062993;
		outerShadowEffect.RotateShadowWithShape = false;
		outerShadowEffect.ShadowColor.Color = default(Color);
		outerShadowEffect.ShadowColor.ColorTransform.Clear();
		outerShadowEffect.ShadowColor.ColorTransform.Add(ColorTransformOperation.SetAlpha, 0.38f);
		IEffectStyle effectStyle2 = effectStyleCollection.Add();
		effectStyle2.EffectFormat.EnableOuterShadowEffect();
		IOuterShadow outerShadowEffect2 = effectStyle2.EffectFormat.OuterShadowEffect;
		outerShadowEffect2.BlurRadius = 3.1496062992125986;
		outerShadowEffect2.Direction = 90f;
		outerShadowEffect2.Distance = 1.811023622047244;
		outerShadowEffect2.RotateShadowWithShape = false;
		outerShadowEffect2.ShadowColor.Color = default(Color);
		outerShadowEffect2.ShadowColor.ColorTransform.Clear();
		outerShadowEffect2.ShadowColor.ColorTransform.Add(ColorTransformOperation.SetAlpha, 0.35f);
		IEffectStyle effectStyle3 = effectStyleCollection.Add();
		effectStyle3.EffectFormat.EnableOuterShadowEffect();
		IOuterShadow outerShadowEffect3 = effectStyle3.EffectFormat.OuterShadowEffect;
		outerShadowEffect3.BlurRadius = 3.1496062992125986;
		outerShadowEffect3.Direction = 90f;
		outerShadowEffect3.Distance = 1.811023622047244;
		outerShadowEffect3.RotateShadowWithShape = false;
		outerShadowEffect3.ShadowColor.Color = default(Color);
		outerShadowEffect3.ShadowColor.ColorTransform.Clear();
		outerShadowEffect3.ShadowColor.ColorTransform.Add(ColorTransformOperation.SetAlpha, 0.35f);
		effectStyle3.ThreeDFormat.Camera.CameraType = CameraPresetType.OrthographicFront;
		effectStyle3.ThreeDFormat.Camera.SetRotation(0f, 0f, 0f);
		effectStyle3.ThreeDFormat.LightRig.Direction = LightingDirection.Top;
		effectStyle3.ThreeDFormat.LightRig.LightType = LightRigPresetType.ThreePt;
		effectStyle3.ThreeDFormat.LightRig.SetRotation(0f, 0f, 20f);
		effectStyle3.ThreeDFormat.BevelTop.BevelType = BevelPresetType.Circle;
		effectStyle3.ThreeDFormat.BevelTop.Width = 5.0;
		effectStyle3.ThreeDFormat.BevelTop.Height = 2.0;
		FillFormatCollection fillFormatCollection2 = (FillFormatCollection)formatScheme.BackgroundFillStyles;
		fillFormatCollection2.list_0.Clear();
		FillFormat fillFormat4 = (FillFormat)fillFormatCollection2.Add();
		fillFormat4.FillType = FillType.Solid;
		fillFormat4.SolidFillColor.SchemeColor = SchemeColor.StyleColor;
		FillFormat fillFormat5 = (FillFormat)fillFormatCollection2.Add();
		fillFormat5.FillType = FillType.Gradient;
		fillFormat5.RotateWithShape = NullableBool.True;
		fillFormat5.GradientFormat.GradientShape = GradientShape.Radial;
		((GradientFormat)fillFormat5.GradientFormat).method_6(0.5f, -0.8f, 0f, 0f);
		IGradientStop gradientStop3 = fillFormat5.GradientFormat.GradientStops.Add(0f, SchemeColor.StyleColor);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.Tint, 0.4f);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3.5f);
		gradientStop3 = fillFormat5.GradientFormat.GradientStops.Add(0.4f, SchemeColor.StyleColor);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.Tint, 0.45f);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.Shade, 0.99f);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3.5f);
		gradientStop3 = fillFormat5.GradientFormat.GradientStops.Add(1f, SchemeColor.StyleColor);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.Shade, 0.2f);
		gradientStop3.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 2.55f);
		FillFormat fillFormat6 = (FillFormat)fillFormatCollection2.Add();
		fillFormat6.FillType = FillType.Gradient;
		fillFormat6.RotateWithShape = NullableBool.True;
		fillFormat6.GradientFormat.GradientShape = GradientShape.Radial;
		((GradientFormat)fillFormat6.GradientFormat).method_6(0.5f, 0.5f, 0f, 0f);
		IGradientStop gradientStop4 = fillFormat6.GradientFormat.GradientStops.Add(0f, SchemeColor.StyleColor);
		gradientStop4.Color.ColorTransform.Add(ColorTransformOperation.Tint, 0.8f);
		gradientStop4.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 3f);
		gradientStop4 = fillFormat6.GradientFormat.GradientStops.Add(1f, SchemeColor.StyleColor);
		gradientStop4.Color.ColorTransform.Add(ColorTransformOperation.Shade, 0.3f);
		gradientStop4.Color.ColorTransform.Add(ColorTransformOperation.MultiplySaturation, 2f);
	}
}
