using System;
using System.Drawing;
using Aspose.Slides;

namespace ns4;

internal class Class1079
{
	internal static MasterSlide smethod_0(Presentation pres)
	{
		MasterSlide masterSlide = new MasterSlide(pres);
		masterSlide.PPTXUnsupportedProps.SlideId = pres.PPTXUnsupportedProps.method_2();
		masterSlide.Background.Type = BackgroundType.Themed;
		masterSlide.Background.StyleIndex = 1;
		masterSlide.Background.StyleColor.SchemeColor = SchemeColor.Background1;
		masterSlide.groupShape_0.RawFrameImpl.vmethod_0(0.0, 0.0, 0.0, 0.0);
		masterSlide.groupShape_0.RawFrameImpl.ChildRect = new RectangleF(0f, 0f, 0f, 0f);
		masterSlide.groupShape_0.effectFormat_0 = new EffectFormat(masterSlide.groupShape_0);
		masterSlide.groupShape_0.AlternativeText = "";
		masterSlide.groupShape_0.Name = "";
		AutoShape autoShape = new AutoShape(masterSlide);
		autoShape.RawFrameImpl.vmethod_0(36.0, 21.62503937007874, 648.0, 90.0);
		autoShape.Geometry.Preset = ShapeType.Rectangle;
		autoShape.AlternativeText = "";
		autoShape.Name = "Title Placeholder 1";
		autoShape.method_0(Orientation.Horizontal, PlaceholderSize.Full, PlaceholderType.Title, 0u, hasCustomPrompt: false);
		autoShape.ShapeLock.GroupingLocked = true;
		autoShape.AddTextFrame("");
		autoShape.TextFrame.Paragraphs.Clear();
		autoShape.TextFrame.TextFrameFormat.AutofitType = TextAutofitType.Normal;
		autoShape.TextFrame.TextFrameFormat.TextVerticalType = TextVerticalType.Horizontal;
		autoShape.TextFrame.TextFrameFormat.MarginLeft = 7.2;
		autoShape.TextFrame.TextFrameFormat.MarginTop = 3.6;
		autoShape.TextFrame.TextFrameFormat.MarginRight = 7.2;
		autoShape.TextFrame.TextFrameFormat.MarginBottom = 3.6;
		((TextFrameFormat)autoShape.TextFrame.TextFrameFormat).RightToLeftColumns = false;
		autoShape.TextFrame.TextFrameFormat.AnchoringType = TextAnchorType.Center;
		Paragraph paragraph = new Paragraph();
		Portion portion = new Portion();
		portion.PortionFormat.LanguageId = "en-US";
		portion.PortionFormat.SmartTagClean = false;
		portion.TextInternal = "Click to edit Master title style";
		paragraph.Portions.Add(portion);
		Portion portion2 = new Portion();
		portion2.PortionFormat.LanguageId = "en-US";
		paragraph.Portions.Add(portion2);
		autoShape.TextFrame.Paragraphs.Add(paragraph);
		((ShapeCollection)masterSlide.groupShape_0.Shapes).Add(autoShape);
		autoShape.method_26();
		AutoShape autoShape2 = new AutoShape(masterSlide);
		autoShape2.RawFrameImpl.vmethod_0(36.0, 126.0, 648.0, 356.37503937007875);
		autoShape2.Geometry.Preset = ShapeType.Rectangle;
		autoShape2.AlternativeText = "";
		autoShape2.Name = "Text Placeholder 2";
		autoShape2.method_0(Orientation.Horizontal, PlaceholderSize.Full, PlaceholderType.Body, 1u, hasCustomPrompt: false);
		autoShape2.ShapeLock.GroupingLocked = true;
		autoShape2.AddTextFrame("");
		autoShape2.TextFrame.Paragraphs.Clear();
		autoShape2.TextFrame.TextFrameFormat.AutofitType = TextAutofitType.Normal;
		autoShape2.TextFrame.TextFrameFormat.TextVerticalType = TextVerticalType.Horizontal;
		autoShape2.TextFrame.TextFrameFormat.MarginLeft = 7.2;
		autoShape2.TextFrame.TextFrameFormat.MarginTop = 3.6;
		autoShape2.TextFrame.TextFrameFormat.MarginRight = 7.2;
		autoShape2.TextFrame.TextFrameFormat.MarginBottom = 3.6;
		((TextFrameFormat)autoShape2.TextFrame.TextFrameFormat).RightToLeftColumns = false;
		Paragraph paragraph2 = new Paragraph();
		paragraph2.ParagraphFormat.Depth = 0;
		Portion portion3 = new Portion();
		portion3.PortionFormat.LanguageId = "en-US";
		portion3.PortionFormat.SmartTagClean = false;
		portion3.TextInternal = "Click to edit Master text styles";
		paragraph2.Portions.Add(portion3);
		autoShape2.TextFrame.Paragraphs.Add(paragraph2);
		paragraph2 = new Paragraph();
		paragraph2.ParagraphFormat.Depth = 1;
		portion3 = new Portion();
		portion3.PortionFormat.LanguageId = "en-US";
		portion3.PortionFormat.SmartTagClean = false;
		portion3.TextInternal = "Second level";
		paragraph2.Portions.Add(portion3);
		autoShape2.TextFrame.Paragraphs.Add(paragraph2);
		paragraph2 = new Paragraph();
		paragraph2.ParagraphFormat.Depth = 2;
		portion3 = new Portion();
		portion3.PortionFormat.LanguageId = "en-US";
		portion3.PortionFormat.SmartTagClean = false;
		portion3.TextInternal = "Third level";
		paragraph2.Portions.Add(portion3);
		autoShape2.TextFrame.Paragraphs.Add(paragraph2);
		paragraph2 = new Paragraph();
		paragraph2.ParagraphFormat.Depth = 3;
		portion3 = new Portion();
		portion3.PortionFormat.LanguageId = "en-US";
		portion3.PortionFormat.SmartTagClean = false;
		portion3.TextInternal = "Fourth level";
		paragraph2.Portions.Add(portion3);
		autoShape2.TextFrame.Paragraphs.Add(paragraph2);
		paragraph2 = new Paragraph();
		paragraph2.ParagraphFormat.Depth = 4;
		portion3 = new Portion();
		portion3.PortionFormat.LanguageId = "en-US";
		portion3.PortionFormat.SmartTagClean = false;
		portion3.TextInternal = "Fifth level";
		paragraph2.Portions.Add(portion3);
		Portion portion4 = new Portion();
		portion4.PortionFormat.LanguageId = "en-US";
		paragraph2.Portions.Add(portion4);
		autoShape2.TextFrame.Paragraphs.Add(paragraph2);
		((ShapeCollection)masterSlide.groupShape_0.Shapes).Add(autoShape2);
		autoShape2.method_26();
		AutoShape autoShape3 = new AutoShape(masterSlide);
		autoShape3.RawFrameImpl.vmethod_0(36.0, 500.5, 168.0, 28.75);
		autoShape3.Geometry.Preset = ShapeType.Rectangle;
		autoShape3.AlternativeText = "";
		autoShape3.Name = "Date Placeholder 3";
		autoShape3.method_0(Orientation.Horizontal, PlaceholderSize.Half, PlaceholderType.DateAndTime, 2u, hasCustomPrompt: false);
		autoShape3.ShapeLock.GroupingLocked = true;
		autoShape3.AddTextFrame("");
		autoShape3.TextFrame.Paragraphs.Clear();
		autoShape3.TextFrame.TextFrameFormat.TextVerticalType = TextVerticalType.Horizontal;
		autoShape3.TextFrame.TextFrameFormat.MarginLeft = 7.2;
		autoShape3.TextFrame.TextFrameFormat.MarginTop = 3.6;
		autoShape3.TextFrame.TextFrameFormat.MarginRight = 7.2;
		autoShape3.TextFrame.TextFrameFormat.MarginBottom = 3.6;
		((TextFrameFormat)autoShape3.TextFrame.TextFrameFormat).RightToLeftColumns = false;
		autoShape3.TextFrame.TextFrameFormat.AnchoringType = TextAnchorType.Center;
		((TextStyle)autoShape3.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		((TextStyle)autoShape3.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		((TextStyle)autoShape3.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.SolidFillColor.ColorTransform.Add(ColorTransformOperation.Tint, 0.75f);
		((TextStyle)autoShape3.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FontHeight = 12f;
		((TextStyle)autoShape3.TextFrame.TextFrameFormat.TextStyle).method_3(0).Alignment = TextAlignment.Left;
		Paragraph paragraph3 = new Paragraph();
		Portion portion5 = new Portion();
		portion5.AddField("datetimeFigureOut");
		((Field)portion5.Field).Guid = new Guid("E8FD0B7A-F5DD-4F40-B4CB-3B2C354B893A");
		portion5.PortionFormat.LanguageId = "en-US";
		portion5.PortionFormat.SmartTagClean = false;
		portion5.TextInternal = "11/7/2009";
		paragraph3.Portions.Add(portion5);
		Portion portion6 = new Portion();
		portion6.PortionFormat.LanguageId = "en-US";
		paragraph3.Portions.Add(portion6);
		autoShape3.TextFrame.Paragraphs.Add(paragraph3);
		((ShapeCollection)masterSlide.groupShape_0.Shapes).Add(autoShape3);
		autoShape3.method_26();
		AutoShape autoShape4 = new AutoShape(masterSlide);
		autoShape4.RawFrameImpl.vmethod_0(246.0, 500.5, 228.0, 28.75);
		autoShape4.Geometry.Preset = ShapeType.Rectangle;
		autoShape4.AlternativeText = "";
		autoShape4.Name = "Footer Placeholder 4";
		autoShape4.method_0(Orientation.Horizontal, PlaceholderSize.Quarter, PlaceholderType.Footer, 3u, hasCustomPrompt: false);
		autoShape4.ShapeLock.GroupingLocked = true;
		autoShape4.AddTextFrame("");
		autoShape4.TextFrame.Paragraphs.Clear();
		autoShape4.TextFrame.TextFrameFormat.TextVerticalType = TextVerticalType.Horizontal;
		autoShape4.TextFrame.TextFrameFormat.MarginLeft = 7.2;
		autoShape4.TextFrame.TextFrameFormat.MarginTop = 3.6;
		autoShape4.TextFrame.TextFrameFormat.MarginRight = 7.2;
		autoShape4.TextFrame.TextFrameFormat.MarginBottom = 3.6;
		((TextFrameFormat)autoShape4.TextFrame.TextFrameFormat).RightToLeftColumns = false;
		autoShape4.TextFrame.TextFrameFormat.AnchoringType = TextAnchorType.Center;
		((TextStyle)autoShape4.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		((TextStyle)autoShape4.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		((TextStyle)autoShape4.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.SolidFillColor.ColorTransform.Add(ColorTransformOperation.Tint, 0.75f);
		((TextStyle)autoShape4.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FontHeight = 12f;
		((TextStyle)autoShape4.TextFrame.TextFrameFormat.TextStyle).method_3(0).Alignment = TextAlignment.Center;
		Paragraph paragraph4 = new Paragraph();
		Portion portion7 = new Portion();
		portion7.PortionFormat.LanguageId = "en-US";
		paragraph4.Portions.Add(portion7);
		autoShape4.TextFrame.Paragraphs.Add(paragraph4);
		((ShapeCollection)masterSlide.groupShape_0.Shapes).Add(autoShape4);
		autoShape4.method_26();
		AutoShape autoShape5 = new AutoShape(masterSlide);
		autoShape5.RawFrameImpl.vmethod_0(516.0, 500.5, 168.0, 28.75);
		autoShape5.Geometry.Preset = ShapeType.Rectangle;
		autoShape5.AlternativeText = "";
		autoShape5.Name = "Slide Number Placeholder 5";
		autoShape5.method_0(Orientation.Horizontal, PlaceholderSize.Quarter, PlaceholderType.SlideNumber, 4u, hasCustomPrompt: false);
		autoShape5.ShapeLock.GroupingLocked = true;
		autoShape5.AddTextFrame("");
		autoShape5.TextFrame.Paragraphs.Clear();
		autoShape5.TextFrame.TextFrameFormat.TextVerticalType = TextVerticalType.Horizontal;
		autoShape5.TextFrame.TextFrameFormat.MarginLeft = 7.2;
		autoShape5.TextFrame.TextFrameFormat.MarginTop = 3.6;
		autoShape5.TextFrame.TextFrameFormat.MarginRight = 7.2;
		autoShape5.TextFrame.TextFrameFormat.MarginBottom = 3.6;
		((TextFrameFormat)autoShape5.TextFrame.TextFrameFormat).RightToLeftColumns = false;
		autoShape5.TextFrame.TextFrameFormat.AnchoringType = TextAnchorType.Center;
		((TextStyle)autoShape5.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		((TextStyle)autoShape5.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		((TextStyle)autoShape5.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FillFormat.SolidFillColor.ColorTransform.Add(ColorTransformOperation.Tint, 0.75f);
		((TextStyle)autoShape5.TextFrame.TextFrameFormat.TextStyle).method_3(0).DefaultPortionFormat.FontHeight = 12f;
		((TextStyle)autoShape5.TextFrame.TextFrameFormat.TextStyle).method_3(0).Alignment = TextAlignment.Right;
		Paragraph paragraph5 = new Paragraph();
		Portion portion8 = new Portion();
		portion8.AddField("slidenum");
		((Field)portion8.Field).Guid = new Guid("93AE1883-0942-4AA3-9DB2-9C7C3A0314B1");
		portion8.PortionFormat.LanguageId = "en-US";
		portion8.PortionFormat.SmartTagClean = false;
		portion8.TextInternal = "‹#›";
		paragraph5.Portions.Add(portion8);
		Portion portion9 = new Portion();
		portion9.PortionFormat.LanguageId = "en-US";
		paragraph5.Portions.Add(portion9);
		autoShape5.TextFrame.Paragraphs.Add(paragraph5);
		((ShapeCollection)masterSlide.groupShape_0.Shapes).Add(autoShape5);
		autoShape5.method_26();
		IParagraphFormat paragraphFormat = ((TextStyle)masterSlide.TitleStyle).method_3(0);
		paragraphFormat.SpaceBefore = 0f;
		paragraphFormat.Bullet.Type = BulletType.None;
		paragraphFormat.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat.DefaultPortionFormat.FontHeight = 44f;
		paragraphFormat.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat.DefaultPortionFormat.LatinFont = new FontData("+mj-lt");
		paragraphFormat.DefaultPortionFormat.EastAsianFont = new FontData("+mj-ea");
		paragraphFormat.DefaultPortionFormat.ComplexScriptFont = new FontData("+mj-cs");
		paragraphFormat.Alignment = TextAlignment.Center;
		paragraphFormat.DefaultTabSize = 72f;
		paragraphFormat.RightToLeft = NullableBool.False;
		paragraphFormat.EastAsianLineBreak = NullableBool.True;
		paragraphFormat.LatinLineBreak = NullableBool.False;
		paragraphFormat.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat2 = ((TextStyle)masterSlide.BodyStyle).method_3(0);
		paragraphFormat2.SpaceBefore = 20f;
		paragraphFormat2.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat2.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat2.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat2.Bullet.Font).CharSet = 0;
		paragraphFormat2.Bullet.Type = BulletType.Symbol;
		paragraphFormat2.Bullet.Char = '•';
		paragraphFormat2.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat2.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat2.DefaultPortionFormat.FontHeight = 32f;
		paragraphFormat2.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat2.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat2.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat2.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat2.Alignment = TextAlignment.Left;
		paragraphFormat2.MarginLeft = 27f;
		paragraphFormat2.Indent = -27f;
		paragraphFormat2.DefaultTabSize = 72f;
		paragraphFormat2.RightToLeft = NullableBool.False;
		paragraphFormat2.EastAsianLineBreak = NullableBool.True;
		paragraphFormat2.LatinLineBreak = NullableBool.False;
		paragraphFormat2.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat3 = ((TextStyle)masterSlide.BodyStyle).method_3(1);
		paragraphFormat3.SpaceBefore = 20f;
		paragraphFormat3.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat3.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat3.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat3.Bullet.Font).CharSet = 0;
		paragraphFormat3.Bullet.Type = BulletType.Symbol;
		paragraphFormat3.Bullet.Char = '–';
		paragraphFormat3.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat3.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat3.DefaultPortionFormat.FontHeight = 28f;
		paragraphFormat3.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat3.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat3.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat3.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat3.Alignment = TextAlignment.Left;
		paragraphFormat3.MarginLeft = 58.5f;
		paragraphFormat3.Indent = -22.5f;
		paragraphFormat3.DefaultTabSize = 72f;
		paragraphFormat3.RightToLeft = NullableBool.False;
		paragraphFormat3.EastAsianLineBreak = NullableBool.True;
		paragraphFormat3.LatinLineBreak = NullableBool.False;
		paragraphFormat3.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat4 = ((TextStyle)masterSlide.BodyStyle).method_3(2);
		paragraphFormat4.SpaceBefore = 20f;
		paragraphFormat4.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat4.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat4.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat4.Bullet.Font).CharSet = 0;
		paragraphFormat4.Bullet.Type = BulletType.Symbol;
		paragraphFormat4.Bullet.Char = '•';
		paragraphFormat4.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat4.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat4.DefaultPortionFormat.FontHeight = 24f;
		paragraphFormat4.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat4.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat4.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat4.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat4.Alignment = TextAlignment.Left;
		paragraphFormat4.MarginLeft = 90f;
		paragraphFormat4.Indent = -18f;
		paragraphFormat4.DefaultTabSize = 72f;
		paragraphFormat4.RightToLeft = NullableBool.False;
		paragraphFormat4.EastAsianLineBreak = NullableBool.True;
		paragraphFormat4.LatinLineBreak = NullableBool.False;
		paragraphFormat4.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat5 = ((TextStyle)masterSlide.BodyStyle).method_3(3);
		paragraphFormat5.SpaceBefore = 20f;
		paragraphFormat5.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat5.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat5.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat5.Bullet.Font).CharSet = 0;
		paragraphFormat5.Bullet.Type = BulletType.Symbol;
		paragraphFormat5.Bullet.Char = '–';
		paragraphFormat5.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat5.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat5.DefaultPortionFormat.FontHeight = 20f;
		paragraphFormat5.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat5.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat5.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat5.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat5.Alignment = TextAlignment.Left;
		paragraphFormat5.MarginLeft = 126f;
		paragraphFormat5.Indent = -18f;
		paragraphFormat5.DefaultTabSize = 72f;
		paragraphFormat5.RightToLeft = NullableBool.False;
		paragraphFormat5.EastAsianLineBreak = NullableBool.True;
		paragraphFormat5.LatinLineBreak = NullableBool.False;
		paragraphFormat5.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat6 = ((TextStyle)masterSlide.BodyStyle).method_3(4);
		paragraphFormat6.SpaceBefore = 20f;
		paragraphFormat6.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat6.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat6.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat6.Bullet.Font).CharSet = 0;
		paragraphFormat6.Bullet.Type = BulletType.Symbol;
		paragraphFormat6.Bullet.Char = '»';
		paragraphFormat6.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat6.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat6.DefaultPortionFormat.FontHeight = 20f;
		paragraphFormat6.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat6.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat6.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat6.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat6.Alignment = TextAlignment.Left;
		paragraphFormat6.MarginLeft = 162f;
		paragraphFormat6.Indent = -18f;
		paragraphFormat6.DefaultTabSize = 72f;
		paragraphFormat6.RightToLeft = NullableBool.False;
		paragraphFormat6.EastAsianLineBreak = NullableBool.True;
		paragraphFormat6.LatinLineBreak = NullableBool.False;
		paragraphFormat6.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat7 = ((TextStyle)masterSlide.BodyStyle).method_3(5);
		paragraphFormat7.SpaceBefore = 20f;
		paragraphFormat7.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat7.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat7.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat7.Bullet.Font).CharSet = 0;
		paragraphFormat7.Bullet.Type = BulletType.Symbol;
		paragraphFormat7.Bullet.Char = '•';
		paragraphFormat7.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat7.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat7.DefaultPortionFormat.FontHeight = 20f;
		paragraphFormat7.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat7.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat7.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat7.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat7.Alignment = TextAlignment.Left;
		paragraphFormat7.MarginLeft = 198f;
		paragraphFormat7.Indent = -18f;
		paragraphFormat7.DefaultTabSize = 72f;
		paragraphFormat7.RightToLeft = NullableBool.False;
		paragraphFormat7.EastAsianLineBreak = NullableBool.True;
		paragraphFormat7.LatinLineBreak = NullableBool.False;
		paragraphFormat7.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat8 = ((TextStyle)masterSlide.BodyStyle).method_3(6);
		paragraphFormat8.SpaceBefore = 20f;
		paragraphFormat8.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat8.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat8.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat8.Bullet.Font).CharSet = 0;
		paragraphFormat8.Bullet.Type = BulletType.Symbol;
		paragraphFormat8.Bullet.Char = '•';
		paragraphFormat8.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat8.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat8.DefaultPortionFormat.FontHeight = 20f;
		paragraphFormat8.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat8.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat8.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat8.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat8.Alignment = TextAlignment.Left;
		paragraphFormat8.MarginLeft = 234f;
		paragraphFormat8.Indent = -18f;
		paragraphFormat8.DefaultTabSize = 72f;
		paragraphFormat8.RightToLeft = NullableBool.False;
		paragraphFormat8.EastAsianLineBreak = NullableBool.True;
		paragraphFormat8.LatinLineBreak = NullableBool.False;
		paragraphFormat8.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat9 = ((TextStyle)masterSlide.BodyStyle).method_3(7);
		paragraphFormat9.SpaceBefore = 20f;
		paragraphFormat9.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat9.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat9.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat9.Bullet.Font).CharSet = 0;
		paragraphFormat9.Bullet.Type = BulletType.Symbol;
		paragraphFormat9.Bullet.Char = '•';
		paragraphFormat9.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat9.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat9.DefaultPortionFormat.FontHeight = 20f;
		paragraphFormat9.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat9.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat9.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat9.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat9.Alignment = TextAlignment.Left;
		paragraphFormat9.MarginLeft = 270f;
		paragraphFormat9.Indent = -18f;
		paragraphFormat9.DefaultTabSize = 72f;
		paragraphFormat9.RightToLeft = NullableBool.False;
		paragraphFormat9.EastAsianLineBreak = NullableBool.True;
		paragraphFormat9.LatinLineBreak = NullableBool.False;
		paragraphFormat9.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat10 = ((TextStyle)masterSlide.BodyStyle).method_3(8);
		paragraphFormat10.SpaceBefore = 20f;
		paragraphFormat10.Bullet.IsBulletHardFont = NullableBool.True;
		paragraphFormat10.Bullet.Font = new FontData("Arial");
		((FontData)paragraphFormat10.Bullet.Font).PitchFamily = 34;
		((FontData)paragraphFormat10.Bullet.Font).CharSet = 0;
		paragraphFormat10.Bullet.Type = BulletType.Symbol;
		paragraphFormat10.Bullet.Char = '•';
		paragraphFormat10.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat10.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat10.DefaultPortionFormat.FontHeight = 20f;
		paragraphFormat10.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat10.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat10.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat10.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat10.Alignment = TextAlignment.Left;
		paragraphFormat10.MarginLeft = 306f;
		paragraphFormat10.Indent = -18f;
		paragraphFormat10.DefaultTabSize = 72f;
		paragraphFormat10.RightToLeft = NullableBool.False;
		paragraphFormat10.EastAsianLineBreak = NullableBool.True;
		paragraphFormat10.LatinLineBreak = NullableBool.False;
		paragraphFormat10.HangingPunctuation = NullableBool.True;
		masterSlide.OtherStyle.DefaultParagraphFormat.DefaultPortionFormat.LanguageId = "en-US";
		IParagraphFormat paragraphFormat11 = ((TextStyle)masterSlide.OtherStyle).method_3(0);
		paragraphFormat11.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat11.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat11.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat11.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat11.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat11.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat11.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat11.Alignment = TextAlignment.Left;
		paragraphFormat11.MarginLeft = 0f;
		paragraphFormat11.DefaultTabSize = 72f;
		paragraphFormat11.RightToLeft = NullableBool.False;
		paragraphFormat11.EastAsianLineBreak = NullableBool.True;
		paragraphFormat11.LatinLineBreak = NullableBool.False;
		paragraphFormat11.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat12 = ((TextStyle)masterSlide.OtherStyle).method_3(1);
		paragraphFormat12.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat12.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat12.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat12.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat12.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat12.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat12.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat12.Alignment = TextAlignment.Left;
		paragraphFormat12.MarginLeft = 36f;
		paragraphFormat12.DefaultTabSize = 72f;
		paragraphFormat12.RightToLeft = NullableBool.False;
		paragraphFormat12.EastAsianLineBreak = NullableBool.True;
		paragraphFormat12.LatinLineBreak = NullableBool.False;
		paragraphFormat12.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat13 = ((TextStyle)masterSlide.OtherStyle).method_3(2);
		paragraphFormat13.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat13.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat13.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat13.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat13.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat13.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat13.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat13.Alignment = TextAlignment.Left;
		paragraphFormat13.MarginLeft = 72f;
		paragraphFormat13.DefaultTabSize = 72f;
		paragraphFormat13.RightToLeft = NullableBool.False;
		paragraphFormat13.EastAsianLineBreak = NullableBool.True;
		paragraphFormat13.LatinLineBreak = NullableBool.False;
		paragraphFormat13.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat14 = ((TextStyle)masterSlide.OtherStyle).method_3(3);
		paragraphFormat14.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat14.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat14.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat14.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat14.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat14.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat14.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat14.Alignment = TextAlignment.Left;
		paragraphFormat14.MarginLeft = 108f;
		paragraphFormat14.DefaultTabSize = 72f;
		paragraphFormat14.RightToLeft = NullableBool.False;
		paragraphFormat14.EastAsianLineBreak = NullableBool.True;
		paragraphFormat14.LatinLineBreak = NullableBool.False;
		paragraphFormat14.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat15 = ((TextStyle)masterSlide.OtherStyle).method_3(4);
		paragraphFormat15.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat15.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat15.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat15.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat15.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat15.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat15.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat15.Alignment = TextAlignment.Left;
		paragraphFormat15.MarginLeft = 144f;
		paragraphFormat15.DefaultTabSize = 72f;
		paragraphFormat15.RightToLeft = NullableBool.False;
		paragraphFormat15.EastAsianLineBreak = NullableBool.True;
		paragraphFormat15.LatinLineBreak = NullableBool.False;
		paragraphFormat15.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat16 = ((TextStyle)masterSlide.OtherStyle).method_3(5);
		paragraphFormat16.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat16.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat16.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat16.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat16.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat16.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat16.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat16.Alignment = TextAlignment.Left;
		paragraphFormat16.MarginLeft = 180f;
		paragraphFormat16.DefaultTabSize = 72f;
		paragraphFormat16.RightToLeft = NullableBool.False;
		paragraphFormat16.EastAsianLineBreak = NullableBool.True;
		paragraphFormat16.LatinLineBreak = NullableBool.False;
		paragraphFormat16.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat17 = ((TextStyle)masterSlide.OtherStyle).method_3(6);
		paragraphFormat17.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat17.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat17.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat17.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat17.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat17.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat17.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat17.Alignment = TextAlignment.Left;
		paragraphFormat17.MarginLeft = 216f;
		paragraphFormat17.DefaultTabSize = 72f;
		paragraphFormat17.RightToLeft = NullableBool.False;
		paragraphFormat17.EastAsianLineBreak = NullableBool.True;
		paragraphFormat17.LatinLineBreak = NullableBool.False;
		paragraphFormat17.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat18 = ((TextStyle)masterSlide.OtherStyle).method_3(7);
		paragraphFormat18.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat18.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat18.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat18.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat18.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat18.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat18.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat18.Alignment = TextAlignment.Left;
		paragraphFormat18.MarginLeft = 252f;
		paragraphFormat18.DefaultTabSize = 72f;
		paragraphFormat18.RightToLeft = NullableBool.False;
		paragraphFormat18.EastAsianLineBreak = NullableBool.True;
		paragraphFormat18.LatinLineBreak = NullableBool.False;
		paragraphFormat18.HangingPunctuation = NullableBool.True;
		IParagraphFormat paragraphFormat19 = ((TextStyle)masterSlide.OtherStyle).method_3(8);
		paragraphFormat19.DefaultPortionFormat.FillFormat.FillType = FillType.Solid;
		paragraphFormat19.DefaultPortionFormat.FillFormat.SolidFillColor.SchemeColor = SchemeColor.Text1;
		paragraphFormat19.DefaultPortionFormat.FontHeight = 18f;
		paragraphFormat19.DefaultPortionFormat.KerningMinimalSize = 12f;
		paragraphFormat19.DefaultPortionFormat.LatinFont = new FontData("+mn-lt");
		paragraphFormat19.DefaultPortionFormat.EastAsianFont = new FontData("+mn-ea");
		paragraphFormat19.DefaultPortionFormat.ComplexScriptFont = new FontData("+mn-cs");
		paragraphFormat19.Alignment = TextAlignment.Left;
		paragraphFormat19.MarginLeft = 288f;
		paragraphFormat19.DefaultTabSize = 72f;
		paragraphFormat19.RightToLeft = NullableBool.False;
		paragraphFormat19.EastAsianLineBreak = NullableBool.True;
		paragraphFormat19.LatinLineBreak = NullableBool.False;
		paragraphFormat19.HangingPunctuation = NullableBool.True;
		return masterSlide;
	}
}
